# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-rootelegram

# >> macros
# << macros
%define __provides_exclude_from ^%{_datadir}/.*$
%define __requires_exclude ^(libtdjson|libavcodec|libavutil|libswresample|libvpx|libopus|libvorbisenc|libvorbis|libtheoradec|libtheoraenc|libwebpmux|libwebp|libopenjp2|libspeex|libogg|libsharpyuv)\..*$
%define _binary_payload w6.xzdio

Summary:    RooTelegram is a Telegram client for Sailfish OS
Version:    3.0
Release:    1
Group:      Qt/Qt
License:    GPL-3.0
URL:        https://github.com/RootGPT-YouTube/RooTelegram-SailfishOS
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-rootelegram.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Sql)
BuildRequires:  pkgconfig(Qt5Multimedia)
BuildRequires:  pkgconfig(Qt5Positioning)
BuildRequires:  pkgconfig(nemonotifications-qt5)
BuildRequires:  pkgconfig(openssl)
BuildRequires:  pkgconfig(zlib)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  gperf
BuildRequires:  desktop-file-utils

%description
RooTelegram is a Telegram client for Sailfish OS


%pre
pkill -9 harbour-rootelegram >/dev/null 2>&1 || true
exit 0

%preun
pkill -9 harbour-rootelegram >/dev/null 2>&1 || true
exit 0

%posttrans
for d in /home/*/.cache/QtProject/qmlcache; do
  [ -d "$d" ] && rm -f "$d"/*.qmlc "$d"/*.jsc 2>/dev/null || true
done
systemctl try-restart sailjaild >/dev/null 2>&1 || true
update-desktop-database /usr/share/applications >/dev/null 2>&1 || true
for u in /home/*; do
  rm -f "$u"/.local/share/applications/harbour-rootelegram-open-url.desktop 2>/dev/null || true
  rm -f "$u"/.local/share/dbus-1/services/de.ygriega.rootelegram.service 2>/dev/null || true
  [ -d "$u"/.local/share/applications ] && update-desktop-database "$u"/.local/share/applications >/dev/null 2>&1 || true
done
systemctl --global enable harbour-rootelegram.service >/dev/null 2>&1 || true
sh /usr/share/harbour-rootelegram/bin/restart-voicecall.sh >/dev/null 2>&1 || true
exit 0

%postun
if [ "$1" = 0 ]; then
  systemctl --global disable harbour-rootelegram.service >/dev/null 2>&1 || true
fi
exit 0

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# rlottie: crea directory e config.h vuoto (il submodule è già stato inizializzato)
mkdir -p rlottie/src/vector
touch rlottie/src/vector/config.h
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# Plugin voicecall: vive nello stesso progetto e nello stesso RPM dell'app, ma
# il .so DEVE stare in /usr/lib64/voicecall/plugins perche' voicecall-manager
# carica i provider dentro il proprio processo (non esiste un modo per
# registrarsi da fuori: il suo D-Bus e' di sola consultazione).
%ifarch aarch64 armv7hl
# ⭐ SHADOW BUILD (dal 2026-09-17): la cartella di compilazione NON e' quella dei
# sorgenti, quindi "cd voicecallplugin" qui non trova niente. Ricaviamo tutto dal
# Makefile che qmake ha appena generato, che porta scritti in testa sia il comando
# qmake completo (con i flag della SDK) sia il .pro di partenza:
#     # Project:  ../../harbour-rootelegram/harbour-rootelegram.pro
#     # Command: /usr/lib64/qt5/bin/qmake '<flag>' ... -o Makefile <quel .pro>
# Usiamo il qmake REALE (percorso assoluto): il wrapper della SDK aggiunge da se'
# la cartella del progetto principale, e qui il progetto lo scegliamo noi.
# In una build in-tree "# Project:" e' un nome nudo ⇒ dirname da "." e funziona uguale.
RT_QMAKE_CMD="$(sed -n 's/^# Command: //p' Makefile | head -1)"
RT_SRC_PRO="$(sed -n 's/^# Project: *//p' Makefile | head -1)"
RT_SRC_DIR="$(cd "$(dirname "$RT_SRC_PRO")" && pwd)"
test -n "$RT_QMAKE_CMD" || { echo "spec: non riesco a leggere il comando qmake dal Makefile"; exit 1; }
test -f "$RT_SRC_DIR/voicecallplugin/rootelegram-voicecall-plugin.pro" || { echo "spec: sorgenti del plugin non trovati in $RT_SRC_DIR"; exit 1; }
mkdir -p voicecallplugin
cd voicecallplugin
# Pulizia obbligatoria: se in questa cartella sono rimasti oggetti di una build
# precedente (magari di UN'ALTRA architettura), make li riuserebbe e il link
# fallirebbe con simboli dalla firma sbagliata, tipo operator new(unsigned int)
# su aarch64. Successo il 2026-08-15.
rm -f *.o moc_* Makefile *.so
eval "${RT_QMAKE_CMD% *} $RT_SRC_DIR/voicecallplugin/rootelegram-voicecall-plugin.pro"
make %{?_smp_mflags}
cd ..
%endif
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
%ifarch aarch64 armv7hl
mkdir -p %{buildroot}/usr/lib64/voicecall/plugins
install -m 644 voicecallplugin/librootelegram-voicecall-plugin.so \
    %{buildroot}/usr/lib64/voicecall/plugins/librootelegram-voicecall-plugin.so
%endif
# Harbour: gli asset (SVG emoji) non devono essere eseguibili
find %{buildroot}%{_datadir}/%{name} -name '*.svg' -exec chmod 644 {} +
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/applications/%{name}-open-url.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
/usr/lib/systemd/user/%{name}.service
# >> files
%ifarch aarch64 armv7hl
/usr/lib64/voicecall/plugins/librootelegram-voicecall-plugin.so
%endif
# << files
