#!/usr/bin/env python3
"""
Genera qml/js/emoji_data.js da iamcal/emoji-data.

Cose che fa:
- Normalizza i nomi file SVG in qml/js/emoji/ al formato canonico usato da
  twemoji.js Emoji.getEmojiPath(): lowercase hex, separatore "-", niente FE0F,
  niente leading zero (es. "0023 fe0f 20e3.svg" -> "23-20e3.svg").
- Filtra "Component" (skin tone modifier) e ignora le skin_variations: solo
  varianti gialle base.
- Tiene solo le emoji il cui SVG e' effettivamente presente.
- Raggruppa per categoria in ordine sort_order.
- Emette qml/js/emoji_data.js con CATEGORIES e NAMES (per search).

Prerequisito: scripts/emoji-data.json scaricato da
https://raw.githubusercontent.com/iamcal/emoji-data/master/emoji.json
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EMOJI_DIR = ROOT / "qml" / "js" / "emoji"
DATA_JSON = Path(__file__).resolve().parent / "emoji-data.json"
OUT_JS = ROOT / "qml" / "js" / "emoji_data.js"

# (key interna, label categoria iamcal, codepoint icona rappresentativa)
CATEGORY_ORDER = [
    ("smileys",  "Smileys & Emotion", "1F600"),  # 😀
    ("people",   "People & Body",     "1F44B"),  # 👋
    ("animals",  "Animals & Nature",  "1F436"),  # 🐶
    ("food",     "Food & Drink",      "1F354"),  # 🍔
    ("activity", "Activities",        "26BD"),   # ⚽
    ("travel",   "Travel & Places",   "1F697"),  # 🚗
    ("objects",  "Objects",           "1F4A1"),  # 💡
    ("symbols",  "Symbols",           "2764"),   # ❤
    ("flags",    "Flags",             "1F3C1"),  # 🏁
]
KEY_BY_CATEGORY = {label: key for key, label, _ in CATEGORY_ORDER}


def canonical_name(unified: str) -> str:
    """1F600 -> 1f600.svg; 0023-FE0F-20E3 -> 23-20e3.svg"""
    parts = [p for p in unified.split("-") if p.upper() != "FE0F"]
    parts = [format(int(p, 16), "x") for p in parts]
    return "-".join(parts) + ".svg"


def unicode_from(unified: str) -> str:
    """1F468-200D-1F469-200D-1F466 -> '👨‍👩‍👦' (FE0F preservato)"""
    return "".join(chr(int(cp, 16)) for cp in unified.split("-"))


def normalize_filenames(emoji_dir: Path) -> None:
    renamed = removed_dup = 0
    for f in list(emoji_dir.iterdir()):
        if not f.is_file() or f.suffix != ".svg":
            continue
        stem = re.sub(r"\s+", "-", f.stem)
        parts = [p for p in stem.split("-") if p.upper() != "FE0F"]
        try:
            parts = [format(int(p, 16), "x") for p in parts]
        except ValueError:
            continue
        new_name = "-".join(parts) + ".svg"
        if new_name == f.name:
            continue
        target = emoji_dir / new_name
        if target.exists():
            f.unlink()
            removed_dup += 1
        else:
            f.rename(target)
            renamed += 1
    print(f"[normalize] renamed={renamed} removed_dup={removed_dup}")


def main() -> int:
    if not DATA_JSON.exists():
        sys.stderr.write(f"Manca {DATA_JSON}. Esegui:\n  curl -sSL -o {DATA_JSON} "
                         "https://raw.githubusercontent.com/iamcal/emoji-data/master/emoji.json\n")
        return 1

    normalize_filenames(EMOJI_DIR)
    available = {f.name for f in EMOJI_DIR.iterdir() if f.suffix == ".svg"}
    print(f"[scan] {len(available)} SVG disponibili")

    data = json.loads(DATA_JSON.read_text())
    by_cat = {key: [] for key, _, _ in CATEGORY_ORDER}
    names_map = {}
    missing = 0

    for entry in sorted(data, key=lambda e: e.get("sort_order", 999999)):
        cat = entry.get("category", "")
        if cat == "Component":
            continue
        key = KEY_BY_CATEGORY.get(cat)
        if not key:
            continue
        unified = entry["unified"]
        fname = canonical_name(unified)
        if fname not in available:
            nq = entry.get("non_qualified")
            if nq:
                alt = canonical_name(nq)
                if alt in available:
                    fname = alt
        if fname not in available:
            missing += 1
            continue
        char = unicode_from(entry["unified"])
        by_cat[key].append(char)
        sn = entry.get("short_names") or []
        if sn:
            names_map[char] = sn[:4]

    total = sum(len(v) for v in by_cat.values())
    per_cat = ", ".join(f"{k}={len(v)}" for k, v in by_cat.items())
    print(f"[build] total={total} missing_svg={missing} ({per_cat})")

    out = []
    out.append("// Generated by scripts/gen_emoji_data.py - DO NOT EDIT BY HAND")
    out.append("// Source: iamcal/emoji-data (MIT)")
    out.append(".pragma library")
    out.append("")
    out.append("var CATEGORIES = [")
    for key, label, icon_cp in CATEGORY_ORDER:
        icon_char = unicode_from(icon_cp)
        emojis_json = json.dumps(by_cat[key], ensure_ascii=False)
        out.append(f"    {{ key: {json.dumps(key)}, title: {json.dumps(label)}, "
                   f"icon: {json.dumps(icon_char, ensure_ascii=False)}, emojis: {emojis_json} }},")
    out.append("];")
    out.append("")
    out.append("var NAMES = {")
    for ch, names in names_map.items():
        out.append(f"    {json.dumps(ch, ensure_ascii=False)}: {json.dumps(names)},")
    out.append("};")
    out.append("")
    out.append("function search(query) {")
    out.append("    if (!query) return [];")
    out.append("    var q = String(query).toLowerCase();")
    out.append("    var results = [];")
    out.append("    for (var ch in NAMES) {")
    out.append("        var ns = NAMES[ch];")
    out.append("        for (var i = 0; i < ns.length; i++) {")
    out.append("            if (ns[i].indexOf(q) !== -1) { results.push(ch); break; }")
    out.append("        }")
    out.append("        if (results.length >= 200) break;")
    out.append("    }")
    out.append("    return results;")
    out.append("}")
    out.append("")

    OUT_JS.write_text("\n".join(out))
    print(f"[write] {OUT_JS} ({OUT_JS.stat().st_size // 1024} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
