#!/usr/bin/env python3
"""Genera translations/harbour-rootelegram-fr.ts (francese) da -en.ts.

- Singolari: FR[src] = "traduction".
- Plurali Qt (numerus="yes"): FRN[src] = (singolare, plurale)
  (il francese usa 2 forme: 0 e 1 = singolare, >1 = plurale).
- Le stringhe non presenti nei dict restano type="unfinished" col sorgente.
"""
from pathlib import Path
import html
import re

EN = Path("translations/harbour-rootelegram-en.ts")
OUT = Path("translations/harbour-rootelegram-fr.ts")

FR = {
    "About RooTelegram": "À propos de RooTelegram",
    "A Telegram client for Sailfish OS": "Un client Telegram pour Sailfish OS",
    "Licensed under GNU GPLv3": "Sous licence GNU GPLv3",
    "Terms of Service": "Conditions d'utilisation",
    "Privacy Policy": "Politique de confidentialité",
    "Credits": "Crédits",
    "This project uses the Telegram Database Library (TDLib). Thanks for making it available under the conditions of the Boost Software License 1.0!": "Ce projet utilise la Telegram Database Library (TDLib). Merci de l'avoir rendue disponible selon les conditions de la licence Boost Software License 1.0 !",
    "Open Telegram Database Library on GitHub": "Ouvrir Telegram Database Library sur GitHub",
    "About Telegram": "À propos de Telegram",
    "This product uses the Telegram API but is not endorsed or certified by Telegram.": "Ce produit utilise l'API Telegram mais n'est ni approuvé ni certifié par Telegram.",
    "TDLib version %1": "TDLib version %1",
    "This project uses rlottie. Copyright 2020 Samsung Electronics Co., Ltd. and other contributors. Thanks for making it available under the conditions of the MIT License!": "Ce projet utilise rlottie. Copyright 2020 Samsung Electronics Co., Ltd. et autres contributeurs. Merci de l'avoir rendue disponible selon les conditions de la licence MIT !",
    "Open rlottie on GitHub": "Ouvrir rlottie sur GitHub",
    "This project uses OpenStreetMap Nominatim for reverse geocoding of location attachments. Thanks for making it available as web service!": "Ce projet utilise OpenStreetMap Nominatim pour le géocodage inversé des pièces jointes de localisation. Merci de l'avoir rendu disponible en tant que service web !",
    "Open OSM Nominatim Wiki": "Ouvrir le wiki OSM Nominatim",
    "Fernschreiber": "Fernschreiber",
    "Yottagram": "Yottagram",
    "Source code on GitHub": "Code source sur GitHub",
    "Fork by RootGPT - based on Fernschreiber by Sebastian J. Wolf and Yottagram by Michal Szczepaniak.": "Fork par RootGPT – basé sur Fernschreiber de Sebastian J. Wolf et Yottagram de Michal Szczepaniak.",
    "This project uses Twemoji (jdecked fork). Copyright the Twemoji contributors. Thanks for making it available under the conditions of the MIT License (coding) and CC-BY 4.0 (graphics)!": "Ce projet utilise Twemoji (fork jdecked). Copyright les contributeurs de Twemoji. Merci de l'avoir rendu disponible selon les conditions de la licence MIT (code) et CC-BY 4.0 (graphismes) !",
    "Open Twemoji on GitHub": "Ouvrir Twemoji sur GitHub",
    "This project bundles FFmpeg, built with libx264, to normalize videos before upload. Thanks for making it available under the conditions of the LGPL v2.1+ / GPL v2+ (libx264)!": "Ce projet inclut FFmpeg, compilé avec libx264, pour normaliser les vidéos avant l'envoi. Merci de l'avoir rendu disponible selon les conditions de la LGPL v2.1+ / GPL v2+ (libx264) !",
    "Open FFmpeg website": "Ouvrir le site de FFmpeg",
    "This project uses tgcalls and tg_owt (WebRTC) for voice and video calls. Thanks for making them available under the conditions of the GPL v2+!": "Ce projet utilise tgcalls et tg_owt (WebRTC) pour les appels vocaux et vidéo. Merci de les avoir rendus disponibles selon les conditions de la GPL v2+ !",
    "Open tgcalls on GitHub": "Ouvrir tgcalls sur GitHub",
    "For SailfishOS 5.0/5.1 compatibility this package also bundles FFmpeg's multimedia dependencies: libvpx, Opus, Ogg, Vorbis, Theora, Speex, WebP, libsharpyuv (BSD) and OpenJPEG (BSD-2). Copyright their respective contributors. The full license texts are shipped in /usr/share/harbour-rootelegram/licenses/.": "Pour la compatibilité avec SailfishOS 5.0/5.1, ce paquet inclut aussi les dépendances multimédia de FFmpeg : libvpx, Opus, Ogg, Vorbis, Theora, Speex, WebP, libsharpyuv (BSD) et OpenJPEG (BSD-2). Copyright leurs contributeurs respectifs. Les textes complets des licences se trouvent dans /usr/share/harbour-rootelegram/licenses/.",
    "Refresh": "Actualiser",
    "Add Members": "Ajouter des membres",
    "Search a contact...": "Rechercher un contact...",
    "No contacts found.": "Aucun contact trouvé.",
    "You don't have any contacts.": "Vous n'avez aucun contact.",
    "Added": "Ajouté",
    "Adding…": "Ajout…",
    "Loading contacts...": "Chargement des contacts...",
    "Member added.": "Membre ajouté.",
    "Proxy added and enabled": "Proxy ajouté et activé",
    "Add proxy": "Ajouter un proxy",
    "Add": "Ajouter",
    "Paste a proxy link (optional)": "Collez un lien de proxy (facultatif)",
    "tg://proxy?server=…  or  https://t.me/proxy?…": "tg://proxy?server=…  ou  https://t.me/proxy?…",
    "Link recognised": "Lien reconnu",
    "Type": "Type",
    "MTProto (recommended)": "MTProto (recommandé)",
    "SOCKS5 (also for calls)": "SOCKS5 (aussi pour les appels)",
    "HTTP": "HTTP",
    "Server": "Serveur",
    "Server (host or IP)": "Serveur (hôte ou IP)",
    "Port": "Port",
    "Secret": "Secret",
    "Secret (supports dd… and ee… Fake-TLS)": "Secret (prend en charge dd… et ee… Fake-TLS)",
    "Username (optional)": "Nom d'utilisateur (facultatif)",
    "Username": "Nom d'utilisateur",
    "Password (optional)": "Mot de passe (facultatif)",
    "Password": "Mot de passe",
    "HTTP only": "HTTP uniquement",
    "The proxy supports only HTTP requests (no HTTPS tunnelling).": "Le proxy ne prend en charge que les requêtes HTTP (pas de tunnel HTTPS).",
    "Add to folder": "Ajouter au dossier",
    "Added to folder: %1": "Ajouté au dossier : %1",
    "No folders": "Aucun dossier",
    "Photo": "Photo",
    "Video": "Vidéo",
    "Document": "Document",
    "Voice": "Voix",
    "GIF": "GIF",
    "Sticker": "Sticker",
    "Location": "Position",
    "Unknown chat": "Discussion inconnue",
    "Scheduled messages": "Messages programmés",
    "Loading…": "Chargement…",
    "No scheduled messages": "Aucun message programmé",
    "Long-press the send button in a chat to schedule a new message.": "Appuyez longuement sur le bouton d'envoi dans une discussion pour programmer un nouveau message.",
    "Deleting": "Suppression",
    "Reschedule": "Reprogrammer",
    "Delete": "Supprimer",
    "Voice message": "Message vocal",
    "Video message": "Message vidéo",
    "Audio": "Audio",
    "Contact": "Contact",
    "Poll": "Sondage",
    "Call": "Appel",
    "Archived chats": "Discussions archivées",
    "Unknown": "Inconnu",
    "Unarchive": "Désarchiver",
    "No archived chats": "Aucune discussion archivée",
    "Long-press a chat in the main list and choose Archive.": "Appuyez longuement sur une discussion dans la liste principale et choisissez Archiver.",
    "%1 %": "%1 %",
    "%1": "%1",
    "Blacklist": "Liste noire",
    "No blocked users.": "Aucun utilisateur bloqué.",
    "Block a user from their profile to see them here.": "Bloquez un utilisateur depuis son profil pour le voir ici.",
    "Unblocking…": "Déblocage…",
    "Unblock": "Débloquer",
    "Load more": "Charger plus",
    "Loading blocked users...": "Chargement des utilisateurs bloqués...",
    "User has been unblocked.": "L'utilisateur a été débloqué.",
    "Theme cleared": "Thème effacé",
    "Theme set: %1": "Thème défini : %1",
    "Appearance": "Apparence",
    "Pick a chat theme. The selected preset is applied to every member viewing this channel.": "Choisissez un thème de discussion. Le préréglage sélectionné s'applique à chaque membre qui consulte ce canal.",
    "Default (no theme)": "Par défaut (aucun thème)",
    "No themes available yet": "Aucun thème disponible pour l'instant",
    "Themes are pushed by Telegram after sign-in. Try again in a moment.": "Les thèmes sont fournis par Telegram après la connexion. Réessayez dans un instant.",
    "Folder created.": "Dossier créé.",
    "Unable to create folder %1": "Impossible de créer le dossier %1",
    "Unable to update folder order.": "Impossible de mettre à jour l'ordre des dossiers.",
    "Edit folders": "Modifier les dossiers",
    "All": "Tous",
    "Custom folders": "Dossiers personnalisés",
    "Create new folder": "Créer un nouveau dossier",
    "Folder name": "Nom du dossier",
    "Enter the folder name": "Saisissez le nom du dossier",
    "Create folder": "Créer le dossier",
    "Deleting folder": "Suppression du dossier",
    "Folder deleted.": "Dossier supprimé.",
    "Unable to delete folder %1": "Impossible de supprimer le dossier %1",
    "Unable to delete folder.": "Impossible de supprimer le dossier.",
    "Folder name must be at most 12 characters.": "Le nom du dossier ne doit pas dépasser 12 caractères.",
    "Unable to create folder %1: %2": "Impossible de créer le dossier %1 : %2",
    "Unable to create folder.": "Impossible de créer le dossier.",
    "Creating folder...": "Création du dossier...",
    "Retrying creation...": "Nouvelle tentative de création...",
    "Error creating folder: %1": "Erreur lors de la création du dossier : %1",
    "Internal error while creating folder.": "Erreur interne lors de la création du dossier.",
    "Leave Chat": "Quitter la discussion",
    "Join Chat": "Rejoindre la discussion",
    "Leaving chat": "Sortie de la discussion",
    "Chat Title": "Titre de la discussion",
    "Enter 1-128 characters": "Saisissez de 1 à 128 caractères",
    "There is no information text available, yet.": "Aucun texte d'information n'est disponible pour l'instant.",
    "Info": "Infos",
    "Phone Number": "Numéro de téléphone",
    "The Invite Link has been copied to the clipboard.": "Le lien d'invitation a été copié dans le presse-papiers.",
    "%1, %2": "%1, %2",
    "New Secret Chat": "Nouvelle discussion secrète",
    "Unmute Chat": "Réactiver les notifications",
    "Mute Chat": "Couper les notifications",
    "ID has been copied to the clipboard.": "L'identifiant a été copié dans le presse-papiers.",
    "Join Requests": "Demandes d'adhésion",
    "Unable to start the call.": "Impossible de démarrer l'appel.",
    "Public": "Public",
    "Private": "Privé",
    "Visible": "Visible",
    "Hidden": "Masqué",
    "Off": "Désactivé",
    "On": "Activé",
    "%1 selected": "%1 sélectionné(s)",
    "None": "Aucun",
    "No": "Non",
    "Default": "Par défaut",
    "Available": "Disponible",
    "Unavailable": "Indisponible",
    "%1 is not available yet.": "%1 n'est pas encore disponible.",
    "No invite link available yet.": "Aucun lien d'invitation disponible pour l'instant.",
    "Deleting channel": "Suppression du canal",
    "Channel Settings": "Paramètres du canal",
    "Group Settings": "Paramètres du groupe",
    "Channel Type": "Type de canal",
    "Group Type": "Type de groupe",
    "Chat History": "Historique de la discussion",
    "Only administrators can change chat history visibility.": "Seuls les administrateurs peuvent modifier la visibilité de l'historique de la discussion.",
    "Topics": "Sujets",
    "Discussion": "Discussion",
    "Direct Messages": "Messages directs",
    "Auto-Translate Messages": "Traduire automatiquement les messages",
    "Reactions": "Réactions",
    "Permissions": "Autorisations",
    "Invite Link": "Lien d'invitation",
    "Administrators": "Administrateurs",
    "Subscribers": "Abonnés",
    "Members": "Membres",
    "Removed Users": "Utilisateurs retirés",
    "Statistics": "Statistiques",
    "Statistics are unavailable for this chat.": "Les statistiques sont indisponibles pour cette discussion.",
    "Recent Actions": "Actions récentes",
    "Affiliate Programs": "Programmes d'affiliation",
    "Delete channel": "Supprimer le canal",
    "Delete and leave group": "Supprimer et quitter le groupe",
    "Reactions can only be changed in supergroups and channels.": "Les réactions ne peuvent être modifiées que dans les supergroupes et les canaux.",
    "Only administrators can change reactions.": "Seuls les administrateurs peuvent modifier les réactions.",
    "Topics enabled.": "Sujets activés.",
    "Topics disabled.": "Sujets désactivés.",
    "All reactions enabled.": "Toutes les réactions activées.",
    "Reactions disabled.": "Réactions désactivées.",
    "Basic groups are private.": "Les groupes basiques sont privés.",
    "Only administrators can change the group type.": "Seuls les administrateurs peuvent modifier le type de groupe.",
    "Only the group owner can change topics.": "Seul le propriétaire du groupe peut modifier les sujets.",
    "Chat history is now visible.": "L'historique de la discussion est maintenant visible.",
    "Chat history is now hidden.": "L'historique de la discussion est maintenant masqué.",
    "Message history can't be hidden while topics are enabled.": "L'historique des messages ne peut pas être masqué tant que les sujets sont activés.",
    "Manage Topics": "Gérer les sujets",
    "Only administrators can manage topics.": "Seuls les administrateurs peuvent gérer les sujets.",
    "Only administrators can change the group picture.": "Seuls les administrateurs peuvent modifier l'image du groupe.",
    "Uploading group picture...": "Envoi de l'image du groupe...",
    "Group picture updated.": "Image du groupe mise à jour.",
    "Channel Picture": "Image du canal",
    "Group Picture": "Image du groupe",
    "Only the channel owner can change the discussion group.": "Seul le propriétaire du canal peut modifier le groupe de discussion.",
    "Only administrators can change the appearance.": "Seuls les administrateurs peuvent modifier l'apparence.",
    "Convert to supergroup": "Convertir en supergroupe",
    "Converting to supergroup": "Conversion en supergroupe",
    "Conversion in progress…": "Conversion en cours…",
    "User has been blocked.": "L'utilisateur a été bloqué.",
    "Unblock User": "Débloquer l'utilisateur",
    "Block User": "Bloquer l'utilisateur",
    "Unable to load content.": "Impossible de charger le contenu.",
    "Loading common chats…": "Chargement des discussions communes…",
    "Loading group members…": "Chargement des membres du groupe…",
    "You": "Vous",
    "You don't have any groups in common with this user.": "Vous n'avez aucun groupe en commun avec cet utilisateur.",
    "This group is empty.": "Ce groupe est vide.",
    "Channel members are anonymous.": "Les membres du canal sont anonymes.",
    "Processing…": "Traitement…",
    "Promote to Admin": "Promouvoir administrateur",
    "Remove Admin": "Retirer les droits d'admin",
    "Removing Admin": "Retrait des droits d'admin",
    "Admin demoted to member.": "Administrateur rétrogradé en membre.",
    "Remove from group": "Retirer du groupe",
    "Removing user": "Retrait de l'utilisateur",
    "Member removed from group.": "Membre retiré du groupe.",
    "Member promoted to Admin.": "Membre promu administrateur.",
    "Groups": "Groupes",
    "Settings": "Paramètres",
    "Voice calls are not available in this build yet.": "Les appels vocaux ne sont pas encore disponibles dans cette version.",
    "Media": "Médias",
    "No media available.": "Aucun média disponible.",
    "Documents": "Documents",
    "No documents available.": "Aucun document disponible.",
    "Link": "Lien",
    "No links available.": "Aucun lien disponible.",
    "No audio available.": "Aucun audio disponible.",
    "Video call": "Appel vidéo",
    "Video calls are not available in this build yet.": "Les appels vidéo ne sont pas encore disponibles dans cette version.",
    "Search requests": "Rechercher des demandes",
    "There are no pending join requests.": "Aucune demande d'adhésion en attente.",
    "No bio": "Aucune bio",
    "Requested %1": "Demandé %1",
    "Approving…": "Approbation…",
    "Approve": "Approuver",
    "Rejecting…": "Refus…",
    "Reject": "Refuser",
    "User Info": "Infos utilisateur",
    "Group Info": "Infos du groupe",
    "Mark all messages as read": "Marquer tous les messages comme lus",
    "No message in this chat.": "Aucun message dans cette discussion.",
    "Mark chat as unread": "Marquer la discussion comme non lue",
    "Mark chat as read": "Marquer la discussion comme lue",
    "Draft": "Brouillon",
    "Unpin chat": "Désépingler la discussion",
    "Pin chat": "Épingler la discussion",
    "Unmute chat": "Réactiver les notifications",
    "Mute chat": "Couper les notifications",
    "Delete Chat": "Supprimer la discussion",
    "Deleting chat": "Suppression de la discussion",
    "Add to folder...": "Ajouter au dossier...",
    "Remove from folder: %1": "Retirer du dossier : %1",
    "Removed from folder: %1": "Retiré du dossier : %1",
    "Archive chat": "Archiver la discussion",
    "Your message": "Votre message",
    "Loading messages...": "Chargement des messages...",
    "Edit Message": "Modifier le message",
    "edited": "modifié",
    "Uploading...": "Envoi...",
    "This chat is empty.": "Cette discussion est vide.",
    "You joined the chat %1": "Vous avez rejoint la discussion %1",
    "Select Messages": "Sélectionner des messages",
    "This secret chat is not yet ready. Your chat partner needs to go online first.": "Cette discussion secrète n'est pas encore prête. Votre correspondant doit d'abord se connecter.",
    "Closing chat": "Fermeture de la discussion",
    "Close Chat": "Fermer la discussion",
    "Search in Chat": "Rechercher dans la discussion",
    "Search in chat...": "Rechercher dans la discussion...",
    "Location: Obtaining position...": "Position : obtention de la position...",
    "Location (%1/%2)": "Position (%1/%2)",
    "Copy Message to Clipboard": "Copier le message",
    "Message unpinned": "Message désépinglé",
    "Unpin Message": "Désépingler le message",
    "Pin Message": "Épingler le message",
    "Additional Options": "Options supplémentaires",
    "Unknown address": "Adresse inconnue",
    "Accuracy: %1m": "Précision : %1 m",
    "Sponsored Message": "Message sponsorisé",
    "Deleted User": "Utilisateur supprimé",
    "Double-tap on a message to choose a reaction": "Touchez deux fois un message pour choisir une réaction",
    "Forward message": "Transférer le message",
    "Delete message": "Supprimer le message",
    "Topic is closed": "Le sujet est fermé",
    "Copy Selected Text": "Copier le texte sélectionné",
    "Quote Selected Text": "Citer le texte sélectionné",
    "Premium set": "Pack Premium",
    "No premium emoji set available": "Aucun pack d'émojis Premium disponible",
    "Only the first shared file has been prepared.": "Seul le premier fichier partagé a été préparé.",
    "Unable to send this sticker.": "Impossible d'envoyer ce sticker.",
    "Telegram allows up to %1 images per album.": "Telegram autorise jusqu'à %1 images par album.",
    "Scheduled for %1": "Programmé pour %1",
    "Recent": "Récents",
    "Sticker set": "Pack de stickers",
    "No recent stickers": "Aucun sticker récent",
    "No stickers in this set": "Aucun sticker dans ce pack",
    'Do you want to delete "%1"?': "Voulez-vous supprimer « %1 » ?",
    "Do you want to delete this set?": "Voulez-vous supprimer ce pack ?",
    'Deleting "%1"': "Suppression de « %1 »",
    "Deleting set": "Suppression du pack",
    "Yes": "Oui",
    "Type your message first, then tap this button to translate it to English!": "Saisissez d'abord votre message, puis touchez ce bouton pour le traduire en anglais !",
    "RooTelegram couldn't detect the language of the text — maybe you wrote a multilingual message?": "RooTelegram n'a pas pu détecter la langue du texte — peut-être avez-vous écrit un message multilingue ?",
    "Selected text copied to clipboard": "Texte sélectionné copié dans le presse-papiers",
    "Code copied to clipboard": "Code copié dans le presse-papiers",
    "is recording a voice message": "enregistre un message vocal",
    "is recording a video message": "enregistre un message vidéo",
    "is recording a video": "enregistre une vidéo",
    "is sending a voice message": "envoie un message vocal",
    "is sending a video message": "envoie un message vidéo",
    "is sending a video": "envoie une vidéo",
    "is sending a photo": "envoie une photo",
    "is sending a file": "envoie un fichier",
    "is choosing a sticker": "choisit un sticker",
    "is choosing a location": "choisit une position",
    "is choosing a contact": "choisit un contact",
    "is typing…": "écrit…",
    "Unknown user": "Utilisateur inconnu",
    "edited a message": "a modifié un message",
    "deleted a message": "a supprimé un message",
    "pinned a message": "a épinglé un message",
    "joined the chat": "a rejoint la discussion",
    "joined via invite link": "a rejoint via un lien d'invitation",
    "left the chat": "a quitté la discussion",
    "invited a member": "a invité un membre",
    "updated administrator rights": "a mis à jour les droits d'administrateur",
    "updated member permissions": "a mis à jour les autorisations du membre",
    "changed the chat title": "a modifié le titre de la discussion",
    "changed the description": "a modifié la description",
    "changed the public username": "a modifié le nom d'utilisateur public",
    "changed the photo": "a modifié la photo",
    "changed invite link permissions": "a modifié les autorisations du lien d'invitation",
    "changed message signing": "a modifié la signature des messages",
    "changed sticker set": "a modifié le pack de stickers",
    "changed linked chat": "a modifié la discussion liée",
    "changed slow mode": "a modifié le mode lent",
    "started a video chat": "a démarré un salon vidéo",
    "ended the video chat": "a terminé le salon vidéo",
    "changed video chat permissions": "a modifié les autorisations du salon vidéo",
    "edited an invite link": "a modifié un lien d'invitation",
    "revoked an invite link": "a révoqué un lien d'invitation",
    "deleted an invite link": "a supprimé un lien d'invitation",
    "performed an action": "a effectué une action",
    "Description cleared": "Description effacée",
    "Username removed": "Nom d'utilisateur supprimé",
    "Slow mode: %1s": "Mode lent : %1 s",
    "Slow mode disabled": "Mode lent désactivé",
    "Linked chat removed": "Discussion liée supprimée",
    "No recent actions found.": "Aucune action récente trouvée.",
    "Select Chat": "Sélectionner une discussion",
    "You don't have any chats yet.": "Vous n'avez encore aucune discussion.",
    "Search in contacts...": "Rechercher dans les contacts...",
    "Send contact": "Envoyer le contact",
    "Search contact": "Rechercher un contact",
    "No contacts with a phone number": "Aucun contact avec un numéro de téléphone",
    "Could not synchronize your contacts with Telegram.": "Impossible de synchroniser vos contacts avec Telegram.",
    "in": "dans",
    "Waiting for network...": "En attente du réseau...",
    "Connecting to network...": "Connexion au réseau...",
    "Connecting to proxy...": "Connexion au proxy...",
    "Connected": "Connecté",
    "Updating content...": "Mise à jour du contenu...",
    "New Channel": "Nouveau canal",
    "New Group": "Nouveau groupe",
    "Cancel": "Annuler",
    "Delete for everyone": "Supprimer pour tout le monde",
    "Delete for me": "Supprimer pour moi",
    "Group Member Permissions": "Autorisations des membres du groupe",
    "Send Messages": "Envoyer des messages",
    "Send Media Messages": "Envoyer des médias",
    "Send Other Messages": "Envoyer d'autres messages",
    "Add Web Page Previews": "Ajouter des aperçus de pages web",
    "Change Chat Info": "Modifier les infos de la discussion",
    "Invite Users": "Inviter des utilisateurs",
    "Pin Messages": "Épingler des messages",
    "New Members": "Nouveaux membres",
    "New members can see older messages": "Les nouveaux membres voient les anciens messages",
    "Send Polls": "Envoyer des sondages",
    "Create Topics": "Créer des sujets",
    "Group permissions updated.": "Autorisations du groupe mises à jour.",
    "Some permission changes were rejected by Telegram.": "Certaines modifications d'autorisations ont été refusées par Telegram.",
    "Slow Mode": "Mode lent",
    "Set how long every chat member has to wait between Messages": "Définissez le temps d'attente entre les messages pour chaque membre de la discussion",
    "Search emoji": "Rechercher un émoji",
    "No results": "Aucun résultat",
    "No emoji": "Aucun émoji",
    "Loading topics...": "Chargement des sujets...",
    "No topics found": "Aucun sujet trouvé",
    "This group has no topics yet.": "Ce groupe n'a pas encore de sujets.",
    "Topic name must be between 1 and 128 characters.": "Le nom du sujet doit comporter entre 1 et 128 caractères.",
    "Create Topic": "Créer un sujet",
    "Disable Topics": "Désactiver les sujets",
    "Topic created.": "Sujet créé.",
    "Topic renamed.": "Sujet renommé.",
    "Topic deleted.": "Sujet supprimé.",
    "Topic closed.": "Sujet fermé.",
    "Topic reopened.": "Sujet rouvert.",
    "Topic name": "Nom du sujet",
    "New topic name": "Nouveau nom du sujet",
    "Enter topic name": "Saisissez le nom du sujet",
    "Saving…": "Enregistrement…",
    "Create": "Créer",
    "Rename": "Renommer",
    "Rename topic": "Renommer le sujet",
    "Reopen topic": "Rouvrir le sujet",
    "Close topic": "Fermer le sujet",
    "Delete topic": "Supprimer le sujet",
    "Deleting topic": "Suppression du sujet",
    "Closed": "Fermé",
    "You don't have permission to create topics.": "Vous n'avez pas l'autorisation de créer des sujets.",
    "Saved %1": "Enregistré %1",
    "Save failed.": "Échec de l'enregistrement.",
    "Username must be 5-32 characters.": "Le nom d'utilisateur doit comporter de 5 à 32 caractères.",
    "Username can only use letters, numbers and underscores.": "Le nom d'utilisateur ne peut contenir que des lettres, des chiffres et des tirets bas.",
    "Save": "Enregistrer",
    "Public Channel": "Canal public",
    "Public Group": "Groupe public",
    "Public chats can be found via username.": "Les discussions publiques peuvent être trouvées via le nom d'utilisateur.",
    "Private chats can only be joined through invite links.": "Les discussions privées ne peuvent être rejointes que via des liens d'invitation.",
    "Set public username": "Définir un nom d'utilisateur public",
    "Use 5-32 letters, numbers or underscores.": "Utilisez de 5 à 32 lettres, chiffres ou tirets bas.",
    "Approve new members": "Approuver les nouveaux membres",
    "New members must be approved by an administrator.": "Les nouveaux membres doivent être approuvés par un administrateur.",
    "Forbid content saving": "Interdire l'enregistrement du contenu",
    "Prevents forwarding, copying and saving of chat contents.": "Empêche le transfert, la copie et l'enregistrement du contenu de la discussion.",
    "Options saved": "Options enregistrées",
    "Download Picture": "Télécharger l'image",
    "Download of %1 successful.": "Téléchargement de %1 réussi.",
    "Download failed.": "Échec du téléchargement.",
    "This message was deleted": "Ce message a été supprimé",
    "OK": "OK",
    "Welcome to RooTelegram!": "Bienvenue dans RooTelegram !",
    "Please enter your phone number to continue.": "Saisissez votre numéro de téléphone pour continuer.",
    "Continue": "Continuer",
    "Please enter the code that you received:": "Saisissez le code que vous avez reçu :",
    "Loading...": "Chargement...",
    "Unable to authenticate you with the entered code.": "Impossible de vous authentifier avec le code saisi.",
    "Enter code again": "Saisir à nouveau le code",
    "Restart authentication": "Redémarrer l'authentification",
    "Please enter your password:": "Saisissez votre mot de passe :",
    "User Registration": "Inscription de l'utilisateur",
    "Enter your First Name": "Saisissez votre prénom",
    "Enter your Last Name": "Saisissez votre nom",
    "Register User": "Inscrire l'utilisateur",
    "Use the international format, e.g. %1": "Utilisez le format international, p. ex. %1",
    "Transcribe": "Transcrire",
    "Play/Pause": "Lecture/pause",
    "Contact saved to address book": "Contact enregistré dans le carnet d'adresses",
    "Could not save the contact": "Impossible d'enregistrer le contact",
    "Message": "Message",
    "Add to contacts": "Ajouter aux contacts",
    "When the recipient comes online": "Quand le destinataire sera en ligne",
    "Message info": "Infos du message",
    "Sent": "Envoyé",
    "Edited": "Modifié",
    "Scheduled": "Programmé",
    "Sender": "Expéditeur",
    "Author signature": "Signature de l'auteur",
    "Via bot": "Via le bot",
    "Forwarded from": "Transféré de",
    "Original date": "Date d'origine",
    "Views": "Vues",
    "Forwards": "Transferts",
    "Message ID": "ID du message",
    "Album ID": "ID de l'album",
    "Reply to Message": "Répondre au message",
    "Forwarded Message": "Message transféré",
    "Select Message": "Sélectionner le message",
    "More Options...": "Plus d'options...",
    "Message deleted": "Message supprimé",
    "Delete all messages from %1": "Supprimer tous les messages de %1",
    "Delete all messages from this user": "Supprimer tous les messages de cet utilisateur",
    "Ban %1": "Bannir %1",
    "Ban user": "Bannir l'utilisateur",
    "Report as spam": "Signaler comme spam",
    "Deletion of messages started": "Suppression des messages démarrée",
    "User banned": "Utilisateur banni",
    "Report submitted": "Signalement envoyé",
    "Delete album": "Supprimer l'album",
    "Hide spoiler": "Masquer le spoiler",
    "Reveal spoiler": "Révéler le spoiler",
    "In reply to a story": "En réponse à une story",
    "Translate message": "Traduire le message",
    "Someone": "Quelqu'un",
    "This message was forwarded. Original author: %1": "Ce message a été transféré. Auteur d'origine : %1",
    "Close Poll": "Fermer le sondage",
    "Reset Answer": "Réinitialiser la réponse",
    "Final Result:": "Résultat final :",
    "Multiple Answers are allowed.": "Plusieurs réponses sont autorisées.",
    "via %1": "via %1",
    "Seen by": "Vu par",
    "No views": "Aucune vue",
    "Voice Note": "Note vocale",
    "Your Contacts": "Vos contacts",
    "Private Chat": "Discussion privée",
    "Secret Chat": "Discussion secrète",
    "End-to-end-encrypted, accessible on this device only": "Chiffré de bout en bout, accessible uniquement sur cet appareil",
    "Transport-encrypted, uses Telegram Cloud, sharable across devices": "Chiffré pour le transport, utilise le cloud Telegram, partageable entre appareils",
    "Synchronize Contacts with Telegram": "Synchroniser les contacts avec Telegram",
    "Contacts successfully synchronized with Telegram.": "Contacts synchronisés avec Telegram avec succès.",
    "posted a new story": "a publié une nouvelle story",
    "reacted to your message": "a réagi à votre message",
    "reacted %1 to your message": "a réagi %1 à votre message",
    "My chats": "Mes discussions",
    "Global results": "Résultats globaux",
    "User": "Utilisateur",
    "Group": "Groupe",
    "Channel": "Canal",
    "No public users, groups or channels found.": "Aucun utilisateur, groupe ou canal public trouvé.",
    "Loading chat list...": "Chargement de la liste des discussions...",
    "New Chat": "Nouvelle discussion",
    "Tap on the title bar to filter your chats": "Touchez la barre de titre pour filtrer vos discussions",
    "No matching chats found.": "Aucune discussion correspondante trouvée.",
    "You can search public chats or create a new chat via the pull-down menu.": "Vous pouvez rechercher des discussions publiques ou créer une nouvelle discussion via le menu déroulant.",
    "Logging out": "Déconnexion",
    "Unable to open link.": "Impossible d'ouvrir le lien.",
    "All chats marked as read.": "Toutes les discussions marquées comme lues.",
    "Mark all as read": "Tout marquer comme lu",
    "Search chat...": "Rechercher une discussion...",
    "Stories": "Stories",
    "Reorder Pinned Chats": "Réorganiser les discussions épinglées",
    "Debug": "Débogage",
    "Search...": "Rechercher...",
    "Pin": "Épingler",
    "Pin message": "Épingler le message",
    "Choose where to pin this message in the chat with %1.": "Choisissez où épingler ce message dans la discussion avec %1.",
    "Choose where to pin this message.": "Choisissez où épingler ce message.",
    "Pin for": "Épingler pour",
    "Both users": "Les deux utilisateurs",
    "Only me": "Moi uniquement",
    "Pinned Message": "Message épinglé",
    "All answers have to contain 1-100 characters.": "Chaque réponse doit contenir de 1 à 100 caractères.",
    "To send a quiz, you have to specify the right answer.": "Pour envoyer un quiz, vous devez indiquer la bonne réponse.",
    "You have to enter a question.": "Vous devez saisir une question.",
    "The question has to be shorter than 256 characters.": "La question doit comporter moins de 256 caractères.",
    "A poll requires 2-10 answers.": "Un sondage nécessite de 2 à 10 réponses.",
    "Create a Poll": "Créer un sondage",
    "in %1": "dans %1",
    "Enter your question here": "Saisissez votre question ici",
    "Answers": "Réponses",
    "Enter an answer here": "Saisissez une réponse ici",
    "Add an answer": "Ajouter une réponse",
    "Poll Options": "Options du sondage",
    "Anonymous answers": "Réponses anonymes",
    "Multiple answers allowed": "Plusieurs réponses autorisées",
    "Quiz Mode": "Mode quiz",
    "Quizzes have one correct answer. Participants can't revoke their responses.": "Les quiz ont une seule bonne réponse. Les participants ne peuvent pas annuler leurs réponses.",
    "Enter an optional explanation": "Saisissez une explication facultative",
    "Shown when the user selects a wrong answer.": "Affichée lorsque l'utilisateur sélectionne une mauvaise réponse.",
    "An explanation can be up to 200 characters long.": "Une explication peut comporter jusqu'à 200 caractères.",
    "Quiz Results": "Résultats du quiz",
    "Poll Results": "Résultats du sondage",
    "Question": "Question",
    "Results": "Résultats",
    "Chosen by:": "Choisi par :",
    "Promote": "Promouvoir",
    "Promote %1 to Admin": "Promouvoir %1 administrateur",
    "Custom title (max 16 characters)": "Titre personnalisé (max. 16 caractères)",
    "e.g. Moderator": "p. ex. Modérateur",
    "Privileges": "Privilèges",
    "Manage chat": "Gérer la discussion",
    "View admin log and chat statistics.": "Voir le journal d'administration et les statistiques de la discussion.",
    "Change group info": "Modifier les infos du groupe",
    "Title, photo and description.": "Titre, photo et description.",
    "Delete messages": "Supprimer des messages",
    "Ban users": "Bannir des utilisateurs",
    "Invite users": "Inviter des utilisateurs",
    "Pin messages": "Épingler des messages",
    "Manage topics": "Gérer les sujets",
    "Manage video chats": "Gérer les salons vidéo",
    "Post messages": "Publier des messages",
    "Edit messages of others": "Modifier les messages des autres",
    "Post stories": "Publier des stories",
    "Edit stories": "Modifier des stories",
    "Delete stories": "Supprimer des stories",
    "Add new admins": "Ajouter de nouveaux administrateurs",
    "With the rights this user already has.": "Avec les droits que cet utilisateur possède déjà.",
    "Anonymous": "Anonyme",
    "Send messages as the group itself.": "Envoyer des messages au nom du groupe lui-même.",
    "MTProto": "MTProto",
    "SOCKS5": "SOCKS5",
    "%1 ms": "%1 ms",
    "Proxy": "Proxy",
    "Disable proxy (direct connection)": "Désactiver le proxy (connexion directe)",
    "Proxy disabled": "Proxy désactivé",
    "No proxies": "Aucun proxy",
    "Pull down to add a proxy, or paste a tg://proxy link.": "Tirez vers le bas pour ajouter un proxy, ou collez un lien tg://proxy.",
    "Disable": "Désactiver",
    "Enable": "Activer",
    "Test connection": "Tester la connexion",
    "Remove": "Retirer",
    "Removing proxy": "Retrait du proxy",
    "Unable to update pinned chat order.": "Impossible de mettre à jour l'ordre des discussions épinglées.",
    "No pinned chats.": "Aucune discussion épinglée.",
    "Pin a chat from home to reorder it here.": "Épinglez une discussion depuis l'accueil pour la réordonner ici.",
    "sent a picture": "a envoyé une image",
    "sent a video": "a envoyé une vidéo",
    "sent an animation": "a envoyé une animation",
    "sent a voice note": "a envoyé une note vocale",
    "sent a document": "a envoyé un document",
    "sent a location": "a envoyé une position",
    "have registered with Telegram": "se sont inscrits sur Telegram",
    "has registered with Telegram": "s'est inscrit sur Telegram",
    "joined this chat": "a rejoint cette discussion",
    "were added to this chat": "ont été ajoutés à cette discussion",
    "was added to this chat": "a été ajouté à cette discussion",
    "left this chat": "a quitté cette discussion",
    "sent a venue": "a envoyé un lieu",
    "sent a poll": "a envoyé un sondage",
    "sent a quiz": "a envoyé un quiz",
    "created this group": "a créé ce groupe",
    "changed the chat photo": "a modifié la photo de la discussion",
    "deleted the chat photo": "a supprimé la photo de la discussion",
    "changed the secret chat TTL setting": "a modifié le réglage TTL de la discussion secrète",
    "upgraded this group to a supergroup": "a transformé ce groupe en supergroupe",
    "changed the pinned message": "a modifié le message épinglé",
    "created a screenshot in this chat": "a fait une capture d'écran dans cette discussion",
    "sent an unsupported message": "a envoyé un message non pris en charge",
    "sent an unsupported message: %1": "a envoyé un message non pris en charge : %1",
    "sent a self-destructing photo that is expired": "a envoyé une photo éphémère qui a expiré",
    "sent a self-destructing video that is expired": "a envoyé une vidéo éphémère qui a expiré",
    "sent an audio": "a envoyé un audio",
    "has added %1 to the chat": "a ajouté %1 à la discussion",
    "has removed %1 from the chat": "a retiré %1 de la discussion",
    "have added %1 to the chat": "ont ajouté %1 à la discussion",
    "have removed %1 from the chat": "ont retiré %1 de la discussion",
    "sent a game": "a envoyé un jeu",
    "sent a video note": "a envoyé une note vidéo",
    "cancelled a call": "a annulé un appel",
    "missed a call": "a manqué un appel",
    "started a call": "a démarré un appel",
    "sent a contact": "a envoyé un contact",
    "scheduled a video chat": "a programmé un salon vidéo",
    "invited participants to the video chat": "a invité des participants au salon vidéo",
    "changed the chat theme": "a modifié le thème de la discussion",
    "changed the chat background": "a modifié le fond de la discussion",
    "Schedule": "Programmer",
    "Message will be sent at the selected time.": "Le message sera envoyé à l'heure sélectionnée.",
    "Pick a time in the future.": "Choisissez une heure dans le futur.",
    "Date": "Date",
    "Time": "Heure",
    "Already scheduled in this chat": "Déjà programmé dans cette discussion",
    "No other scheduled messages in this chat.": "Aucun autre message programmé dans cette discussion.",
    "Deleting scheduled message": "Suppression du message programmé",
    "No chats found.": "Aucune discussion trouvée.",
    "Searching chats...": "Recherche de discussions...",
    "Search Chats": "Rechercher des discussions",
    "Search a chat...": "Rechercher une discussion...",
    "Enter your query to start searching (at least 5 characters needed)": "Saisissez votre requête pour lancer la recherche (au moins 5 caractères requis)",
    "Discussion group updated": "Groupe de discussion mis à jour",
    "Discussion group removed": "Groupe de discussion supprimé",
    "Error: %1": "Erreur : %1",
    "Remove discussion group": "Supprimer le groupe de discussion",
    "Choose a group that will host discussion of channel posts.": "Choisissez un groupe qui hébergera les discussions sur les publications du canal.",
    "No suitable groups": "Aucun groupe approprié",
    "Create a public supergroup or convert an existing one to use as discussion.": "Créez une supergroupe publique ou convertissez-en une existante pour servir de discussion.",
    "Reload": "Recharger",
    "Show stickers as emojis": "Afficher les stickers comme émojis",
    "Only display emojis instead of the actual stickers": "Afficher uniquement les émojis au lieu des stickers réels",
    "Show stickers as images": "Afficher les stickers comme images",
    "Show background for stickers and align them centrally like images": "Afficher un fond pour les stickers et les centrer comme des images",
    "Animate stickers": "Animer les stickers",
    "Cyberpunk look (requires a dark and orange theme for the perfect experience)": "Style cyberpunk (nécessite un thème sombre et orange pour une expérience parfaite)",
    "Silica base theme (lighter, also good on light themes)": "Thème de base Silica (plus léger, aussi adapté aux thèmes clairs)",
    "Choose RooTelegram's theme": "Choisir le thème de RooTelegram",
    "Silica (base theme)": "Silica (thème de base)",
    "Neon (cyberpunk)": "Néon (cyberpunk)",
    "Behavior": "Comportement",
    "Send message by enter": "Envoyer le message avec Entrée",
    "Send your message by pressing the enter key": "Envoyer votre message en appuyant sur la touche Entrée",
    "Focus text input on chat open": "Activer le champ de texte à l'ouverture de la discussion",
    "Focus the text input area when entering a chat": "Activer la zone de saisie de texte en entrant dans une discussion",
    "Focus text input area after send": "Activer la zone de saisie après l'envoi",
    "Focus the text input area after sending a message": "Activer la zone de saisie de texte après l'envoi d'un message",
    "Delay before marking messages as read": "Délai avant de marquer les messages comme lus",
    "RooTelegram will wait a bit before messages are marked as read": "RooTelegram attendra un peu avant que les messages soient marqués comme lus",
    "Open-with menu integration": "Intégration au menu « Ouvrir avec »",
    "Integrate RooTelegram into open-with menu of Sailfish OS": "Intégrer RooTelegram au menu « Ouvrir avec » de Sailfish OS",
    "Notification feedback": "Retour des notifications",
    "Use non-graphical feedback (sound, vibration) for notifications": "Utiliser un retour non graphique (son, vibration) pour les notifications",
    "All events": "Tous les événements",
    "Only new events": "Uniquement les nouveaux événements",
    "Notification turns on the display": "La notification allume l'écran",
    "Enable notification sounds": "Activer les sons de notification",
    "When sounds are enabled, RooTelegram will use the current Sailfish OS notification sound for chats, which can be configured in the system settings.": "Lorsque les sons sont activés, RooTelegram utilisera le son de notification actuel de Sailfish OS pour les discussions, configurable dans les paramètres système.",
    "Always append message preview to notifications": "Toujours ajouter l'aperçu du message aux notifications",
    "In addition to showing the number of unread messages, the latest message will also be appended to notifications.": "En plus d'afficher le nombre de messages non lus, le dernier message sera également ajouté aux notifications.",
    "Highlight unread messages": "Mettre en évidence les messages non lus",
    "Highlight Conversations with unread messages": "Mettre en évidence les conversations avec des messages non lus",
    "Hide content in notifications": "Masquer le contenu dans les notifications",
    "Go to quoted message": "Aller au message cité",
    "When tapping a quoted message, open it in chat instead of showing it in an overlay.": "En touchant un message cité, l'ouvrir dans la discussion au lieu de l'afficher en surimpression.",
    "Cover: only private chats in unread count": "Couverture : seulement les discussions privées dans le compteur de non-lus",
    "Exclude groups and channels from the unread message and chat counts shown on the cover preview": "Exclure les groupes et canaux des compteurs de messages non lus et de discussions affichés sur l'aperçu de couverture",
    "Disable video preloading": "Désactiver le préchargement des vidéos",
    "Disables automatic video preloading to reduce RAM/GPU and mobile data usage. Photos are still downloaded automatically.": "Désactive le préchargement automatique des vidéos pour réduire l'utilisation de la RAM/du GPU et des données mobiles. Les photos sont toujours téléchargées automatiquement.",
    "Notifications": "Notifications",
    "Show desktop notifications for new messages. The app always stays in background; this toggle controls only notification publishing.": "Afficher les notifications pour les nouveaux messages. L'application reste toujours en arrière-plan ; ce réglage ne contrôle que la publication des notifications.",
    "Notify when a contact posts a new story.": "Notifier lorsqu'un contact publie une nouvelle story.",
    "Notify when someone reacts to one of your messages.": "Notifier lorsque quelqu'un réagit à l'un de vos messages.",
    "Connection": "Connexion",
    "Proxies route your Telegram traffic through another server to bypass censorship. MTProto proxies (especially with Fake-TLS) are the most resistant to blocking. SOCKS5 proxies also cover voice and video calls.": "Les proxys acheminent votre trafic Telegram via un autre serveur pour contourner la censure. Les proxys MTProto (surtout avec Fake-TLS) sont les plus résistants au blocage. Les proxys SOCKS5 couvrent aussi les appels vocaux et vidéo.",
    "Add, enable and test connection proxies.": "Ajoutez, activez et testez les proxys de connexion.",
    "Privacy": "Confidentialité",
    "Allow adding me to groups and channels": "Autoriser à m'ajouter aux groupes et canaux",
    "Privacy setting for managing who can add you to groups and channels.": "Réglage de confidentialité pour gérer qui peut vous ajouter aux groupes et canaux.",
    "Your contacts only": "Vos contacts uniquement",
    "Allow finding by phone number": "Autoriser à être trouvé par numéro de téléphone",
    "Privacy setting for managing whether you can be found by your phone number.": "Réglage de confidentialité pour gérer si vous pouvez être trouvé par votre numéro de téléphone.",
    "Show link in forwarded messages": "Afficher le lien dans les messages transférés",
    "Privacy setting for managing whether a link to your account is included in forwarded messages.": "Réglage de confidentialité pour gérer si un lien vers votre compte est inclus dans les messages transférés.",
    "Show phone number": "Afficher le numéro de téléphone",
    "Privacy setting for managing whether your phone number is visible.": "Réglage de confidentialité pour gérer si votre numéro de téléphone est visible.",
    "Show profile photo": "Afficher la photo de profil",
    "Privacy setting for managing whether your profile photo is visible.": "Réglage de confidentialité pour gérer si votre photo de profil est visible.",
    "Show status": "Afficher le statut",
    "Privacy setting for managing whether your online status is visible.": "Réglage de confidentialité pour gérer si votre statut en ligne est visible.",
    "Allow sending Location to inline bots": "Autoriser l'envoi de la position aux bots en ligne",
    "Some inline bots request location data when using them": "Certains bots en ligne demandent des données de localisation lors de leur utilisation",
    "Blocklist": "Liste de blocage",
    "View": "Afficher",
    "Show the list of Telegram users you have blocked.": "Afficher la liste des utilisateurs Telegram que vous avez bloqués.",
    "Privacy setting for managing who can call you.": "Réglage de confidentialité pour gérer qui peut vous appeler.",
    "Everybody": "Tout le monde",
    "Nobody": "Personne",
    "Allow calls": "Autoriser les appels",
    "This is a Premium-only feature.": "Cette fonctionnalité est réservée à Premium.",
    "Only selected": "Sélectionnés uniquement",
    "Privacy updated": "Confidentialité mise à jour",
    "Voice and video messages": "Messages vocaux et vidéo",
    "Who can send you voice messages and video notes (round videos). Premium feature.": "Qui peut vous envoyer des messages vocaux et des notes vidéo (vidéos rondes). Fonctionnalité Premium.",
    "Choose who can send you voice messages and video notes.": "Choisissez qui peut vous envoyer des messages vocaux et des notes vidéo.",
    "Choose who cannot send you voice messages and video notes.": "Choisissez qui ne peut pas vous envoyer de messages vocaux et de notes vidéo.",
    "Everybody except": "Tout le monde sauf",
    "Sessions": "Sessions",
    "Session was terminated": "La session a été fermée",
    "Terminating session": "Fermeture de la session",
    "Terminate Session": "Fermer la session",
    "This app": "Cette application",
    "Active since: %1, last online: %2": "Active depuis : %1, dernière connexion : %2",
    "1 week": "1 semaine",
    "1 month": "1 mois",
    "3 months": "3 mois",
    "6 months": "6 mois",
    "1 year": "1 an",
    "Session Timeout": "Expiration de la session",
    "Inactive sessions will be terminated after this timeframe": "Les sessions inactives seront fermées après ce délai",
    "Storage": "Stockage",
    "Enable online-only mode": "Activer le mode « en ligne uniquement »",
    "Disables offline caching. Certain features may be limited or missing in this mode. Changes require a restart of RooTelegram to take effect.": "Désactive la mise en cache hors ligne. Certaines fonctionnalités peuvent être limitées ou absentes dans ce mode. Les modifications nécessitent un redémarrage de RooTelegram.",
    "Enable storage optimizer": "Activer l'optimiseur de stockage",
    "User Profile": "Profil utilisateur",
    "First Name": "Prénom",
    "Enter 1-64 characters": "Saisissez de 1 à 64 caractères",
    "Last Name": "Nom",
    "Enter 0-64 characters": "Saisissez de 0 à 64 caractères",
    "Profile Pictures": "Photos de profil",
    "Add Picture": "Ajouter une photo",
    "Delete Picture": "Supprimer la photo",
    "Deleting profile picture": "Suppression de la photo de profil",
    "Log Out": "Se déconnecter",
    "Logged out": "Déconnecté",
    "Phone number: +%1": "Numéro de téléphone : +%1",
    "Go to Channel": "Aller au canal",
    "Go to Message": "Aller au message",
    "Start Bot": "Démarrer le bot",
    "Sticker set successfully removed!": "Pack de stickers supprimé avec succès !",
    "Sticker set successfully installed!": "Pack de stickers installé avec succès !",
    "Main": "Principal",
    "No stories from your contacts": "Aucune story de vos contacts",
    "Pull down to refresh": "Tirez vers le bas pour actualiser",
    "My Archive": "Mes archives",
    "You have no archived stories": "Vous n'avez aucune story archivée",
    "(no caption)": "(sans légende)",
    "New story": "Nouvelle story",
    "Delete story": "Supprimer la story",
    "Blacklist is empty": "La liste noire est vide",
    "Remove from blacklist": "Retirer de la liste noire",
    "Add to blacklist": "Ajouter à la liste noire",
    "Added to blacklist": "Ajouté à la liste noire",
    "Removed from blacklist": "Retiré de la liste noire",
    "My Profile": "Mon profil",
    "You have no stories on your profile": "Vous n'avez aucune story sur votre profil",
    "Archive": "Archiver",
    "Profile": "Profil",
    "Story": "Story",
    "This story type is not supported yet": "Ce type de story n'est pas encore pris en charge",
    "Deleting story": "Suppression de la story",
    "Could not set reaction.": "Impossible de définir la réaction.",
    "Story not available": "Story indisponible",
    "Audience": "Audience",
    "Done": "Terminé",
    "No contacts or private chats.": "Aucun contact ou discussion privée.",
    "Custom audience": "Audience personnalisée",
    "Publish": "Publier",
    "Tap to change": "Touchez pour modifier",
    "Caption": "Légende",
    "Add a caption (optional)": "Ajouter une légende (facultatif)",
    "Reading video…": "Lecture de la vidéo…",
    "Video too long: %1 (max %2)": "Vidéo trop longue : %1 (max. %2)",
    "Duration: %1": "Durée : %1",
    "Cannot determine your account.": "Impossible de déterminer votre compte.",
    "Posting story…": "Publication de la story…",
    "Video conversion failed.": "Échec de la conversion de la vidéo.",
    "Story posted": "Story publiée",
    "Could not post story.": "Impossible de publier la story.",
    "Telegram stories are vertical (9:16). Your landscape video is being adapted before publishing.": "Les stories Telegram sont verticales (9:16). Votre vidéo horizontale est adaptée avant la publication.",
    "Converting video": "Conversion de la vidéo",
    "Uploading video": "Envoi de la vidéo",
    "Everyone": "Tout le monde",
    "Selected contacts": "Contacts sélectionnés",
    "Choose contacts": "Choisir des contacts",
    "Allow screenshots": "Autoriser les captures d'écran",
    "If off, the story is marked as protected: official clients block screenshots and forwarding.": "Si désactivé, la story est marquée comme protégée : les clients officiels bloquent les captures d'écran et le transfert.",
    "Post to my profile": "Publier sur mon profil",
    "Keep the story visible on your profile after the 24h expiration.": "Garder la story visible sur votre profil après l'expiration de 24 h.",
    "Custom audience (%1)": "Audience personnalisée (%1)",
    "Reply sent": "Réponse envoyée",
    "Send": "Envoyer",
    "Reply to %1": "Répondre à %1",
    "Reply to story": "Répondre à la story",
    "Reply": "Répondre",
    "Write a reply…": "Écrivez une réponse…",
    "Viewers": "Spectateurs",
    "Telegram user": "Utilisateur Telegram",
    "Forwarded": "Transféré",
    "Reposted": "Republié",
    "No viewers yet": "Aucun spectateur pour l'instant",
    "Banned until %1": "Banni jusqu'au %1",
    "Banned": "Banni",
    "Unable to load members for this chat.": "Impossible de charger les membres de cette discussion.",
    "There are no removed users.": "Aucun utilisateur retiré.",
    "No administrators found.": "Aucun administrateur trouvé.",
    "Joined %1": "A rejoint %1",
    "Unbanning…": "Débannissement…",
    "Unban": "Débannir",
    "User has been unbanned.": "L'utilisateur a été débanni.",
    "Apply now": "Appliquer maintenant",
    "Neon theme": "Thème Néon",
    "Silica theme": "Thème Silica",
    "Cyberpunk look": "Style cyberpunk",
    "Base theme": "Thème de base",
    "Circuit background, neon glow on menus, buttons and titles, rounded avatars and glass cards. Heavier: requires a dark and orange theme for the perfect experience.": "Fond à circuits, lueur néon sur les menus, boutons et titres, avatars arrondis et cartes en verre. Plus lourd : nécessite un thème sombre et orange pour une expérience parfaite.",
    "Native flat menus, square avatars, no custom background, standard Silica colors. Lighter and clearly readable also on light system themes.": "Menus plats natifs, avatars carrés, aucun fond personnalisé, couleurs Silica standard. Plus léger et bien lisible aussi avec les thèmes système clairs.",
    "Apply this theme now?": "Appliquer ce thème maintenant ?",
    "Copy video to gallery": "Copier la vidéo dans la galerie",
    "A video conversion is already in progress.": "Une conversion vidéo est déjà en cours.",
    "Video converter not available.": "Convertisseur vidéo indisponible.",
    "Source video not found.": "Vidéo source introuvable.",
    "Could not start the video converter.": "Impossible de démarrer le convertisseur vidéo.",
    "Record a Voice Note": "Enregistrer une note vocale",
    "Press the button to start recording": "Appuyez sur le bouton pour démarrer l'enregistrement",
    "Starting": "Démarrage",
    "Recording": "Enregistrement",
    "Stopping": "Arrêt",
    "Use recording": "Utiliser l'enregistrement",
    "Voice Note (%1)": "Note vocale (%1)",
    "Ready": "Prêt",
    "Preview not supported for this link...": "Aperçu non pris en charge pour ce lien...",
    "Continua": "Continuer",
    "Novità": "Nouveautés",
    "Video: %1": "Vidéo : %1",
    "Picture: %1": "Image : %1",
    "Audio: %1": "Audio : %1",
    "Voice Note: %1": "Note vocale : %1",
    "Animation: %1": "Animation : %1",
    "Document: %1": "Document : %1",
    "%1M": "%1 M",
    "%1K": "%1 k",
    "was never online": "n'a jamais été en ligne",
    "last online: last month": "dernière connexion : le mois dernier",
    "last online: last week": "dernière connexion : la semaine dernière",
    "last online: %1": "dernière connexion : %1",
    "online": "en ligne",
    "was recently online": "était récemment en ligne",
    "Admin": "Admin",
    "Creator": "Créateur",
    "Restricted": "Restreint",
    "changed the chat title to %1": "a changé le titre de la discussion en %1",
    "sent an anonymous quiz": "a envoyé un quiz anonyme",
    "sent an anonymous poll": "a envoyé un sondage anonyme",
    "Anonymous Quiz": "Quiz anonyme",
    "Quiz": "Quiz",
    "Anonymous Poll": "Sondage anonyme",
    "Unable to find user %1": "Impossible de trouver l'utilisateur %1",
    "You are already a member of this chat.": "Vous êtes déjà membre de cette discussion.",
    "Closed!": "Fermé !",
    "Pending acknowledgement": "En attente de confirmation",
    "created topic: %1": "a créé le sujet : %1",
    "renamed topic to: %1": "a renommé le sujet en : %1",
    "edited topic icon": "a modifié l'icône du sujet",
    "closed topic": "a fermé le sujet",
    "reopened topic": "a rouvert le sujet",
    "edited topic": "a modifié le sujet",
    "hid topic": "a masqué le sujet",
    "unhid topic": "a affiché le sujet",
    "Send shared content": "Envoyer le contenu partagé",
    "Unknown caller": "Appelant inconnu",
    "Calling…": "Appel…",
    "Incoming voice call": "Appel vocal entrant",
    "Exchanging encryption keys…": "Échange des clés de chiffrement…",
    "Ending call…": "Fin de l'appel…",
    "Decline": "Refuser",
    "Accept": "Accepter",
    "Unmute": "Réactiver le son",
    "Mute": "Couper le son",
    "End call": "Terminer l'appel",
    "Call declined": "Appel refusé",
    "No answer": "Pas de réponse",
    "Missed call": "Appel manqué",
    "Call failed": "Échec de l'appel",
    "Speaker off": "Haut-parleur désactivé",
    "Speaker": "Haut-parleur",
    "Incoming video call": "Appel vidéo entrant",
    "Video not\navailable": "Vidéo\nindisponible",
}

FRN = {
    "%n scheduled message(s)": ("%n message programmé", "%n messages programmés"),
    "%n chat(s)": ("%n discussion", "%n discussions"),
    "%1 blocked": ("%1 bloqué", "%1 bloqués"),
    "%1 subscribers": ("%1 abonné", "%1 abonnés"),
    "%1 members": ("%1 membre", "%1 membres"),
    "%1 online": ("%1 en ligne", "%1 en ligne"),
    "%Ln Messages deleted": ("%Ln message supprimé", "%Ln messages supprimés"),
    "%Ln messages have been copied": ("%Ln message copié", "%Ln messages copiés"),
    "Forward %Ln messages": ("Transférer %Ln message", "Transférer %Ln messages"),
    "%Ln messages selected": ("%Ln message sélectionné", "%Ln messages sélectionnés"),
    "%Ln join requests": ("%Ln demande d'adhésion", "%Ln demandes d'adhésion"),
    "chats": ("discussion", "discussions"),
    "unread messages": ("message non lu", "messages non lus"),
    "Delete %Ln message(s)?": ("Supprimer %Ln message ?", "Supprimer %Ln messages ?"),
    "%Ln messages of album deleted": ("%Ln message de l'album supprimé", "%Ln messages de l'album supprimés"),
    "%n comment(s)": ("%n commentaire", "%n commentaires"),
    "scored %Ln points in %2": ("a marqué %Ln point dans %2", "a marqué %Ln points dans %2"),
    "%Ln%": ("%Ln %", "%Ln %"),
    "%Ln vote(s) total": ("%Ln vote au total", "%Ln votes au total"),
    "%Ln unread messages": ("%Ln message non lu", "%Ln messages non lus"),
    "Question (%Ln characters left)": ("Question (%Ln caractère restant)", "Question (%Ln caractères restants)"),
    "Answer (%Ln characters left)": ("Réponse (%Ln caractère restant)", "Réponse (%Ln caractères restants)"),
    "%Ln vote(s)": ("%Ln vote", "%Ln votes"),
    "%Ln vote(s) including yours": ("%Ln vote, dont le vôtre", "%Ln votes, dont le vôtre"),
    "scored %Ln points": ("a marqué %Ln point", "a marqué %Ln points"),
    "On (%n configured)": ("Activé (%n configuré)", "Activé (%n configurés)"),
    "Off (%n configured)": ("Désactivé (%n configuré)", "Désactivé (%n configurés)"),
    "%1 day(s)": ("%1 jour", "%1 jours"),
    "%n new story(es)": ("%n nouvelle story", "%n nouvelles stories"),
    "%n story(es)": ("%n story", "%n stories"),
    "Choose who will see your next story (%n selected).": ("Choisissez qui verra votre prochaine story (%n sélectionné).", "Choisissez qui verra votre prochaine story (%n sélectionnés)."),
    "Members of your custom audience (%n selected). Saved across stories.": ("Membres de votre audience personnalisée (%n sélectionné). Conservé d'une story à l'autre.", "Membres de votre audience personnalisée (%n sélectionnés). Conservé d'une story à l'autre."),
    "(%n selected)": ("(%n sélectionné)", "(%n sélectionnés)"),
    "%n contact(s) selected": ("%n contact sélectionné", "%n contacts sélectionnés"),
    "%n view(s)": ("%n vue", "%n vues"),
    "%n reaction(s)": ("%n réaction", "%n réactions"),
}


def esc(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def repl_message(m: re.Match) -> str:
    block = m.group(0)
    src = html.unescape(m.group("src"))
    if m.group("num") is not None:
        forms = FRN.get(src)
        if forms is None:
            return block
        nf = "".join(f"<numerusform>{esc(f)}</numerusform>" for f in forms)
        new_tr = f"<translation>{nf}</translation>"
    else:
        tr = FR.get(src)
        if tr is None:
            return block
        new_tr = f"<translation>{esc(tr)}</translation>"
    return re.sub(r'<translation[^>]*>.*?</translation>', new_tr, block, count=1, flags=re.S)


def main():
    data = EN.read_text(encoding="utf-8")
    data = data.replace('language="en"', 'language="fr"', 1)
    pattern = re.compile(
        r'<message(?P<num> numerus="yes")?>(?P<body>.*?<source>(?P<src>.*?)</source>.*?)</message>',
        re.S,
    )
    out = pattern.sub(repl_message, data)
    OUT.write_text(out, encoding="utf-8")
    print(f"Scritto {OUT} — unfinished residui: {out.count('type=\"unfinished\"')}")


if __name__ == "__main__":
    main()
