#!/usr/bin/env python3
"""Genera translations/harbour-rootelegram-pl.ts (polacco) da -en.ts.

- Singolari: PL[src] = "tłumaczenie".
- Plurali Qt (numerus="yes"): PLN[src] = (forma1_one, forma2_few, forma3_many)
  (il polacco usa 3 forme: one / few / many).
- Le stringhe non presenti nei dict restano type="unfinished" col sorgente.
- Esegue: clona la struttura di -en.ts cambiando language="pl".
"""
from pathlib import Path
import html
import re
import sys

EN = Path("translations/harbour-rootelegram-en.ts")
OUT = Path("translations/harbour-rootelegram-pl.ts")

PL = {
    # About / crediti
    "About RooTelegram": "O RooTelegram",
    "A Telegram client for Sailfish OS": "Klient Telegrama dla Sailfish OS",
    "Licensed under GNU GPLv3": "Na licencji GNU GPLv3",
    "Terms of Service": "Warunki korzystania",
    "Privacy Policy": "Polityka prywatności",
    "Credits": "Podziękowania",
    "This project uses the Telegram Database Library (TDLib). Thanks for making it available under the conditions of the Boost Software License 1.0!": "Ten projekt korzysta z biblioteki Telegram Database Library (TDLib). Dziękujemy za udostępnienie jej na warunkach licencji Boost Software License 1.0!",
    "Open Telegram Database Library on GitHub": "Otwórz Telegram Database Library na GitHubie",
    "About Telegram": "O Telegramie",
    "This product uses the Telegram API but is not endorsed or certified by Telegram.": "Ten produkt korzysta z API Telegrama, ale nie jest przez Telegram wspierany ani certyfikowany.",
    "TDLib version %1": "TDLib wersja %1",
    "This project uses rlottie. Copyright 2020 Samsung Electronics Co., Ltd. and other contributors. Thanks for making it available under the conditions of the MIT License!": "Ten projekt korzysta z rlottie. Copyright 2020 Samsung Electronics Co., Ltd. i inni współtwórcy. Dziękujemy za udostępnienie jej na warunkach licencji MIT!",
    "Open rlottie on GitHub": "Otwórz rlottie na GitHubie",
    "This project uses OpenStreetMap Nominatim for reverse geocoding of location attachments. Thanks for making it available as web service!": "Ten projekt korzysta z OpenStreetMap Nominatim do odwrotnego geokodowania załączników z lokalizacją. Dziękujemy za udostępnienie tej usługi internetowej!",
    "Open OSM Nominatim Wiki": "Otwórz wiki OSM Nominatim",
    "Fernschreiber": "Fernschreiber",
    "Yottagram": "Yottagram",
    "Source code on GitHub": "Kod źródłowy na GitHubie",
    "Fork by RootGPT - based on Fernschreiber by Sebastian J. Wolf and Yottagram by Michal Szczepaniak.": "Fork autorstwa RootGPT – na podstawie Fernschreiber autorstwa Sebastiana J. Wolfa oraz Yottagram autorstwa Michała Szczepaniaka.",
    "This project uses Twemoji (jdecked fork). Copyright the Twemoji contributors. Thanks for making it available under the conditions of the MIT License (coding) and CC-BY 4.0 (graphics)!": "Ten projekt korzysta z Twemoji (fork jdecked). Copyright współtwórcy Twemoji. Dziękujemy za udostępnienie na warunkach licencji MIT (kod) oraz CC-BY 4.0 (grafika)!",
    "Open Twemoji on GitHub": "Otwórz Twemoji na GitHubie",
    "This project bundles FFmpeg, built with libx264, to normalize videos before upload. Thanks for making it available under the conditions of the LGPL v2.1+ / GPL v2+ (libx264)!": "Ten projekt dołącza FFmpeg, zbudowany z libx264, do normalizacji filmów przed wysłaniem. Dziękujemy za udostępnienie na warunkach LGPL v2.1+ / GPL v2+ (libx264)!",
    "Open FFmpeg website": "Otwórz stronę FFmpeg",
    "This project uses tgcalls and tg_owt (WebRTC) for voice and video calls. Thanks for making them available under the conditions of the GPL v2+!": "Ten projekt korzysta z tgcalls i tg_owt (WebRTC) do połączeń głosowych i wideo. Dziękujemy za udostępnienie ich na warunkach GPL v2+!",
    "Open tgcalls on GitHub": "Otwórz tgcalls na GitHubie",
    "For SailfishOS 5.0/5.1 compatibility this package also bundles FFmpeg's multimedia dependencies: libvpx, Opus, Ogg, Vorbis, Theora, Speex, WebP, libsharpyuv (BSD) and OpenJPEG (BSD-2). Copyright their respective contributors. The full license texts are shipped in /usr/share/harbour-rootelegram/licenses/.": "Dla zgodności z SailfishOS 5.0/5.1 pakiet dołącza też multimedialne zależności FFmpeg: libvpx, Opus, Ogg, Vorbis, Theora, Speex, WebP, libsharpyuv (BSD) oraz OpenJPEG (BSD-2). Copyright odpowiedni współtwórcy. Pełne teksty licencji znajdują się w /usr/share/harbour-rootelegram/licenses/.",
    # Membri / contatti
    "Refresh": "Odśwież",
    "Add Members": "Dodaj członków",
    "Search a contact...": "Szukaj kontaktu...",
    "No contacts found.": "Nie znaleziono kontaktów.",
    "You don't have any contacts.": "Nie masz żadnych kontaktów.",
    "Added": "Dodano",
    "Adding…": "Dodawanie…",
    "Loading contacts...": "Wczytywanie kontaktów...",
    "Member added.": "Dodano członka.",
    # Proxy
    "Proxy added and enabled": "Dodano i włączono proxy",
    "Add proxy": "Dodaj proxy",
    "Add": "Dodaj",
    "Paste a proxy link (optional)": "Wklej link proxy (opcjonalnie)",
    "tg://proxy?server=…  or  https://t.me/proxy?…": "tg://proxy?server=…  lub  https://t.me/proxy?…",
    "Link recognised": "Rozpoznano link",
    "Type": "Typ",
    "MTProto (recommended)": "MTProto (zalecane)",
    "SOCKS5 (also for calls)": "SOCKS5 (także dla połączeń)",
    "HTTP": "HTTP",
    "Server": "Serwer",
    "Server (host or IP)": "Serwer (host lub IP)",
    "Port": "Port",
    "Secret": "Sekret",
    "Secret (supports dd… and ee… Fake-TLS)": "Sekret (obsługuje dd… i ee… Fake-TLS)",
    "Username (optional)": "Nazwa użytkownika (opcjonalnie)",
    "Username": "Nazwa użytkownika",
    "Password (optional)": "Hasło (opcjonalnie)",
    "Password": "Hasło",
    "HTTP only": "Tylko HTTP",
    "The proxy supports only HTTP requests (no HTTPS tunnelling).": "To proxy obsługuje tylko żądania HTTP (bez tunelowania HTTPS).",
    # Cartelle / media tipi
    "Add to folder": "Dodaj do folderu",
    "Added to folder: %1": "Dodano do folderu: %1",
    "No folders": "Brak folderów",
    "Photo": "Zdjęcie",
    "Video": "Film",
    "Document": "Dokument",
    "Voice": "Głos",
    "GIF": "GIF",
    "Sticker": "Naklejka",
    "Location": "Lokalizacja",
    "Unknown chat": "Nieznany czat",
    "Scheduled messages": "Zaplanowane wiadomości",
    "Loading…": "Wczytywanie…",
    "No scheduled messages": "Brak zaplanowanych wiadomości",
    "Long-press the send button in a chat to schedule a new message.": "Przytrzymaj przycisk wysyłania w czacie, aby zaplanować nową wiadomość.",
    "Deleting": "Usuwanie",
    "Reschedule": "Zmień termin",
    "Delete": "Usuń",
    "Voice message": "Wiadomość głosowa",
    "Video message": "Wiadomość wideo",
    "Audio": "Audio",
    "Contact": "Kontakt",
    "Poll": "Ankieta",
    "Call": "Połączenie",
    "Archived chats": "Zarchiwizowane czaty",
    "Unknown": "Nieznany",
    "Unarchive": "Przywróć z archiwum",
    "No archived chats": "Brak zarchiwizowanych czatów",
    "Long-press a chat in the main list and choose Archive.": "Przytrzymaj czat na liście głównej i wybierz Archiwizuj.",
    "%1 %": "%1 %",
    "%1": "%1",
    # Blacklist
    "Blacklist": "Czarna lista",
    "No blocked users.": "Brak zablokowanych użytkowników.",
    "Block a user from their profile to see them here.": "Zablokuj użytkownika z jego profilu, aby zobaczyć go tutaj.",
    "Unblocking…": "Odblokowywanie…",
    "Unblock": "Odblokuj",
    "Load more": "Wczytaj więcej",
    "Loading blocked users...": "Wczytywanie zablokowanych użytkowników...",
    "User has been unblocked.": "Użytkownik został odblokowany.",
    # Tema canale
    "Theme cleared": "Wyczyszczono motyw",
    "Theme set: %1": "Ustawiono motyw: %1",
    "Appearance": "Wygląd",
    "Pick a chat theme. The selected preset is applied to every member viewing this channel.": "Wybierz motyw czatu. Wybrany szablon zostanie zastosowany dla każdego, kto ogląda ten kanał.",
    "Default (no theme)": "Domyślny (brak motywu)",
    "No themes available yet": "Brak dostępnych motywów",
    "Themes are pushed by Telegram after sign-in. Try again in a moment.": "Motywy są dostarczane przez Telegram po zalogowaniu. Spróbuj ponownie za chwilę.",
    # Cartelle
    "Folder created.": "Utworzono folder.",
    "Unable to create folder %1": "Nie można utworzyć folderu %1",
    "Unable to update folder order.": "Nie można zaktualizować kolejności folderów.",
    "Edit folders": "Edytuj foldery",
    "All": "Wszystkie",
    "Custom folders": "Własne foldery",
    "Create new folder": "Utwórz nowy folder",
    "Folder name": "Nazwa folderu",
    "Enter the folder name": "Wpisz nazwę folderu",
    "Create folder": "Utwórz folder",
    "Deleting folder": "Usuwanie folderu",
    "Folder deleted.": "Usunięto folder.",
    "Unable to delete folder %1": "Nie można usunąć folderu %1",
    "Unable to delete folder.": "Nie można usunąć folderu.",
    "Folder name must be at most 12 characters.": "Nazwa folderu może mieć maksymalnie 12 znaków.",
    "Unable to create folder %1: %2": "Nie można utworzyć folderu %1: %2",
    "Unable to create folder.": "Nie można utworzyć folderu.",
    "Creating folder...": "Tworzenie folderu...",
    "Retrying creation...": "Ponawianie tworzenia...",
    "Error creating folder: %1": "Błąd podczas tworzenia folderu: %1",
    "Internal error while creating folder.": "Błąd wewnętrzny podczas tworzenia folderu.",
    # Chat info
    "Leave Chat": "Opuść czat",
    "Join Chat": "Dołącz do czatu",
    "Leaving chat": "Opuszczanie czatu",
    "Chat Title": "Tytuł czatu",
    "Enter 1-128 characters": "Wpisz od 1 do 128 znaków",
    "There is no information text available, yet.": "Brak dostępnego tekstu informacyjnego.",
    "Info": "Informacje",
    "Phone Number": "Numer telefonu",
    "The Invite Link has been copied to the clipboard.": "Link zaproszenia skopiowano do schowka.",
    "%1, %2": "%1, %2",
    "New Secret Chat": "Nowy tajny czat",
    "Unmute Chat": "Wyłącz wyciszenie czatu",
    "Mute Chat": "Wycisz czat",
    "ID has been copied to the clipboard.": "Identyfikator skopiowano do schowka.",
    "Join Requests": "Prośby o dołączenie",
    "Unable to start the call.": "Nie można rozpocząć połączenia.",
    "Public": "Publiczny",
    "Private": "Prywatny",
    "Visible": "Widoczny",
    "Hidden": "Ukryty",
    "Off": "Wył.",
    "On": "Wł.",
    "%1 selected": "Zaznaczono: %1",
    "None": "Brak",
    "No": "Nie",
    "Default": "Domyślny",
    "Available": "Dostępny",
    "Unavailable": "Niedostępny",
    "%1 is not available yet.": "%1 nie jest jeszcze dostępny.",
    "No invite link available yet.": "Brak dostępnego linku zaproszenia.",
    "Deleting channel": "Usuwanie kanału",
    "Channel Settings": "Ustawienia kanału",
    "Group Settings": "Ustawienia grupy",
    "Channel Type": "Typ kanału",
    "Group Type": "Typ grupy",
    "Chat History": "Historia czatu",
    "Only administrators can change chat history visibility.": "Tylko administratorzy mogą zmienić widoczność historii czatu.",
    "Topics": "Tematy",
    "Discussion": "Dyskusja",
    "Direct Messages": "Wiadomości bezpośrednie",
    "Auto-Translate Messages": "Automatyczne tłumaczenie wiadomości",
    "Reactions": "Reakcje",
    "Permissions": "Uprawnienia",
    "Invite Link": "Link zaproszenia",
    "Administrators": "Administratorzy",
    "Subscribers": "Subskrybenci",
    "Members": "Członkowie",
    "Removed Users": "Usunięci użytkownicy",
    "Statistics": "Statystyki",
    "Statistics are unavailable for this chat.": "Statystyki są niedostępne dla tego czatu.",
    "Recent Actions": "Ostatnie działania",
    "Affiliate Programs": "Programy partnerskie",
    "Delete channel": "Usuń kanał",
    "Delete and leave group": "Usuń i opuść grupę",
    "Reactions can only be changed in supergroups and channels.": "Reakcje można zmieniać tylko w supergrupach i kanałach.",
    "Only administrators can change reactions.": "Tylko administratorzy mogą zmieniać reakcje.",
    "Topics enabled.": "Włączono tematy.",
    "Topics disabled.": "Wyłączono tematy.",
    "All reactions enabled.": "Włączono wszystkie reakcje.",
    "Reactions disabled.": "Wyłączono reakcje.",
    "Basic groups are private.": "Podstawowe grupy są prywatne.",
    "Only administrators can change the group type.": "Tylko administratorzy mogą zmienić typ grupy.",
    "Only the group owner can change topics.": "Tylko właściciel grupy może zmieniać tematy.",
    "Chat history is now visible.": "Historia czatu jest teraz widoczna.",
    "Chat history is now hidden.": "Historia czatu jest teraz ukryta.",
    "Message history can't be hidden while topics are enabled.": "Nie można ukryć historii wiadomości, gdy tematy są włączone.",
    "Manage Topics": "Zarządzaj tematami",
    "Only administrators can manage topics.": "Tylko administratorzy mogą zarządzać tematami.",
    "Only administrators can change the group picture.": "Tylko administratorzy mogą zmienić zdjęcie grupy.",
    "Uploading group picture...": "Przesyłanie zdjęcia grupy...",
    "Group picture updated.": "Zaktualizowano zdjęcie grupy.",
    "Channel Picture": "Zdjęcie kanału",
    "Group Picture": "Zdjęcie grupy",
    "Only the channel owner can change the discussion group.": "Tylko właściciel kanału może zmienić grupę dyskusyjną.",
    "Only administrators can change the appearance.": "Tylko administratorzy mogą zmienić wygląd.",
    "Convert to supergroup": "Przekształć w supergrupę",
    "Converting to supergroup": "Przekształcanie w supergrupę",
    "Conversion in progress…": "Trwa przekształcanie…",
    "User has been blocked.": "Użytkownik został zablokowany.",
    "Unblock User": "Odblokuj użytkownika",
    "Block User": "Zablokuj użytkownika",
    "Unable to load content.": "Nie można wczytać zawartości.",
    "Loading common chats…": "Wczytywanie wspólnych czatów…",
    "Loading group members…": "Wczytywanie członków grupy…",
    "You": "Ty",
    "You don't have any groups in common with this user.": "Nie masz żadnych wspólnych grup z tym użytkownikiem.",
    "This group is empty.": "Ta grupa jest pusta.",
    "Channel members are anonymous.": "Członkowie kanału są anonimowi.",
    "Processing…": "Przetwarzanie…",
    "Promote to Admin": "Awansuj na administratora",
    "Remove Admin": "Usuń administratora",
    "Removing Admin": "Usuwanie administratora",
    "Admin demoted to member.": "Zdegradowano administratora do członka.",
    "Remove from group": "Usuń z grupy",
    "Removing user": "Usuwanie użytkownika",
    "Member removed from group.": "Usunięto członka z grupy.",
    "Member promoted to Admin.": "Awansowano członka na administratora.",
    "Groups": "Grupy",
    "Settings": "Ustawienia",
    "Voice calls are not available in this build yet.": "Połączenia głosowe nie są jeszcze dostępne w tej wersji.",
    "Media": "Multimedia",
    "No media available.": "Brak dostępnych multimediów.",
    "Documents": "Dokumenty",
    "No documents available.": "Brak dostępnych dokumentów.",
    "Link": "Link",
    "No links available.": "Brak dostępnych linków.",
    "No audio available.": "Brak dostępnego audio.",
    "Video call": "Połączenie wideo",
    "Video calls are not available in this build yet.": "Połączenia wideo nie są jeszcze dostępne w tej wersji.",
    "Search requests": "Szukaj próśb",
    "There are no pending join requests.": "Brak oczekujących próśb o dołączenie.",
    "No bio": "Brak opisu",
    "Requested %1": "Poproszono %1",
    "Approving…": "Zatwierdzanie…",
    "Approve": "Zatwierdź",
    "Rejecting…": "Odrzucanie…",
    "Reject": "Odrzuć",
    "User Info": "Informacje o użytkowniku",
    "Group Info": "Informacje o grupie",
    "Mark all messages as read": "Oznacz wszystkie wiadomości jako przeczytane",
    "No message in this chat.": "Brak wiadomości w tym czacie.",
    "Mark chat as unread": "Oznacz czat jako nieprzeczytany",
    "Mark chat as read": "Oznacz czat jako przeczytany",
    "Draft": "Wersja robocza",
    "Unpin chat": "Odepnij czat",
    "Pin chat": "Przypnij czat",
    "Unmute chat": "Wyłącz wyciszenie czatu",
    "Mute chat": "Wycisz czat",
    "Delete Chat": "Usuń czat",
    "Deleting chat": "Usuwanie czatu",
    "Add to folder...": "Dodaj do folderu...",
    "Remove from folder: %1": "Usuń z folderu: %1",
    "Removed from folder: %1": "Usunięto z folderu: %1",
    "Archive chat": "Archiwizuj czat",
    "Your message": "Twoja wiadomość",
    "Loading messages...": "Wczytywanie wiadomości...",
    "Edit Message": "Edytuj wiadomość",
    "edited": "edytowano",
    "Uploading...": "Przesyłanie...",
    "This chat is empty.": "Ten czat jest pusty.",
    "You joined the chat %1": "Dołączono do czatu %1",
    "Select Messages": "Zaznacz wiadomości",
    "This secret chat is not yet ready. Your chat partner needs to go online first.": "Ten tajny czat nie jest jeszcze gotowy. Twój rozmówca musi najpierw wejść do sieci.",
    "Closing chat": "Zamykanie czatu",
    "Close Chat": "Zamknij czat",
    "Search in Chat": "Szukaj w czacie",
    "Search in chat...": "Szukaj w czacie...",
    "Location: Obtaining position...": "Lokalizacja: ustalanie pozycji...",
    "Location (%1/%2)": "Lokalizacja (%1/%2)",
    "Copy Message to Clipboard": "Kopiuj wiadomość",
    "Message unpinned": "Odpięto wiadomość",
    "Unpin Message": "Odepnij wiadomość",
    "Pin Message": "Przypnij wiadomość",
    "Additional Options": "Dodatkowe opcje",
    "Unknown address": "Nieznany adres",
    "Accuracy: %1m": "Dokładność: %1 m",
    "Sponsored Message": "Wiadomość sponsorowana",
    "Deleted User": "Usunięty użytkownik",
    "Double-tap on a message to choose a reaction": "Dotknij dwukrotnie wiadomości, aby wybrać reakcję",
    "Forward message": "Prześlij wiadomość",
    "Delete message": "Usuń wiadomość",
    "Topic is closed": "Temat jest zamknięty",
    "Copy Selected Text": "Kopiuj zaznaczony tekst",
    "Quote Selected Text": "Cytuj zaznaczony tekst",
    "Premium set": "Zestaw Premium",
    "No premium emoji set available": "Brak dostępnego zestawu emoji Premium",
    "Only the first shared file has been prepared.": "Przygotowano tylko pierwszy udostępniony plik.",
    "Unable to send this sticker.": "Nie można wysłać tej naklejki.",
    "Telegram allows up to %1 images per album.": "Telegram pozwala na maksymalnie %1 obrazów w albumie.",
    "Scheduled for %1": "Zaplanowano na %1",
    "Recent": "Ostatnie",
    "Sticker set": "Zestaw naklejek",
    "No recent stickers": "Brak ostatnich naklejek",
    "No stickers in this set": "Brak naklejek w tym zestawie",
    'Do you want to delete "%1"?': 'Czy chcesz usunąć „%1”?',
    "Do you want to delete this set?": "Czy chcesz usunąć ten zestaw?",
    'Deleting "%1"': "Usuwanie „%1”",
    "Deleting set": "Usuwanie zestawu",
    "Yes": "Tak",
    "Type your message first, then tap this button to translate it to English!": "Najpierw wpisz wiadomość, a następnie dotknij tego przycisku, aby przetłumaczyć ją na angielski!",
    "RooTelegram couldn't detect the language of the text — maybe you wrote a multilingual message?": "RooTelegram nie wykrył języka tekstu — może napisałeś wiadomość wielojęzyczną?",
    "Selected text copied to clipboard": "Skopiowano zaznaczony tekst do schowka",
    "Code copied to clipboard": "Skopiowano kod do schowka",
    # Stato "sta scrivendo"
    "is recording a voice message": "nagrywa wiadomość głosową",
    "is recording a video message": "nagrywa wiadomość wideo",
    "is recording a video": "nagrywa film",
    "is sending a voice message": "wysyła wiadomość głosową",
    "is sending a video message": "wysyła wiadomość wideo",
    "is sending a video": "wysyła film",
    "is sending a photo": "wysyła zdjęcie",
    "is sending a file": "wysyła plik",
    "is choosing a sticker": "wybiera naklejkę",
    "is choosing a location": "wybiera lokalizację",
    "is choosing a contact": "wybiera kontakt",
    "is typing…": "pisze…",
    "Unknown user": "Nieznany użytkownik",
    # Azioni log
    "edited a message": "edytował wiadomość",
    "deleted a message": "usunął wiadomość",
    "pinned a message": "przypiął wiadomość",
    "joined the chat": "dołączył do czatu",
    "joined via invite link": "dołączył przez link zaproszenia",
    "left the chat": "opuścił czat",
    "invited a member": "zaprosił członka",
    "updated administrator rights": "zaktualizował uprawnienia administratora",
    "updated member permissions": "zaktualizował uprawnienia członka",
    "changed the chat title": "zmienił tytuł czatu",
    "changed the description": "zmienił opis",
    "changed the public username": "zmienił publiczną nazwę użytkownika",
    "changed the photo": "zmienił zdjęcie",
    "changed invite link permissions": "zmienił uprawnienia linku zaproszenia",
    "changed message signing": "zmienił podpisywanie wiadomości",
    "changed sticker set": "zmienił zestaw naklejek",
    "changed linked chat": "zmienił powiązany czat",
    "changed slow mode": "zmienił tryb wolny",
    "started a video chat": "rozpoczął czat wideo",
    "ended the video chat": "zakończył czat wideo",
    "changed video chat permissions": "zmienił uprawnienia czatu wideo",
    "edited an invite link": "edytował link zaproszenia",
    "revoked an invite link": "unieważnił link zaproszenia",
    "deleted an invite link": "usunął link zaproszenia",
    "performed an action": "wykonał czynność",
    "Description cleared": "Wyczyszczono opis",
    "Username removed": "Usunięto nazwę użytkownika",
    "Slow mode: %1s": "Tryb wolny: %1 s",
    "Slow mode disabled": "Wyłączono tryb wolny",
    "Linked chat removed": "Usunięto powiązany czat",
    "No recent actions found.": "Nie znaleziono ostatnich działań.",
    "Select Chat": "Wybierz czat",
    "You don't have any chats yet.": "Nie masz jeszcze żadnych czatów.",
    "Search in contacts...": "Szukaj w kontaktach...",
    "Send contact": "Wyślij kontakt",
    "Search contact": "Szukaj kontaktu",
    "No contacts with a phone number": "Brak kontaktów z numerem telefonu",
    "Could not synchronize your contacts with Telegram.": "Nie udało się zsynchronizować kontaktów z Telegramem.",
    "in": "w",
    "Waiting for network...": "Oczekiwanie na sieć...",
    "Connecting to network...": "Łączenie z siecią...",
    "Connecting to proxy...": "Łączenie z proxy...",
    "Connected": "Połączono",
    "Updating content...": "Aktualizowanie zawartości...",
    "New Channel": "Nowy kanał",
    "New Group": "Nowa grupa",
    "Cancel": "Anuluj",
    "Delete for everyone": "Usuń u wszystkich",
    "Delete for me": "Usuń u mnie",
    "Group Member Permissions": "Uprawnienia członków grupy",
    "Send Messages": "Wysyłanie wiadomości",
    "Send Media Messages": "Wysyłanie multimediów",
    "Send Other Messages": "Wysyłanie innych wiadomości",
    "Add Web Page Previews": "Dodawanie podglądów stron",
    "Change Chat Info": "Zmiana informacji o czacie",
    "Invite Users": "Zapraszanie użytkowników",
    "Pin Messages": "Przypinanie wiadomości",
    "New Members": "Nowi członkowie",
    "New members can see older messages": "Nowi członkowie widzą starsze wiadomości",
    "Send Polls": "Wysyłanie ankiet",
    "Create Topics": "Tworzenie tematów",
    "Group permissions updated.": "Zaktualizowano uprawnienia grupy.",
    "Some permission changes were rejected by Telegram.": "Część zmian uprawnień została odrzucona przez Telegram.",
    "Slow Mode": "Tryb wolny",
    "Set how long every chat member has to wait between Messages": "Ustaw, jak długo każdy członek czatu musi czekać między wiadomościami",
    "Search emoji": "Szukaj emoji",
    "No results": "Brak wyników",
    "No emoji": "Brak emoji",
    "Loading topics...": "Wczytywanie tematów...",
    "No topics found": "Nie znaleziono tematów",
    "This group has no topics yet.": "Ta grupa nie ma jeszcze tematów.",
    "Topic name must be between 1 and 128 characters.": "Nazwa tematu musi mieć od 1 do 128 znaków.",
    "Create Topic": "Utwórz temat",
    "Disable Topics": "Wyłącz tematy",
    "Topic created.": "Utworzono temat.",
    "Topic renamed.": "Zmieniono nazwę tematu.",
    "Topic deleted.": "Usunięto temat.",
    "Topic closed.": "Zamknięto temat.",
    "Topic reopened.": "Ponownie otwarto temat.",
    "Topic name": "Nazwa tematu",
    "New topic name": "Nowa nazwa tematu",
    "Enter topic name": "Wpisz nazwę tematu",
    "Saving…": "Zapisywanie…",
    "Create": "Utwórz",
    "Rename": "Zmień nazwę",
    "Rename topic": "Zmień nazwę tematu",
    "Reopen topic": "Otwórz temat ponownie",
    "Close topic": "Zamknij temat",
    "Delete topic": "Usuń temat",
    "Deleting topic": "Usuwanie tematu",
    "Closed": "Zamknięty",
    "You don't have permission to create topics.": "Nie masz uprawnień do tworzenia tematów.",
    "Saved %1": "Zapisano %1",
    "Save failed.": "Zapis nie powiódł się.",
    "Username must be 5-32 characters.": "Nazwa użytkownika musi mieć od 5 do 32 znaków.",
    "Username can only use letters, numbers and underscores.": "Nazwa użytkownika może zawierać tylko litery, cyfry i podkreślenia.",
    "Save": "Zapisz",
    "Public Channel": "Kanał publiczny",
    "Public Group": "Grupa publiczna",
    "Public chats can be found via username.": "Publiczne czaty można znaleźć po nazwie użytkownika.",
    "Private chats can only be joined through invite links.": "Do prywatnych czatów można dołączyć tylko przez linki zaproszenia.",
    "Set public username": "Ustaw publiczną nazwę użytkownika",
    "Use 5-32 letters, numbers or underscores.": "Użyj od 5 do 32 liter, cyfr lub podkreśleń.",
    "Approve new members": "Zatwierdzaj nowych członków",
    "New members must be approved by an administrator.": "Nowi członkowie muszą zostać zatwierdzeni przez administratora.",
    "Forbid content saving": "Zabroń zapisywania zawartości",
    "Prevents forwarding, copying and saving of chat contents.": "Uniemożliwia przesyłanie, kopiowanie i zapisywanie zawartości czatu.",
    "Options saved": "Zapisano opcje",
    "Download Picture": "Pobierz zdjęcie",
    "Download of %1 successful.": "Pobrano %1 pomyślnie.",
    "Download failed.": "Pobieranie nie powiodło się.",
    "This message was deleted": "Ta wiadomość została usunięta",
    "OK": "OK",
    # Login / registrazione
    "Welcome to RooTelegram!": "Witamy w RooTelegram!",
    "Please enter your phone number to continue.": "Wpisz swój numer telefonu, aby kontynuować.",
    "Continue": "Kontynuuj",
    "Please enter the code that you received:": "Wpisz otrzymany kod:",
    "Loading...": "Wczytywanie...",
    "Unable to authenticate you with the entered code.": "Nie można uwierzytelnić Cię wpisanym kodem.",
    "Enter code again": "Wpisz kod ponownie",
    "Restart authentication": "Uruchom uwierzytelnianie ponownie",
    "Please enter your password:": "Wpisz swoje hasło:",
    "User Registration": "Rejestracja użytkownika",
    "Enter your First Name": "Wpisz swoje imię",
    "Enter your Last Name": "Wpisz swoje nazwisko",
    "Register User": "Zarejestruj użytkownika",
    "Use the international format, e.g. %1": "Użyj formatu międzynarodowego, np. %1",
    "Transcribe": "Transkrybuj",
    "Play/Pause": "Odtwórz/wstrzymaj",
    "Contact saved to address book": "Zapisano kontakt w książce adresowej",
    "Could not save the contact": "Nie udało się zapisać kontaktu",
    "Message": "Napisz",
    "Add to contacts": "Dodaj do kontaktów",
    # Info messaggio
    "When the recipient comes online": "Gdy odbiorca będzie online",
    "Message info": "Informacje o wiadomości",
    "Sent": "Wysłano",
    "Edited": "Edytowano",
    "Scheduled": "Zaplanowano",
    "Sender": "Nadawca",
    "Author signature": "Podpis autora",
    "Via bot": "Przez bota",
    "Forwarded from": "Przekazano od",
    "Original date": "Pierwotna data",
    "Views": "Wyświetlenia",
    "Forwards": "Przekazania",
    "Message ID": "ID wiadomości",
    "Album ID": "ID albumu",
    "Reply to Message": "Odpowiedz na wiadomość",
    "Forwarded Message": "Przekazana wiadomość",
    "Select Message": "Zaznacz wiadomość",
    "More Options...": "Więcej opcji...",
    "Message deleted": "Usunięto wiadomość",
    "Delete all messages from %1": "Usuń wszystkie wiadomości od %1",
    "Delete all messages from this user": "Usuń wszystkie wiadomości tego użytkownika",
    "Ban %1": "Zbanuj %1",
    "Ban user": "Zbanuj użytkownika",
    "Report as spam": "Zgłoś jako spam",
    "Deletion of messages started": "Rozpoczęto usuwanie wiadomości",
    "User banned": "Zbanowano użytkownika",
    "Report submitted": "Wysłano zgłoszenie",
    "Delete album": "Usuń album",
    "Hide spoiler": "Ukryj spoiler",
    "Reveal spoiler": "Odkryj spoiler",
    "In reply to a story": "W odpowiedzi na relację",
    "Translate message": "Przetłumacz wiadomość",
    "Someone": "Ktoś",
    "This message was forwarded. Original author: %1": "Ta wiadomość została przekazana. Pierwotny autor: %1",
    "Close Poll": "Zamknij ankietę",
    "Reset Answer": "Resetuj odpowiedź",
    "Final Result:": "Wynik końcowy:",
    "Multiple Answers are allowed.": "Dozwolonych jest wiele odpowiedzi.",
    "via %1": "przez %1",
    "Seen by": "Wyświetlone przez",
    "No views": "Brak wyświetleń",
    "Voice Note": "Notatka głosowa",
    "Your Contacts": "Twoje kontakty",
    "Private Chat": "Czat prywatny",
    "Secret Chat": "Tajny czat",
    "End-to-end-encrypted, accessible on this device only": "Szyfrowany od końca do końca, dostępny tylko na tym urządzeniu",
    "Transport-encrypted, uses Telegram Cloud, sharable across devices": "Szyfrowany w transporcie, korzysta z chmury Telegrama, dostępny na wielu urządzeniach",
    "Synchronize Contacts with Telegram": "Synchronizuj kontakty z Telegramem",
    "Contacts successfully synchronized with Telegram.": "Pomyślnie zsynchronizowano kontakty z Telegramem.",
    "posted a new story": "opublikował nową relację",
    "reacted to your message": "zareagował na Twoją wiadomość",
    "reacted %1 to your message": "zareagował %1 na Twoją wiadomość",
    "My chats": "Moje czaty",
    "Global results": "Wyniki globalne",
    "User": "Użytkownik",
    "Group": "Grupa",
    "Channel": "Kanał",
    "No public users, groups or channels found.": "Nie znaleziono publicznych użytkowników, grup ani kanałów.",
    "Loading chat list...": "Wczytywanie listy czatów...",
    "New Chat": "Nowy czat",
    "Tap on the title bar to filter your chats": "Dotknij paska tytułu, aby filtrować czaty",
    "No matching chats found.": "Nie znaleziono pasujących czatów.",
    "You can search public chats or create a new chat via the pull-down menu.": "Możesz wyszukać publiczne czaty lub utworzyć nowy czat za pomocą menu rozwijanego.",
    "Logging out": "Wylogowywanie",
    "Unable to open link.": "Nie można otworzyć linku.",
    "All chats marked as read.": "Oznaczono wszystkie czaty jako przeczytane.",
    "Mark all as read": "Oznacz wszystkie jako przeczytane",
    "Search chat...": "Szukaj czatu...",
    "Stories": "Relacje",
    "Reorder Pinned Chats": "Zmień kolejność przypiętych czatów",
    "Debug": "Debugowanie",
    "Search...": "Szukaj...",
    "Pin": "Przypnij",
    "Pin message": "Przypnij wiadomość",
    "Choose where to pin this message in the chat with %1.": "Wybierz, gdzie przypiąć tę wiadomość w czacie z %1.",
    "Choose where to pin this message.": "Wybierz, gdzie przypiąć tę wiadomość.",
    "Pin for": "Przypnij dla",
    "Both users": "Obu użytkowników",
    "Only me": "Tylko mnie",
    "Pinned Message": "Przypięta wiadomość",
    "All answers have to contain 1-100 characters.": "Każda odpowiedź musi mieć od 1 do 100 znaków.",
    "To send a quiz, you have to specify the right answer.": "Aby wysłać quiz, musisz wskazać prawidłową odpowiedź.",
    "You have to enter a question.": "Musisz wpisać pytanie.",
    "The question has to be shorter than 256 characters.": "Pytanie musi mieć mniej niż 256 znaków.",
    "A poll requires 2-10 answers.": "Ankieta wymaga od 2 do 10 odpowiedzi.",
    "Create a Poll": "Utwórz ankietę",
    "in %1": "w %1",
    "Enter your question here": "Wpisz tutaj swoje pytanie",
    "Answers": "Odpowiedzi",
    "Enter an answer here": "Wpisz tutaj odpowiedź",
    "Add an answer": "Dodaj odpowiedź",
    "Poll Options": "Opcje ankiety",
    "Anonymous answers": "Anonimowe odpowiedzi",
    "Multiple answers allowed": "Wiele odpowiedzi dozwolone",
    "Quiz Mode": "Tryb quizu",
    "Quizzes have one correct answer. Participants can't revoke their responses.": "Quizy mają jedną prawidłową odpowiedź. Uczestnicy nie mogą cofnąć swoich odpowiedzi.",
    "Enter an optional explanation": "Wpisz opcjonalne wyjaśnienie",
    "Shown when the user selects a wrong answer.": "Wyświetlane, gdy użytkownik wybierze błędną odpowiedź.",
    "An explanation can be up to 200 characters long.": "Wyjaśnienie może mieć maksymalnie 200 znaków.",
    "Quiz Results": "Wyniki quizu",
    "Poll Results": "Wyniki ankiety",
    "Question": "Pytanie",
    "Results": "Wyniki",
    "Chosen by:": "Wybrane przez:",
    "Promote": "Awansuj",
    "Promote %1 to Admin": "Awansuj %1 na administratora",
    "Custom title (max 16 characters)": "Własny tytuł (maks. 16 znaków)",
    "e.g. Moderator": "np. Moderator",
    "Privileges": "Uprawnienia",
    "Manage chat": "Zarządzaj czatem",
    "View admin log and chat statistics.": "Wyświetl dziennik administratora i statystyki czatu.",
    "Change group info": "Zmień informacje o grupie",
    "Title, photo and description.": "Tytuł, zdjęcie i opis.",
    "Delete messages": "Usuwaj wiadomości",
    "Ban users": "Banuj użytkowników",
    "Invite users": "Zapraszaj użytkowników",
    "Pin messages": "Przypinaj wiadomości",
    "Manage topics": "Zarządzaj tematami",
    "Manage video chats": "Zarządzaj czatami wideo",
    "Post messages": "Publikuj wiadomości",
    "Edit messages of others": "Edytuj wiadomości innych",
    "Post stories": "Publikuj relacje",
    "Edit stories": "Edytuj relacje",
    "Delete stories": "Usuwaj relacje",
    "Add new admins": "Dodawaj nowych administratorów",
    "With the rights this user already has.": "Z uprawnieniami, które ten użytkownik już posiada.",
    "Anonymous": "Anonimowo",
    "Send messages as the group itself.": "Wysyłaj wiadomości w imieniu samej grupy.",
    "MTProto": "MTProto",
    "SOCKS5": "SOCKS5",
    "%1 ms": "%1 ms",
    "Proxy": "Proxy",
    "Disable proxy (direct connection)": "Wyłącz proxy (połączenie bezpośrednie)",
    "Proxy disabled": "Wyłączono proxy",
    "No proxies": "Brak proxy",
    "Pull down to add a proxy, or paste a tg://proxy link.": "Pociągnij w dół, aby dodać proxy, lub wklej link tg://proxy.",
    "Disable": "Wyłącz",
    "Enable": "Włącz",
    "Test connection": "Testuj połączenie",
    "Remove": "Usuń",
    "Removing proxy": "Usuwanie proxy",
    "Unable to update pinned chat order.": "Nie można zaktualizować kolejności przypiętych czatów.",
    "No pinned chats.": "Brak przypiętych czatów.",
    "Pin a chat from home to reorder it here.": "Przypnij czat z ekranu głównego, aby zmienić tutaj jego kolejność.",
    "sent a picture": "wysłał zdjęcie",
    "sent a video": "wysłał film",
    "sent an animation": "wysłał animację",
    "sent a voice note": "wysłał notatkę głosową",
    "sent a document": "wysłał dokument",
    "sent a location": "wysłał lokalizację",
    "have registered with Telegram": "zarejestrowali się w Telegramie",
    "has registered with Telegram": "zarejestrował się w Telegramie",
    "joined this chat": "dołączył do tego czatu",
    "were added to this chat": "zostali dodani do tego czatu",
    "was added to this chat": "został dodany do tego czatu",
    "left this chat": "opuścił ten czat",
    "sent a venue": "wysłał miejsce",
    "sent a poll": "wysłał ankietę",
    "sent a quiz": "wysłał quiz",
    "created this group": "utworzył tę grupę",
    "changed the chat photo": "zmienił zdjęcie czatu",
    "deleted the chat photo": "usunął zdjęcie czatu",
    "changed the secret chat TTL setting": "zmienił ustawienie TTL tajnego czatu",
    "upgraded this group to a supergroup": "przekształcił tę grupę w supergrupę",
    "changed the pinned message": "zmienił przypiętą wiadomość",
    "created a screenshot in this chat": "zrobił zrzut ekranu w tym czacie",
    "sent an unsupported message": "wysłał nieobsługiwaną wiadomość",
    "sent an unsupported message: %1": "wysłał nieobsługiwaną wiadomość: %1",
    "sent a self-destructing photo that is expired": "wysłał samoznikające zdjęcie, które wygasło",
    "sent a self-destructing video that is expired": "wysłał samoznikający film, który wygasł",
    "sent an audio": "wysłał audio",
    "has added %1 to the chat": "dodał %1 do czatu",
    "has removed %1 from the chat": "usunął %1 z czatu",
    "have added %1 to the chat": "dodali %1 do czatu",
    "have removed %1 from the chat": "usunęli %1 z czatu",
    "sent a game": "wysłał grę",
    "sent a video note": "wysłał notatkę wideo",
    "cancelled a call": "anulował połączenie",
    "missed a call": "nie odebrał połączenia",
    "started a call": "rozpoczął połączenie",
    "sent a contact": "wysłał kontakt",
    "scheduled a video chat": "zaplanował czat wideo",
    "invited participants to the video chat": "zaprosił uczestników do czatu wideo",
    "changed the chat theme": "zmienił motyw czatu",
    "changed the chat background": "zmienił tło czatu",
    "Schedule": "Zaplanuj",
    "Message will be sent at the selected time.": "Wiadomość zostanie wysłana o wybranej godzinie.",
    "Pick a time in the future.": "Wybierz godzinę w przyszłości.",
    "Date": "Data",
    "Time": "Godzina",
    "Already scheduled in this chat": "Już zaplanowane w tym czacie",
    "No other scheduled messages in this chat.": "Brak innych zaplanowanych wiadomości w tym czacie.",
    "Deleting scheduled message": "Usuwanie zaplanowanej wiadomości",
    "No chats found.": "Nie znaleziono czatów.",
    "Searching chats...": "Wyszukiwanie czatów...",
    "Search Chats": "Szukaj czatów",
    "Search a chat...": "Szukaj czatu...",
    "Enter your query to start searching (at least 5 characters needed)": "Wpisz zapytanie, aby rozpocząć wyszukiwanie (potrzeba co najmniej 5 znaków)",
    "Discussion group updated": "Zaktualizowano grupę dyskusyjną",
    "Discussion group removed": "Usunięto grupę dyskusyjną",
    "Error: %1": "Błąd: %1",
    "Remove discussion group": "Usuń grupę dyskusyjną",
    "Choose a group that will host discussion of channel posts.": "Wybierz grupę, w której będą omawiane posty z kanału.",
    "No suitable groups": "Brak odpowiednich grup",
    "Create a public supergroup or convert an existing one to use as discussion.": "Utwórz publiczną supergrupę lub przekształć istniejącą, aby użyć jej do dyskusji.",
    "Reload": "Załaduj ponownie",
    "Show stickers as emojis": "Pokazuj naklejki jako emoji",
    "Only display emojis instead of the actual stickers": "Wyświetlaj tylko emoji zamiast rzeczywistych naklejek",
    "Show stickers as images": "Pokazuj naklejki jako obrazy",
    "Show background for stickers and align them centrally like images": "Pokazuj tło dla naklejek i wyrównuj je centralnie jak obrazy",
    "Animate stickers": "Animuj naklejki",
    "Cyberpunk look (requires a dark and orange theme for the perfect experience)": "Wygląd cyberpunk (dla najlepszego efektu wymaga ciemnego i pomarańczowego motywu)",
    "Silica base theme (lighter, also good on light themes)": "Podstawowy motyw Silica (lżejszy, dobry także przy jasnych motywach)",
    "Choose RooTelegram's theme": "Wybierz motyw RooTelegram",
    "Silica (base theme)": "Silica (motyw podstawowy)",
    "Neon (cyberpunk)": "Neon (cyberpunk)",
    "Behavior": "Zachowanie",
    "Send message by enter": "Wysyłaj wiadomość klawiszem Enter",
    "Send your message by pressing the enter key": "Wysyłaj wiadomość, naciskając klawisz Enter",
    "Focus text input on chat open": "Aktywuj pole tekstowe po otwarciu czatu",
    "Focus the text input area when entering a chat": "Aktywuj pole tekstowe podczas wchodzenia do czatu",
    "Focus text input area after send": "Aktywuj pole tekstowe po wysłaniu",
    "Focus the text input area after sending a message": "Aktywuj pole tekstowe po wysłaniu wiadomości",
    "Delay before marking messages as read": "Opóźnienie przed oznaczeniem wiadomości jako przeczytanych",
    "RooTelegram will wait a bit before messages are marked as read": "RooTelegram odczeka chwilę, zanim wiadomości zostaną oznaczone jako przeczytane",
    "Open-with menu integration": "Integracja z menu „Otwórz za pomocą”",
    "Integrate RooTelegram into open-with menu of Sailfish OS": "Zintegruj RooTelegram z menu „Otwórz za pomocą” systemu Sailfish OS",
    "Notification feedback": "Sygnalizacja powiadomień",
    "Use non-graphical feedback (sound, vibration) for notifications": "Używaj niewizualnej sygnalizacji (dźwięk, wibracje) dla powiadomień",
    "All events": "Wszystkie zdarzenia",
    "Only new events": "Tylko nowe zdarzenia",
    "Notification turns on the display": "Powiadomienie włącza ekran",
    "Enable notification sounds": "Włącz dźwięki powiadomień",
    "When sounds are enabled, RooTelegram will use the current Sailfish OS notification sound for chats, which can be configured in the system settings.": "Gdy dźwięki są włączone, RooTelegram użyje bieżącego dźwięku powiadomień Sailfish OS dla czatów, który można skonfigurować w ustawieniach systemu.",
    "Always append message preview to notifications": "Zawsze dołączaj podgląd wiadomości do powiadomień",
    "In addition to showing the number of unread messages, the latest message will also be appended to notifications.": "Oprócz pokazywania liczby nieprzeczytanych wiadomości, do powiadomień dołączana będzie też najnowsza wiadomość.",
    "Highlight unread messages": "Wyróżniaj nieprzeczytane wiadomości",
    "Highlight Conversations with unread messages": "Wyróżniaj rozmowy z nieprzeczytanymi wiadomościami",
    "Hide content in notifications": "Ukrywaj treść w powiadomieniach",
    "Go to quoted message": "Przejdź do cytowanej wiadomości",
    "When tapping a quoted message, open it in chat instead of showing it in an overlay.": "Po dotknięciu cytowanej wiadomości otwórz ją w czacie zamiast wyświetlać w nakładce.",
    "Cover: only private chats in unread count": "Okładka: tylko czaty prywatne w liczbie nieprzeczytanych",
    "Exclude groups and channels from the unread message and chat counts shown on the cover preview": "Wyklucz grupy i kanały z liczby nieprzeczytanych wiadomości i czatów pokazywanej na podglądzie okładki",
    "Disable video preloading": "Wyłącz wstępne wczytywanie filmów",
    "Disables automatic video preloading to reduce RAM/GPU and mobile data usage. Photos are still downloaded automatically.": "Wyłącza automatyczne wstępne wczytywanie filmów, aby zmniejszyć zużycie RAM/GPU i danych mobilnych. Zdjęcia nadal są pobierane automatycznie.",
    "Notifications": "Powiadomienia",
    "Show desktop notifications for new messages. The app always stays in background; this toggle controls only notification publishing.": "Pokazuj powiadomienia o nowych wiadomościach. Aplikacja zawsze pozostaje w tle; ten przełącznik steruje tylko publikowaniem powiadomień.",
    "Notify when a contact posts a new story.": "Powiadamiaj, gdy kontakt opublikuje nową relację.",
    "Notify when someone reacts to one of your messages.": "Powiadamiaj, gdy ktoś zareaguje na jedną z Twoich wiadomości.",
    "Connection": "Połączenie",
    "Proxies route your Telegram traffic through another server to bypass censorship. MTProto proxies (especially with Fake-TLS) are the most resistant to blocking. SOCKS5 proxies also cover voice and video calls.": "Serwery proxy kierują Twój ruch Telegrama przez inny serwer, aby ominąć cenzurę. Proxy MTProto (zwłaszcza z Fake-TLS) są najbardziej odporne na blokowanie. Proxy SOCKS5 obsługują też połączenia głosowe i wideo.",
    "Add, enable and test connection proxies.": "Dodawaj, włączaj i testuj serwery proxy połączeń.",
    "Privacy": "Prywatność",
    "Allow adding me to groups and channels": "Pozwól dodawać mnie do grup i kanałów",
    "Privacy setting for managing who can add you to groups and channels.": "Ustawienie prywatności określające, kto może dodawać Cię do grup i kanałów.",
    "Your contacts only": "Tylko Twoje kontakty",
    "Allow finding by phone number": "Pozwól wyszukiwać po numerze telefonu",
    "Privacy setting for managing whether you can be found by your phone number.": "Ustawienie prywatności określające, czy można Cię znaleźć po numerze telefonu.",
    "Show link in forwarded messages": "Pokazuj link w przekazanych wiadomościach",
    "Privacy setting for managing whether a link to your account is included in forwarded messages.": "Ustawienie prywatności określające, czy link do Twojego konta jest dołączany do przekazanych wiadomości.",
    "Show phone number": "Pokazuj numer telefonu",
    "Privacy setting for managing whether your phone number is visible.": "Ustawienie prywatności określające, czy Twój numer telefonu jest widoczny.",
    "Show profile photo": "Pokazuj zdjęcie profilowe",
    "Privacy setting for managing whether your profile photo is visible.": "Ustawienie prywatności określające, czy Twoje zdjęcie profilowe jest widoczne.",
    "Show status": "Pokazuj status",
    "Privacy setting for managing whether your online status is visible.": "Ustawienie prywatności określające, czy Twój status online jest widoczny.",
    "Allow sending Location to inline bots": "Pozwól wysyłać lokalizację do botów inline",
    "Some inline bots request location data when using them": "Niektóre boty inline żądają danych o lokalizacji podczas używania",
    "Blocklist": "Lista blokowanych",
    "View": "Wyświetl",
    "Show the list of Telegram users you have blocked.": "Pokaż listę użytkowników Telegrama, których zablokowałeś.",
    "Privacy setting for managing who can call you.": "Ustawienie prywatności określające, kto może do Ciebie dzwonić.",
    "Everybody": "Wszyscy",
    "Nobody": "Nikt",
    "Allow calls": "Zezwalaj na połączenia",
    "This is a Premium-only feature.": "To funkcja dostępna tylko w wersji Premium.",
    "Only selected": "Tylko wybrani",
    "Privacy updated": "Zaktualizowano prywatność",
    "Voice and video messages": "Wiadomości głosowe i wideo",
    "Who can send you voice messages and video notes (round videos). Premium feature.": "Kto może wysyłać Ci wiadomości głosowe i notatki wideo (okrągłe filmy). Funkcja Premium.",
    "Choose who can send you voice messages and video notes.": "Wybierz, kto może wysyłać Ci wiadomości głosowe i notatki wideo.",
    "Choose who cannot send you voice messages and video notes.": "Wybierz, kto nie może wysyłać Ci wiadomości głosowych i notatek wideo.",
    "Everybody except": "Wszyscy oprócz",
    "Sessions": "Sesje",
    "Session was terminated": "Sesja została zakończona",
    "Terminating session": "Kończenie sesji",
    "Terminate Session": "Zakończ sesję",
    "This app": "Ta aplikacja",
    "Active since: %1, last online: %2": "Aktywna od: %1, ostatnio online: %2",
    "1 week": "1 tydzień",
    "1 month": "1 miesiąc",
    "3 months": "3 miesiące",
    "6 months": "6 miesięcy",
    "1 year": "1 rok",
    "Session Timeout": "Limit czasu sesji",
    "Inactive sessions will be terminated after this timeframe": "Nieaktywne sesje zostaną zakończone po tym czasie",
    "Storage": "Pamięć",
    "Enable online-only mode": "Włącz tryb tylko online",
    "Disables offline caching. Certain features may be limited or missing in this mode. Changes require a restart of RooTelegram to take effect.": "Wyłącza buforowanie offline. W tym trybie niektóre funkcje mogą być ograniczone lub niedostępne. Zmiany wymagają ponownego uruchomienia RooTelegram.",
    "Enable storage optimizer": "Włącz optymalizator pamięci",
    "User Profile": "Profil użytkownika",
    "First Name": "Imię",
    "Enter 1-64 characters": "Wpisz od 1 do 64 znaków",
    "Last Name": "Nazwisko",
    "Enter 0-64 characters": "Wpisz od 0 do 64 znaków",
    "Profile Pictures": "Zdjęcia profilowe",
    "Add Picture": "Dodaj zdjęcie",
    "Delete Picture": "Usuń zdjęcie",
    "Deleting profile picture": "Usuwanie zdjęcia profilowego",
    "Log Out": "Wyloguj",
    "Logged out": "Wylogowano",
    "Phone number: +%1": "Numer telefonu: +%1",
    "Go to Channel": "Przejdź do kanału",
    "Go to Message": "Przejdź do wiadomości",
    "Start Bot": "Uruchom bota",
    "Sticker set successfully removed!": "Pomyślnie usunięto zestaw naklejek!",
    "Sticker set successfully installed!": "Pomyślnie zainstalowano zestaw naklejek!",
    "Main": "Główne",
    "No stories from your contacts": "Brak relacji od Twoich kontaktów",
    "Pull down to refresh": "Pociągnij w dół, aby odświeżyć",
    "My Archive": "Moje archiwum",
    "You have no archived stories": "Nie masz zarchiwizowanych relacji",
    "(no caption)": "(brak podpisu)",
    "New story": "Nowa relacja",
    "Delete story": "Usuń relację",
    "Blacklist is empty": "Czarna lista jest pusta",
    "Remove from blacklist": "Usuń z czarnej listy",
    "Add to blacklist": "Dodaj do czarnej listy",
    "Added to blacklist": "Dodano do czarnej listy",
    "Removed from blacklist": "Usunięto z czarnej listy",
    "My Profile": "Mój profil",
    "You have no stories on your profile": "Nie masz relacji na swoim profilu",
    "Archive": "Archiwum",
    "Profile": "Profil",
    "Story": "Relacja",
    "This story type is not supported yet": "Ten typ relacji nie jest jeszcze obsługiwany",
    "Deleting story": "Usuwanie relacji",
    "Could not set reaction.": "Nie udało się ustawić reakcji.",
    "Story not available": "Relacja niedostępna",
    "Audience": "Odbiorcy",
    "Done": "Gotowe",
    "No contacts or private chats.": "Brak kontaktów lub czatów prywatnych.",
    "Custom audience": "Własna grupa odbiorców",
    "Publish": "Opublikuj",
    "Tap to change": "Dotknij, aby zmienić",
    "Caption": "Podpis",
    "Add a caption (optional)": "Dodaj podpis (opcjonalnie)",
    "Reading video…": "Wczytywanie filmu…",
    "Video too long: %1 (max %2)": "Film zbyt długi: %1 (maks. %2)",
    "Duration: %1": "Czas trwania: %1",
    "Cannot determine your account.": "Nie można ustalić Twojego konta.",
    "Posting story…": "Publikowanie relacji…",
    "Video conversion failed.": "Konwersja filmu nie powiodła się.",
    "Story posted": "Opublikowano relację",
    "Could not post story.": "Nie udało się opublikować relacji.",
    "Telegram stories are vertical (9:16). Your landscape video is being adapted before publishing.": "Relacje Telegrama są pionowe (9:16). Twój film poziomy jest dostosowywany przed opublikowaniem.",
    "Converting video": "Konwertowanie filmu",
    "Uploading video": "Przesyłanie filmu",
    "Everyone": "Wszyscy",
    "Selected contacts": "Wybrane kontakty",
    "Choose contacts": "Wybierz kontakty",
    "Allow screenshots": "Zezwalaj na zrzuty ekranu",
    "If off, the story is marked as protected: official clients block screenshots and forwarding.": "Jeśli wyłączone, relacja jest oznaczana jako chroniona: oficjalne klienty blokują zrzuty ekranu i przekazywanie.",
    "Post to my profile": "Opublikuj na moim profilu",
    "Keep the story visible on your profile after the 24h expiration.": "Zachowaj relację widoczną na profilu po wygaśnięciu po 24 godzinach.",
    "Custom audience (%1)": "Własna grupa odbiorców (%1)",
    "Reply sent": "Wysłano odpowiedź",
    "Send": "Wyślij",
    "Reply to %1": "Odpowiedz %1",
    "Reply to story": "Odpowiedz na relację",
    "Reply": "Odpowiedz",
    "Write a reply…": "Napisz odpowiedź…",
    "Viewers": "Wyświetlający",
    "Telegram user": "Użytkownik Telegrama",
    "Forwarded": "Przekazano",
    "Reposted": "Udostępniono ponownie",
    "No viewers yet": "Brak wyświetleń",
    "Banned until %1": "Zbanowany do %1",
    "Banned": "Zbanowany",
    "Unable to load members for this chat.": "Nie można wczytać członków tego czatu.",
    "There are no removed users.": "Brak usuniętych użytkowników.",
    "No administrators found.": "Nie znaleziono administratorów.",
    "Joined %1": "Dołączył %1",
    "Unbanning…": "Odbanowywanie…",
    "Unban": "Odbanuj",
    "User has been unbanned.": "Użytkownik został odbanowany.",
    "Apply now": "Zastosuj teraz",
    "Neon theme": "Motyw Neon",
    "Silica theme": "Motyw Silica",
    "Cyberpunk look": "Wygląd cyberpunk",
    "Base theme": "Motyw podstawowy",
    "Circuit background, neon glow on menus, buttons and titles, rounded avatars and glass cards. Heavier: requires a dark and orange theme for the perfect experience.": "Tło z obwodami, neonowa poświata na menu, przyciskach i tytułach, zaokrąglone awatary i szklane karty. Cięższy: dla najlepszego efektu wymaga ciemnego i pomarańczowego motywu.",
    "Native flat menus, square avatars, no custom background, standard Silica colors. Lighter and clearly readable also on light system themes.": "Natywne płaskie menu, kwadratowe awatary, brak własnego tła, standardowe kolory Silica. Lżejszy i dobrze czytelny także przy jasnych motywach systemowych.",
    "Apply this theme now?": "Zastosować ten motyw teraz?",
    "Copy video to gallery": "Kopiuj film do galerii",
    "A video conversion is already in progress.": "Konwersja filmu jest już w toku.",
    "Video converter not available.": "Konwerter filmów niedostępny.",
    "Source video not found.": "Nie znaleziono filmu źródłowego.",
    "Could not start the video converter.": "Nie udało się uruchomić konwertera filmów.",
    "Record a Voice Note": "Nagraj notatkę głosową",
    "Press the button to start recording": "Naciśnij przycisk, aby rozpocząć nagrywanie",
    "Starting": "Uruchamianie",
    "Recording": "Nagrywanie",
    "Stopping": "Zatrzymywanie",
    "Use recording": "Użyj nagrania",
    "Voice Note (%1)": "Notatka głosowa (%1)",
    "Ready": "Gotowe",
    "Preview not supported for this link...": "Podgląd nie jest obsługiwany dla tego linku...",
    "Continua": "Kontynuuj",
    "Novità": "Nowości",
    "Video: %1": "Film: %1",
    "Picture: %1": "Zdjęcie: %1",
    "Audio: %1": "Audio: %1",
    "Voice Note: %1": "Notatka głosowa: %1",
    "Animation: %1": "Animacja: %1",
    "Document: %1": "Dokument: %1",
    "%1M": "%1 mln",
    "%1K": "%1 tys.",
    "was never online": "nigdy nie był online",
    "last online: last month": "ostatnio online: w zeszłym miesiącu",
    "last online: last week": "ostatnio online: w zeszłym tygodniu",
    "last online: %1": "ostatnio online: %1",
    "online": "online",
    "was recently online": "był ostatnio online",
    "Admin": "Administrator",
    "Creator": "Twórca",
    "Restricted": "Z ograniczeniami",
    "changed the chat title to %1": "zmienił tytuł czatu na %1",
    "sent an anonymous quiz": "wysłał anonimowy quiz",
    "sent an anonymous poll": "wysłał anonimową ankietę",
    "Anonymous Quiz": "Anonimowy quiz",
    "Quiz": "Quiz",
    "Anonymous Poll": "Anonimowa ankieta",
    "Unable to find user %1": "Nie można znaleźć użytkownika %1",
    "You are already a member of this chat.": "Jesteś już członkiem tego czatu.",
    "Closed!": "Zamknięte!",
    "Pending acknowledgement": "Oczekuje na potwierdzenie",
    "created topic: %1": "utworzył temat: %1",
    "renamed topic to: %1": "zmienił nazwę tematu na: %1",
    "edited topic icon": "edytował ikonę tematu",
    "closed topic": "zamknął temat",
    "reopened topic": "ponownie otworzył temat",
    "edited topic": "edytował temat",
    "hid topic": "ukrył temat",
    "unhid topic": "odkrył temat",
    "Send shared content": "Wyślij udostępnioną treść",
    "Unknown caller": "Nieznany dzwoniący",
    "Calling…": "Dzwonienie…",
    "Incoming voice call": "Połączenie głosowe przychodzące",
    "Exchanging encryption keys…": "Wymiana kluczy szyfrowania…",
    "Ending call…": "Kończenie połączenia…",
    "Decline": "Odrzuć",
    "Accept": "Odbierz",
    "Unmute": "Wyłącz wyciszenie",
    "Mute": "Wycisz",
    "End call": "Zakończ połączenie",
    "Call declined": "Odrzucono połączenie",
    "No answer": "Brak odpowiedzi",
    "Missed call": "Nieodebrane połączenie",
    "Call failed": "Połączenie nie powiodło się",
    "Speaker off": "Głośnik wył.",
    "Speaker": "Głośnik",
    "Incoming video call": "Połączenie wideo przychodzące",
    "Video not\navailable": "Wideo\nniedostępne",
}

# Plurali polacchi: 3 forme (one / few / many)
PLN = {
    "%n scheduled message(s)": ("%n zaplanowana wiadomość", "%n zaplanowane wiadomości", "%n zaplanowanych wiadomości"),
    "%n chat(s)": ("%n czat", "%n czaty", "%n czatów"),
    "%1 blocked": ("%1 zablokowany", "%1 zablokowani", "%1 zablokowanych"),
    "%1 subscribers": ("%1 subskrybent", "%1 subskrybenci", "%1 subskrybentów"),
    "%1 members": ("%1 członek", "%1 członkowie", "%1 członków"),
    "%1 online": ("%1 online", "%1 online", "%1 online"),
    "%Ln Messages deleted": ("Usunięto %Ln wiadomość", "Usunięto %Ln wiadomości", "Usunięto %Ln wiadomości"),
    "%Ln messages have been copied": ("Skopiowano %Ln wiadomość", "Skopiowano %Ln wiadomości", "Skopiowano %Ln wiadomości"),
    "Forward %Ln messages": ("Prześlij %Ln wiadomość", "Prześlij %Ln wiadomości", "Prześlij %Ln wiadomości"),
    "%Ln messages selected": ("Zaznaczono %Ln wiadomość", "Zaznaczono %Ln wiadomości", "Zaznaczono %Ln wiadomości"),
    "%Ln join requests": ("%Ln prośba o dołączenie", "%Ln prośby o dołączenie", "%Ln próśb o dołączenie"),
    "chats": ("czat", "czaty", "czatów"),
    "unread messages": ("nieprzeczytana wiadomość", "nieprzeczytane wiadomości", "nieprzeczytanych wiadomości"),
    "Delete %Ln message(s)?": ("Usunąć %Ln wiadomość?", "Usunąć %Ln wiadomości?", "Usunąć %Ln wiadomości?"),
    "%Ln messages of album deleted": ("Usunięto %Ln wiadomość albumu", "Usunięto %Ln wiadomości albumu", "Usunięto %Ln wiadomości albumu"),
    "%n comment(s)": ("%n komentarz", "%n komentarze", "%n komentarzy"),
    "scored %Ln points in %2": ("zdobył %Ln punkt w %2", "zdobył %Ln punkty w %2", "zdobył %Ln punktów w %2"),
    "%Ln%": ("%Ln%", "%Ln%", "%Ln%"),
    "%Ln vote(s) total": ("%Ln głos łącznie", "%Ln głosy łącznie", "%Ln głosów łącznie"),
    "%Ln unread messages": ("%Ln nieprzeczytana wiadomość", "%Ln nieprzeczytane wiadomości", "%Ln nieprzeczytanych wiadomości"),
    "Question (%Ln characters left)": ("Pytanie (pozostał %Ln znak)", "Pytanie (pozostały %Ln znaki)", "Pytanie (pozostało %Ln znaków)"),
    "Answer (%Ln characters left)": ("Odpowiedź (pozostał %Ln znak)", "Odpowiedź (pozostały %Ln znaki)", "Odpowiedź (pozostało %Ln znaków)"),
    "%Ln vote(s)": ("%Ln głos", "%Ln głosy", "%Ln głosów"),
    "%Ln vote(s) including yours": ("%Ln głos wraz z Twoim", "%Ln głosy wraz z Twoim", "%Ln głosów wraz z Twoim"),
    "scored %Ln points": ("zdobył %Ln punkt", "zdobył %Ln punkty", "zdobył %Ln punktów"),
    "On (%n configured)": ("Wł. (%n skonfigurowany)", "Wł. (%n skonfigurowane)", "Wł. (%n skonfigurowanych)"),
    "Off (%n configured)": ("Wył. (%n skonfigurowany)", "Wył. (%n skonfigurowane)", "Wył. (%n skonfigurowanych)"),
    "%1 day(s)": ("%1 dzień", "%1 dni", "%1 dni"),
    "%n new story(es)": ("%n nowa relacja", "%n nowe relacje", "%n nowych relacji"),
    "%n story(es)": ("%n relacja", "%n relacje", "%n relacji"),
    "Choose who will see your next story (%n selected).": ("Wybierz, kto zobaczy Twoją następną relację (%n wybrany).", "Wybierz, kto zobaczy Twoją następną relację (%n wybrani).", "Wybierz, kto zobaczy Twoją następną relację (%n wybranych)."),
    "Members of your custom audience (%n selected). Saved across stories.": ("Członkowie Twojej grupy odbiorców (%n wybrany). Zapisywane między relacjami.", "Członkowie Twojej grupy odbiorców (%n wybrani). Zapisywane między relacjami.", "Członkowie Twojej grupy odbiorców (%n wybranych). Zapisywane między relacjami."),
    "(%n selected)": ("(%n wybrany)", "(%n wybrani)", "(%n wybranych)"),
    "%n contact(s) selected": ("Zaznaczono %n kontakt", "Zaznaczono %n kontakty", "Zaznaczono %n kontaktów"),
    "%n view(s)": ("%n wyświetlenie", "%n wyświetlenia", "%n wyświetleń"),
    "%n reaction(s)": ("%n reakcja", "%n reakcje", "%n reakcji"),
}


def esc(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def repl_message(m: re.Match) -> str:
    block = m.group(0)
    is_plural = 'numerus="yes"' in m.group(1 if False else 0)[:60] or m.group("num") is not None
    raw_src = m.group("src")
    src = html.unescape(raw_src)
    if m.group("num") is not None:
        forms = PLN.get(src)
        if forms is None:
            return block  # lascia unfinished com'è
        nf = "".join(f"<numerusform>{esc(f)}</numerusform>" for f in forms)
        new_tr = f"<translation>{nf}</translation>"
    else:
        tr = PL.get(src)
        if tr is None:
            return block  # lascia unfinished
        new_tr = f"<translation>{esc(tr)}</translation>"
    # sostituisci il blocco <translation ...>...</translation> dentro il message
    return re.sub(r'<translation[^>]*>.*?</translation>', new_tr, block, count=1, flags=re.S)


def main():
    data = EN.read_text(encoding="utf-8")
    data = data.replace('language="en"', 'language="pl"', 1)
    pattern = re.compile(
        r'<message(?P<num> numerus="yes")?>(?P<body>.*?<source>(?P<src>.*?)</source>.*?)</message>',
        re.S,
    )
    out = pattern.sub(repl_message, data)
    OUT.write_text(out, encoding="utf-8")
    # report
    remaining = out.count('type="unfinished"')
    print(f"Scritto {OUT} — unfinished residui: {remaining}")


if __name__ == "__main__":
    main()
