#!/usr/bin/env python3
"""Genera translations/harbour-rootelegram-ru.ts (russo) da -en.ts.

- Singolari: RU[src] = "перевод".
- Plurali Qt (numerus="yes"): RUN[src] = (one, few, many)
  (il russo usa 3 forme: one / few / many, come il polacco).
- Le stringhe non presenti nei dict restano type="unfinished" col sorgente.
"""
from pathlib import Path
import html
import re

EN = Path("translations/harbour-rootelegram-en.ts")
OUT = Path("translations/harbour-rootelegram-ru.ts")

RU = {
    "About RooTelegram": "О RooTelegram",
    "A Telegram client for Sailfish OS": "Клиент Telegram для Sailfish OS",
    "Licensed under GNU GPLv3": "Под лицензией GNU GPLv3",
    "Terms of Service": "Условия использования",
    "Privacy Policy": "Политика конфиденциальности",
    "Credits": "Благодарности",
    "This project uses the Telegram Database Library (TDLib). Thanks for making it available under the conditions of the Boost Software License 1.0!": "Этот проект использует библиотеку Telegram Database Library (TDLib). Спасибо за её предоставление на условиях лицензии Boost Software License 1.0!",
    "Open Telegram Database Library on GitHub": "Открыть Telegram Database Library на GitHub",
    "About Telegram": "О Telegram",
    "This product uses the Telegram API but is not endorsed or certified by Telegram.": "Этот продукт использует Telegram API, но не одобрен и не сертифицирован Telegram.",
    "TDLib version %1": "TDLib версия %1",
    "This project uses rlottie. Copyright 2020 Samsung Electronics Co., Ltd. and other contributors. Thanks for making it available under the conditions of the MIT License!": "Этот проект использует rlottie. Copyright 2020 Samsung Electronics Co., Ltd. и другие участники. Спасибо за её предоставление на условиях лицензии MIT!",
    "Open rlottie on GitHub": "Открыть rlottie на GitHub",
    "This project uses OpenStreetMap Nominatim for reverse geocoding of location attachments. Thanks for making it available as web service!": "Этот проект использует OpenStreetMap Nominatim для обратного геокодирования вложений с местоположением. Спасибо за предоставление этого веб-сервиса!",
    "Open OSM Nominatim Wiki": "Открыть вики OSM Nominatim",
    "Fernschreiber": "Fernschreiber",
    "Yottagram": "Yottagram",
    "Source code on GitHub": "Исходный код на GitHub",
    "Fork by RootGPT - based on Fernschreiber by Sebastian J. Wolf and Yottagram by Michal Szczepaniak.": "Форк от RootGPT — на основе Fernschreiber от Sebastian J. Wolf и Yottagram от Michal Szczepaniak.",
    "This project uses Twemoji (jdecked fork). Copyright the Twemoji contributors. Thanks for making it available under the conditions of the MIT License (coding) and CC-BY 4.0 (graphics)!": "Этот проект использует Twemoji (форк jdecked). Copyright участники Twemoji. Спасибо за предоставление на условиях лицензии MIT (код) и CC-BY 4.0 (графика)!",
    "Open Twemoji on GitHub": "Открыть Twemoji на GitHub",
    "This project bundles FFmpeg, built with libx264, to normalize videos before upload. Thanks for making it available under the conditions of the LGPL v2.1+ / GPL v2+ (libx264)!": "Этот проект включает FFmpeg, собранный с libx264, для нормализации видео перед загрузкой. Спасибо за предоставление на условиях LGPL v2.1+ / GPL v2+ (libx264)!",
    "Open FFmpeg website": "Открыть сайт FFmpeg",
    "This project uses tgcalls and tg_owt (WebRTC) for voice and video calls. Thanks for making them available under the conditions of the GPL v2+!": "Этот проект использует tgcalls и tg_owt (WebRTC) для голосовых и видеозвонков. Спасибо за их предоставление на условиях GPL v2+!",
    "Open tgcalls on GitHub": "Открыть tgcalls на GitHub",
    "For SailfishOS 5.0/5.1 compatibility this package also bundles FFmpeg's multimedia dependencies: libvpx, Opus, Ogg, Vorbis, Theora, Speex, WebP, libsharpyuv (BSD) and OpenJPEG (BSD-2). Copyright their respective contributors. The full license texts are shipped in /usr/share/harbour-rootelegram/licenses/.": "Для совместимости с SailfishOS 5.0/5.1 этот пакет также включает мультимедийные зависимости FFmpeg: libvpx, Opus, Ogg, Vorbis, Theora, Speex, WebP, libsharpyuv (BSD) и OpenJPEG (BSD-2). Copyright соответствующие участники. Полные тексты лицензий находятся в /usr/share/harbour-rootelegram/licenses/.",
    "Refresh": "Обновить",
    "Add Members": "Добавить участников",
    "Search a contact...": "Поиск контакта...",
    "No contacts found.": "Контакты не найдены.",
    "You don't have any contacts.": "У вас нет контактов.",
    "Added": "Добавлено",
    "Adding…": "Добавление…",
    "Loading contacts...": "Загрузка контактов...",
    "Member added.": "Участник добавлен.",
    "Proxy added and enabled": "Прокси добавлен и включён",
    "Add proxy": "Добавить прокси",
    "Add": "Добавить",
    "Paste a proxy link (optional)": "Вставьте ссылку прокси (необязательно)",
    "tg://proxy?server=…  or  https://t.me/proxy?…": "tg://proxy?server=…  или  https://t.me/proxy?…",
    "Link recognised": "Ссылка распознана",
    "Type": "Тип",
    "MTProto (recommended)": "MTProto (рекомендуется)",
    "SOCKS5 (also for calls)": "SOCKS5 (также для звонков)",
    "HTTP": "HTTP",
    "Server": "Сервер",
    "Server (host or IP)": "Сервер (хост или IP)",
    "Port": "Порт",
    "Secret": "Секрет",
    "Secret (supports dd… and ee… Fake-TLS)": "Секрет (поддерживает dd… и ee… Fake-TLS)",
    "Username (optional)": "Имя пользователя (необязательно)",
    "Username": "Имя пользователя",
    "Password (optional)": "Пароль (необязательно)",
    "Password": "Пароль",
    "HTTP only": "Только HTTP",
    "The proxy supports only HTTP requests (no HTTPS tunnelling).": "Прокси поддерживает только HTTP-запросы (без туннелирования HTTPS).",
    "Add to folder": "Добавить в папку",
    "Added to folder: %1": "Добавлено в папку: %1",
    "No folders": "Нет папок",
    "Photo": "Фото",
    "Video": "Видео",
    "Document": "Документ",
    "Voice": "Голос",
    "GIF": "GIF",
    "Sticker": "Стикер",
    "Location": "Местоположение",
    "Unknown chat": "Неизвестный чат",
    "Scheduled messages": "Отложенные сообщения",
    "Loading…": "Загрузка…",
    "No scheduled messages": "Нет отложенных сообщений",
    "Long-press the send button in a chat to schedule a new message.": "Удерживайте кнопку отправки в чате, чтобы запланировать новое сообщение.",
    "Deleting": "Удаление",
    "Reschedule": "Перенести",
    "Delete": "Удалить",
    "Voice message": "Голосовое сообщение",
    "Video message": "Видеосообщение",
    "Audio": "Аудио",
    "Contact": "Контакт",
    "Poll": "Опрос",
    "Call": "Звонок",
    "Archived chats": "Архив чатов",
    "Unknown": "Неизвестно",
    "Unarchive": "Разархивировать",
    "No archived chats": "Нет архивированных чатов",
    "Long-press a chat in the main list and choose Archive.": "Удерживайте чат в главном списке и выберите «Архивировать».",
    "%1 %": "%1 %",
    "%1": "%1",
    "Blacklist": "Чёрный список",
    "No blocked users.": "Нет заблокированных пользователей.",
    "Block a user from their profile to see them here.": "Заблокируйте пользователя в его профиле, чтобы увидеть его здесь.",
    "Unblocking…": "Разблокировка…",
    "Unblock": "Разблокировать",
    "Load more": "Загрузить ещё",
    "Loading blocked users...": "Загрузка заблокированных пользователей...",
    "User has been unblocked.": "Пользователь разблокирован.",
    "Theme cleared": "Тема сброшена",
    "Theme set: %1": "Тема установлена: %1",
    "Appearance": "Внешний вид",
    "Pick a chat theme. The selected preset is applied to every member viewing this channel.": "Выберите тему чата. Выбранный пресет применяется ко всем, кто просматривает этот канал.",
    "Default (no theme)": "По умолчанию (без темы)",
    "No themes available yet": "Темы пока недоступны",
    "Themes are pushed by Telegram after sign-in. Try again in a moment.": "Темы загружаются Telegram после входа. Повторите попытку через мгновение.",
    "Folder created.": "Папка создана.",
    "Unable to create folder %1": "Не удалось создать папку %1",
    "Unable to update folder order.": "Не удалось обновить порядок папок.",
    "Edit folders": "Изменить папки",
    "All": "Все",
    "Custom folders": "Пользовательские папки",
    "Create new folder": "Создать новую папку",
    "Folder name": "Имя папки",
    "Enter the folder name": "Введите имя папки",
    "Create folder": "Создать папку",
    "Deleting folder": "Удаление папки",
    "Folder deleted.": "Папка удалена.",
    "Unable to delete folder %1": "Не удалось удалить папку %1",
    "Unable to delete folder.": "Не удалось удалить папку.",
    "Folder name must be at most 12 characters.": "Имя папки должно содержать не более 12 символов.",
    "Unable to create folder %1: %2": "Не удалось создать папку %1: %2",
    "Unable to create folder.": "Не удалось создать папку.",
    "Creating folder...": "Создание папки...",
    "Retrying creation...": "Повторная попытка создания...",
    "Error creating folder: %1": "Ошибка создания папки: %1",
    "Internal error while creating folder.": "Внутренняя ошибка при создании папки.",
    "Leave Chat": "Покинуть чат",
    "Join Chat": "Присоединиться к чату",
    "Leaving chat": "Выход из чата",
    "Chat Title": "Название чата",
    "Enter 1-128 characters": "Введите от 1 до 128 символов",
    "There is no information text available, yet.": "Информационный текст пока недоступен.",
    "Info": "Информация",
    "Phone Number": "Номер телефона",
    "The Invite Link has been copied to the clipboard.": "Ссылка-приглашение скопирована в буфер обмена.",
    "%1, %2": "%1, %2",
    "New Secret Chat": "Новый секретный чат",
    "Unmute Chat": "Включить уведомления чата",
    "Mute Chat": "Отключить уведомления чата",
    "ID has been copied to the clipboard.": "ID скопирован в буфер обмена.",
    "Join Requests": "Запросы на вступление",
    "Unable to start the call.": "Не удалось начать звонок.",
    "Public": "Публичный",
    "Private": "Приватный",
    "Visible": "Видимый",
    "Hidden": "Скрытый",
    "Off": "Выкл.",
    "On": "Вкл.",
    "%1 selected": "Выбрано: %1",
    "None": "Нет",
    "No": "Нет",
    "Default": "По умолчанию",
    "Available": "Доступно",
    "Unavailable": "Недоступно",
    "%1 is not available yet.": "%1 пока недоступен.",
    "No invite link available yet.": "Ссылка-приглашение пока недоступна.",
    "Deleting channel": "Удаление канала",
    "Channel Settings": "Настройки канала",
    "Group Settings": "Настройки группы",
    "Channel Type": "Тип канала",
    "Group Type": "Тип группы",
    "Chat History": "История чата",
    "Only administrators can change chat history visibility.": "Только администраторы могут изменять видимость истории чата.",
    "Topics": "Темы",
    "Discussion": "Обсуждение",
    "Direct Messages": "Личные сообщения",
    "Auto-Translate Messages": "Автоперевод сообщений",
    "Reactions": "Реакции",
    "Permissions": "Разрешения",
    "Invite Link": "Ссылка-приглашение",
    "Administrators": "Администраторы",
    "Subscribers": "Подписчики",
    "Members": "Участники",
    "Removed Users": "Удалённые пользователи",
    "Statistics": "Статистика",
    "Statistics are unavailable for this chat.": "Статистика недоступна для этого чата.",
    "Recent Actions": "Недавние действия",
    "Affiliate Programs": "Партнёрские программы",
    "Delete channel": "Удалить канал",
    "Delete and leave group": "Удалить и покинуть группу",
    "Reactions can only be changed in supergroups and channels.": "Реакции можно изменять только в супергруппах и каналах.",
    "Only administrators can change reactions.": "Только администраторы могут изменять реакции.",
    "Topics enabled.": "Темы включены.",
    "Topics disabled.": "Темы отключены.",
    "All reactions enabled.": "Все реакции включены.",
    "Reactions disabled.": "Реакции отключены.",
    "Basic groups are private.": "Базовые группы приватны.",
    "Only administrators can change the group type.": "Только администраторы могут изменять тип группы.",
    "Only the group owner can change topics.": "Только владелец группы может изменять темы.",
    "Chat history is now visible.": "История чата теперь видна.",
    "Chat history is now hidden.": "История чата теперь скрыта.",
    "Message history can't be hidden while topics are enabled.": "Историю сообщений нельзя скрыть, пока включены темы.",
    "Manage Topics": "Управление темами",
    "Only administrators can manage topics.": "Только администраторы могут управлять темами.",
    "Only administrators can change the group picture.": "Только администраторы могут изменять изображение группы.",
    "Uploading group picture...": "Загрузка изображения группы...",
    "Group picture updated.": "Изображение группы обновлено.",
    "Channel Picture": "Изображение канала",
    "Group Picture": "Изображение группы",
    "Only the channel owner can change the discussion group.": "Только владелец канала может изменять группу обсуждения.",
    "Only administrators can change the appearance.": "Только администраторы могут изменять внешний вид.",
    "Convert to supergroup": "Преобразовать в супергруппу",
    "Converting to supergroup": "Преобразование в супергруппу",
    "Conversion in progress…": "Идёт преобразование…",
    "User has been blocked.": "Пользователь заблокирован.",
    "Unblock User": "Разблокировать пользователя",
    "Block User": "Заблокировать пользователя",
    "Unable to load content.": "Не удалось загрузить содержимое.",
    "Loading common chats…": "Загрузка общих чатов…",
    "Loading group members…": "Загрузка участников группы…",
    "You": "Вы",
    "You don't have any groups in common with this user.": "У вас нет общих групп с этим пользователем.",
    "This group is empty.": "Эта группа пуста.",
    "Channel members are anonymous.": "Участники канала анонимны.",
    "Processing…": "Обработка…",
    "Promote to Admin": "Назначить администратором",
    "Remove Admin": "Снять администратора",
    "Removing Admin": "Снятие администратора",
    "Admin demoted to member.": "Администратор понижен до участника.",
    "Remove from group": "Удалить из группы",
    "Removing user": "Удаление пользователя",
    "Member removed from group.": "Участник удалён из группы.",
    "Member promoted to Admin.": "Участник назначен администратором.",
    "Groups": "Группы",
    "Settings": "Настройки",
    "Voice calls are not available in this build yet.": "Голосовые звонки пока недоступны в этой сборке.",
    "Media": "Медиа",
    "No media available.": "Медиа недоступны.",
    "Documents": "Документы",
    "No documents available.": "Документы недоступны.",
    "Link": "Ссылка",
    "No links available.": "Ссылки недоступны.",
    "No audio available.": "Аудио недоступно.",
    "Video call": "Видеозвонок",
    "Video calls are not available in this build yet.": "Видеозвонки пока недоступны в этой сборке.",
    "Search requests": "Поиск запросов",
    "There are no pending join requests.": "Нет ожидающих запросов на вступление.",
    "No bio": "Нет описания",
    "Requested %1": "Запрошено %1",
    "Approving…": "Одобрение…",
    "Approve": "Одобрить",
    "Rejecting…": "Отклонение…",
    "Reject": "Отклонить",
    "User Info": "Информация о пользователе",
    "Group Info": "Информация о группе",
    "Mark all messages as read": "Отметить все сообщения как прочитанные",
    "No message in this chat.": "В этом чате нет сообщений.",
    "Mark chat as unread": "Отметить чат как непрочитанный",
    "Mark chat as read": "Отметить чат как прочитанный",
    "Draft": "Черновик",
    "Unpin chat": "Открепить чат",
    "Pin chat": "Закрепить чат",
    "Unmute chat": "Включить уведомления чата",
    "Mute chat": "Отключить уведомления чата",
    "Delete Chat": "Удалить чат",
    "Deleting chat": "Удаление чата",
    "Add to folder...": "Добавить в папку...",
    "Remove from folder: %1": "Удалить из папки: %1",
    "Removed from folder: %1": "Удалено из папки: %1",
    "Archive chat": "Архивировать чат",
    "Your message": "Ваше сообщение",
    "Loading messages...": "Загрузка сообщений...",
    "Edit Message": "Изменить сообщение",
    "edited": "изменено",
    "Uploading...": "Загрузка...",
    "This chat is empty.": "Этот чат пуст.",
    "You joined the chat %1": "Вы присоединились к чату %1",
    "Select Messages": "Выбрать сообщения",
    "This secret chat is not yet ready. Your chat partner needs to go online first.": "Этот секретный чат ещё не готов. Сначала ваш собеседник должен выйти в сеть.",
    "Closing chat": "Закрытие чата",
    "Close Chat": "Закрыть чат",
    "Search in Chat": "Поиск в чате",
    "Search in chat...": "Поиск в чате...",
    "Location: Obtaining position...": "Местоположение: определение позиции...",
    "Location (%1/%2)": "Местоположение (%1/%2)",
    "Copy Message to Clipboard": "Копировать сообщение",
    "Message unpinned": "Сообщение откреплено",
    "Unpin Message": "Открепить сообщение",
    "Pin Message": "Закрепить сообщение",
    "Additional Options": "Дополнительные параметры",
    "Unknown address": "Неизвестный адрес",
    "Accuracy: %1m": "Точность: %1 м",
    "Sponsored Message": "Рекламное сообщение",
    "Deleted User": "Удалённый пользователь",
    "Double-tap on a message to choose a reaction": "Дважды коснитесь сообщения, чтобы выбрать реакцию",
    "Forward message": "Переслать сообщение",
    "Delete message": "Удалить сообщение",
    "Topic is closed": "Тема закрыта",
    "Copy Selected Text": "Копировать выделенный текст",
    "Quote Selected Text": "Цитировать выделенный текст",
    "Premium set": "Набор Premium",
    "No premium emoji set available": "Нет доступного набора эмодзи Premium",
    "Only the first shared file has been prepared.": "Подготовлен только первый отправленный файл.",
    "Unable to send this sticker.": "Не удалось отправить этот стикер.",
    "Telegram allows up to %1 images per album.": "Telegram разрешает до %1 изображений в альбоме.",
    "Scheduled for %1": "Запланировано на %1",
    "Recent": "Недавние",
    "Sticker set": "Набор стикеров",
    "No recent stickers": "Нет недавних стикеров",
    "No stickers in this set": "В этом наборе нет стикеров",
    'Do you want to delete "%1"?': "Вы хотите удалить «%1»?",
    "Do you want to delete this set?": "Вы хотите удалить этот набор?",
    'Deleting "%1"': "Удаление «%1»",
    "Deleting set": "Удаление набора",
    "Yes": "Да",
    "Type your message first, then tap this button to translate it to English!": "Сначала введите сообщение, затем нажмите эту кнопку, чтобы перевести его на английский!",
    "RooTelegram couldn't detect the language of the text — maybe you wrote a multilingual message?": "RooTelegram не смог определить язык текста — возможно, вы написали многоязычное сообщение?",
    "Selected text copied to clipboard": "Выделенный текст скопирован в буфер обмена",
    "Code copied to clipboard": "Код скопирован в буфер обмена",
    "is recording a voice message": "записывает голосовое сообщение",
    "is recording a video message": "записывает видеосообщение",
    "is recording a video": "записывает видео",
    "is sending a voice message": "отправляет голосовое сообщение",
    "is sending a video message": "отправляет видеосообщение",
    "is sending a video": "отправляет видео",
    "is sending a photo": "отправляет фото",
    "is sending a file": "отправляет файл",
    "is choosing a sticker": "выбирает стикер",
    "is choosing a location": "выбирает местоположение",
    "is choosing a contact": "выбирает контакт",
    "is typing…": "печатает…",
    "Unknown user": "Неизвестный пользователь",
    "edited a message": "изменил сообщение",
    "deleted a message": "удалил сообщение",
    "pinned a message": "закрепил сообщение",
    "joined the chat": "присоединился к чату",
    "joined via invite link": "присоединился по ссылке-приглашению",
    "left the chat": "покинул чат",
    "invited a member": "пригласил участника",
    "updated administrator rights": "обновил права администратора",
    "updated member permissions": "обновил разрешения участника",
    "changed the chat title": "изменил название чата",
    "changed the description": "изменил описание",
    "changed the public username": "изменил публичное имя пользователя",
    "changed the photo": "изменил фото",
    "changed invite link permissions": "изменил разрешения ссылки-приглашения",
    "changed message signing": "изменил подписывание сообщений",
    "changed sticker set": "изменил набор стикеров",
    "changed linked chat": "изменил связанный чат",
    "changed slow mode": "изменил медленный режим",
    "started a video chat": "начал видеочат",
    "ended the video chat": "завершил видеочат",
    "changed video chat permissions": "изменил разрешения видеочата",
    "edited an invite link": "изменил ссылку-приглашение",
    "revoked an invite link": "отозвал ссылку-приглашение",
    "deleted an invite link": "удалил ссылку-приглашение",
    "performed an action": "выполнил действие",
    "Description cleared": "Описание очищено",
    "Username removed": "Имя пользователя удалено",
    "Slow mode: %1s": "Медленный режим: %1 с",
    "Slow mode disabled": "Медленный режим отключён",
    "Linked chat removed": "Связанный чат удалён",
    "No recent actions found.": "Недавние действия не найдены.",
    "Select Chat": "Выбрать чат",
    "You don't have any chats yet.": "У вас пока нет чатов.",
    "Search in contacts...": "Поиск в контактах...",
    "Send contact": "Отправить контакт",
    "Search contact": "Поиск контакта",
    "No contacts with a phone number": "Нет контактов с номером телефона",
    "Could not synchronize your contacts with Telegram.": "Не удалось синхронизировать контакты с Telegram.",
    "in": "в",
    "Waiting for network...": "Ожидание сети...",
    "Connecting to network...": "Подключение к сети...",
    "Connecting to proxy...": "Подключение к прокси...",
    "Connected": "Подключено",
    "Updating content...": "Обновление содержимого...",
    "New Channel": "Новый канал",
    "New Group": "Новая группа",
    "Cancel": "Отмена",
    "Delete for everyone": "Удалить у всех",
    "Delete for me": "Удалить у меня",
    "Group Member Permissions": "Разрешения участников группы",
    "Send Messages": "Отправка сообщений",
    "Send Media Messages": "Отправка медиа",
    "Send Other Messages": "Отправка других сообщений",
    "Add Web Page Previews": "Добавление превью веб-страниц",
    "Change Chat Info": "Изменение информации о чате",
    "Invite Users": "Приглашение пользователей",
    "Pin Messages": "Закрепление сообщений",
    "New Members": "Новые участники",
    "New members can see older messages": "Новые участники видят старые сообщения",
    "Send Polls": "Отправка опросов",
    "Create Topics": "Создание тем",
    "Group permissions updated.": "Разрешения группы обновлены.",
    "Some permission changes were rejected by Telegram.": "Часть изменений разрешений отклонена Telegram.",
    "Slow Mode": "Медленный режим",
    "Set how long every chat member has to wait between Messages": "Задайте, сколько каждый участник чата должен ждать между сообщениями",
    "Search emoji": "Поиск эмодзи",
    "No results": "Нет результатов",
    "No emoji": "Нет эмодзи",
    "Loading topics...": "Загрузка тем...",
    "No topics found": "Темы не найдены",
    "This group has no topics yet.": "В этой группе пока нет тем.",
    "Topic name must be between 1 and 128 characters.": "Имя темы должно содержать от 1 до 128 символов.",
    "Create Topic": "Создать тему",
    "Disable Topics": "Отключить темы",
    "Topic created.": "Тема создана.",
    "Topic renamed.": "Тема переименована.",
    "Topic deleted.": "Тема удалена.",
    "Topic closed.": "Тема закрыта.",
    "Topic reopened.": "Тема снова открыта.",
    "Topic name": "Имя темы",
    "New topic name": "Новое имя темы",
    "Enter topic name": "Введите имя темы",
    "Saving…": "Сохранение…",
    "Create": "Создать",
    "Rename": "Переименовать",
    "Rename topic": "Переименовать тему",
    "Reopen topic": "Снова открыть тему",
    "Close topic": "Закрыть тему",
    "Delete topic": "Удалить тему",
    "Deleting topic": "Удаление темы",
    "Closed": "Закрыта",
    "You don't have permission to create topics.": "У вас нет разрешения на создание тем.",
    "Saved %1": "Сохранено %1",
    "Save failed.": "Не удалось сохранить.",
    "Username must be 5-32 characters.": "Имя пользователя должно содержать от 5 до 32 символов.",
    "Username can only use letters, numbers and underscores.": "Имя пользователя может содержать только буквы, цифры и подчёркивания.",
    "Save": "Сохранить",
    "Public Channel": "Публичный канал",
    "Public Group": "Публичная группа",
    "Public chats can be found via username.": "Публичные чаты можно найти по имени пользователя.",
    "Private chats can only be joined through invite links.": "К приватным чатам можно присоединиться только по ссылкам-приглашениям.",
    "Set public username": "Задать публичное имя пользователя",
    "Use 5-32 letters, numbers or underscores.": "Используйте от 5 до 32 букв, цифр или подчёркиваний.",
    "Approve new members": "Одобрять новых участников",
    "New members must be approved by an administrator.": "Новые участники должны быть одобрены администратором.",
    "Forbid content saving": "Запретить сохранение содержимого",
    "Prevents forwarding, copying and saving of chat contents.": "Запрещает пересылку, копирование и сохранение содержимого чата.",
    "Options saved": "Параметры сохранены",
    "Download Picture": "Скачать изображение",
    "Download of %1 successful.": "Загрузка %1 выполнена успешно.",
    "Download failed.": "Не удалось скачать.",
    "This message was deleted": "Это сообщение было удалено",
    "OK": "ОК",
    "Welcome to RooTelegram!": "Добро пожаловать в RooTelegram!",
    "Please enter your phone number to continue.": "Введите номер телефона, чтобы продолжить.",
    "Continue": "Продолжить",
    "Please enter the code that you received:": "Введите полученный код:",
    "Loading...": "Загрузка...",
    "Unable to authenticate you with the entered code.": "Не удалось выполнить вход с введённым кодом.",
    "Enter code again": "Введите код заново",
    "Restart authentication": "Перезапустить аутентификацию",
    "Please enter your password:": "Введите ваш пароль:",
    "User Registration": "Регистрация пользователя",
    "Enter your First Name": "Введите ваше имя",
    "Enter your Last Name": "Введите вашу фамилию",
    "Register User": "Зарегистрировать пользователя",
    "Use the international format, e.g. %1": "Используйте международный формат, например %1",
    "Transcribe": "Расшифровать",
    "Play/Pause": "Воспроизвести/пауза",
    "Contact saved to address book": "Контакт сохранён в адресную книгу",
    "Could not save the contact": "Не удалось сохранить контакт",
    "Message": "Написать",
    "Add to contacts": "Добавить в контакты",
    "When the recipient comes online": "Когда получатель будет в сети",
    "Message info": "Информация о сообщении",
    "Sent": "Отправлено",
    "Edited": "Изменено",
    "Scheduled": "Запланировано",
    "Sender": "Отправитель",
    "Author signature": "Подпись автора",
    "Via bot": "Через бота",
    "Forwarded from": "Переслано от",
    "Original date": "Исходная дата",
    "Views": "Просмотры",
    "Forwards": "Пересылки",
    "Message ID": "ID сообщения",
    "Album ID": "ID альбома",
    "Reply to Message": "Ответить на сообщение",
    "Forwarded Message": "Пересланное сообщение",
    "Select Message": "Выбрать сообщение",
    "More Options...": "Больше параметров...",
    "Message deleted": "Сообщение удалено",
    "Delete all messages from %1": "Удалить все сообщения от %1",
    "Delete all messages from this user": "Удалить все сообщения этого пользователя",
    "Ban %1": "Забанить %1",
    "Ban user": "Забанить пользователя",
    "Report as spam": "Пожаловаться на спам",
    "Deletion of messages started": "Начато удаление сообщений",
    "User banned": "Пользователь забанен",
    "Report submitted": "Жалоба отправлена",
    "Delete album": "Удалить альбом",
    "Hide spoiler": "Скрыть спойлер",
    "Reveal spoiler": "Показать спойлер",
    "In reply to a story": "В ответ на историю",
    "Translate message": "Перевести сообщение",
    "Someone": "Кто-то",
    "This message was forwarded. Original author: %1": "Это сообщение было переслано. Исходный автор: %1",
    "Close Poll": "Закрыть опрос",
    "Reset Answer": "Сбросить ответ",
    "Final Result:": "Итоговый результат:",
    "Multiple Answers are allowed.": "Разрешено несколько ответов.",
    "via %1": "через %1",
    "Seen by": "Просмотрено",
    "No views": "Нет просмотров",
    "Voice Note": "Голосовая заметка",
    "Your Contacts": "Ваши контакты",
    "Private Chat": "Приватный чат",
    "Secret Chat": "Секретный чат",
    "End-to-end-encrypted, accessible on this device only": "Сквозное шифрование, доступно только на этом устройстве",
    "Transport-encrypted, uses Telegram Cloud, sharable across devices": "Шифрование при передаче, использует облако Telegram, доступно на нескольких устройствах",
    "Synchronize Contacts with Telegram": "Синхронизировать контакты с Telegram",
    "Contacts successfully synchronized with Telegram.": "Контакты успешно синхронизированы с Telegram.",
    "posted a new story": "опубликовал новую историю",
    "reacted to your message": "отреагировал на ваше сообщение",
    "reacted %1 to your message": "отреагировал %1 на ваше сообщение",
    "My chats": "Мои чаты",
    "Global results": "Глобальные результаты",
    "User": "Пользователь",
    "Group": "Группа",
    "Channel": "Канал",
    "No public users, groups or channels found.": "Публичные пользователи, группы или каналы не найдены.",
    "Loading chat list...": "Загрузка списка чатов...",
    "New Chat": "Новый чат",
    "Tap on the title bar to filter your chats": "Коснитесь строки заголовка, чтобы отфильтровать чаты",
    "No matching chats found.": "Подходящие чаты не найдены.",
    "You can search public chats or create a new chat via the pull-down menu.": "Вы можете искать публичные чаты или создать новый чат через выпадающее меню.",
    "Logging out": "Выход",
    "Unable to open link.": "Не удалось открыть ссылку.",
    "All chats marked as read.": "Все чаты отмечены как прочитанные.",
    "Mark all as read": "Отметить все как прочитанные",
    "Search chat...": "Поиск чата...",
    "Stories": "Истории",
    "Reorder Pinned Chats": "Изменить порядок закреплённых чатов",
    "Debug": "Отладка",
    "Search...": "Поиск...",
    "Pin": "Закрепить",
    "Pin message": "Закрепить сообщение",
    "Choose where to pin this message in the chat with %1.": "Выберите, где закрепить это сообщение в чате с %1.",
    "Choose where to pin this message.": "Выберите, где закрепить это сообщение.",
    "Pin for": "Закрепить для",
    "Both users": "Обоих пользователей",
    "Only me": "Только меня",
    "Pinned Message": "Закреплённое сообщение",
    "All answers have to contain 1-100 characters.": "Каждый ответ должен содержать от 1 до 100 символов.",
    "To send a quiz, you have to specify the right answer.": "Чтобы отправить викторину, нужно указать правильный ответ.",
    "You have to enter a question.": "Необходимо ввести вопрос.",
    "The question has to be shorter than 256 characters.": "Вопрос должен быть короче 256 символов.",
    "A poll requires 2-10 answers.": "Опрос требует от 2 до 10 ответов.",
    "Create a Poll": "Создать опрос",
    "in %1": "в %1",
    "Enter your question here": "Введите здесь ваш вопрос",
    "Answers": "Ответы",
    "Enter an answer here": "Введите здесь ответ",
    "Add an answer": "Добавить ответ",
    "Poll Options": "Параметры опроса",
    "Anonymous answers": "Анонимные ответы",
    "Multiple answers allowed": "Разрешено несколько ответов",
    "Quiz Mode": "Режим викторины",
    "Quizzes have one correct answer. Participants can't revoke their responses.": "В викторинах один правильный ответ. Участники не могут отозвать свои ответы.",
    "Enter an optional explanation": "Введите необязательное пояснение",
    "Shown when the user selects a wrong answer.": "Показывается, когда пользователь выбирает неверный ответ.",
    "An explanation can be up to 200 characters long.": "Пояснение может содержать до 200 символов.",
    "Quiz Results": "Результаты викторины",
    "Poll Results": "Результаты опроса",
    "Question": "Вопрос",
    "Results": "Результаты",
    "Chosen by:": "Выбрали:",
    "Promote": "Повысить",
    "Promote %1 to Admin": "Назначить %1 администратором",
    "Custom title (max 16 characters)": "Произвольное звание (макс. 16 символов)",
    "e.g. Moderator": "напр. Модератор",
    "Privileges": "Привилегии",
    "Manage chat": "Управлять чатом",
    "View admin log and chat statistics.": "Просмотр журнала администратора и статистики чата.",
    "Change group info": "Изменять информацию о группе",
    "Title, photo and description.": "Название, фото и описание.",
    "Delete messages": "Удалять сообщения",
    "Ban users": "Банить пользователей",
    "Invite users": "Приглашать пользователей",
    "Pin messages": "Закреплять сообщения",
    "Manage topics": "Управлять темами",
    "Manage video chats": "Управлять видеочатами",
    "Post messages": "Публиковать сообщения",
    "Edit messages of others": "Изменять сообщения других",
    "Post stories": "Публиковать истории",
    "Edit stories": "Изменять истории",
    "Delete stories": "Удалять истории",
    "Add new admins": "Добавлять новых администраторов",
    "With the rights this user already has.": "С правами, которые уже есть у этого пользователя.",
    "Anonymous": "Анонимно",
    "Send messages as the group itself.": "Отправлять сообщения от имени самой группы.",
    "MTProto": "MTProto",
    "SOCKS5": "SOCKS5",
    "%1 ms": "%1 мс",
    "Proxy": "Прокси",
    "Disable proxy (direct connection)": "Отключить прокси (прямое подключение)",
    "Proxy disabled": "Прокси отключён",
    "No proxies": "Нет прокси",
    "Pull down to add a proxy, or paste a tg://proxy link.": "Потяните вниз, чтобы добавить прокси, или вставьте ссылку tg://proxy.",
    "Disable": "Отключить",
    "Enable": "Включить",
    "Test connection": "Проверить подключение",
    "Remove": "Удалить",
    "Removing proxy": "Удаление прокси",
    "Unable to update pinned chat order.": "Не удалось обновить порядок закреплённых чатов.",
    "No pinned chats.": "Нет закреплённых чатов.",
    "Pin a chat from home to reorder it here.": "Закрепите чат на главном экране, чтобы изменить его порядок здесь.",
    "sent a picture": "отправил изображение",
    "sent a video": "отправил видео",
    "sent an animation": "отправил анимацию",
    "sent a voice note": "отправил голосовую заметку",
    "sent a document": "отправил документ",
    "sent a location": "отправил местоположение",
    "have registered with Telegram": "зарегистрировались в Telegram",
    "has registered with Telegram": "зарегистрировался в Telegram",
    "joined this chat": "присоединился к этому чату",
    "were added to this chat": "были добавлены в этот чат",
    "was added to this chat": "был добавлен в этот чат",
    "left this chat": "покинул этот чат",
    "sent a venue": "отправил место",
    "sent a poll": "отправил опрос",
    "sent a quiz": "отправил викторину",
    "created this group": "создал эту группу",
    "changed the chat photo": "изменил фото чата",
    "deleted the chat photo": "удалил фото чата",
    "changed the secret chat TTL setting": "изменил настройку TTL секретного чата",
    "upgraded this group to a supergroup": "преобразовал эту группу в супергруппу",
    "changed the pinned message": "изменил закреплённое сообщение",
    "created a screenshot in this chat": "сделал снимок экрана в этом чате",
    "sent an unsupported message": "отправил неподдерживаемое сообщение",
    "sent an unsupported message: %1": "отправил неподдерживаемое сообщение: %1",
    "sent a self-destructing photo that is expired": "отправил самоуничтожающееся фото, срок которого истёк",
    "sent a self-destructing video that is expired": "отправил самоуничтожающееся видео, срок которого истёк",
    "sent an audio": "отправил аудио",
    "has added %1 to the chat": "добавил %1 в чат",
    "has removed %1 from the chat": "удалил %1 из чата",
    "have added %1 to the chat": "добавили %1 в чат",
    "have removed %1 from the chat": "удалили %1 из чата",
    "sent a game": "отправил игру",
    "sent a video note": "отправил видеозаметку",
    "cancelled a call": "отменил звонок",
    "missed a call": "пропустил звонок",
    "started a call": "начал звонок",
    "sent a contact": "отправил контакт",
    "scheduled a video chat": "запланировал видеочат",
    "invited participants to the video chat": "пригласил участников в видеочат",
    "changed the chat theme": "изменил тему чата",
    "changed the chat background": "изменил фон чата",
    "Schedule": "Запланировать",
    "Message will be sent at the selected time.": "Сообщение будет отправлено в выбранное время.",
    "Pick a time in the future.": "Выберите время в будущем.",
    "Date": "Дата",
    "Time": "Время",
    "Already scheduled in this chat": "Уже запланировано в этом чате",
    "No other scheduled messages in this chat.": "Других отложенных сообщений в этом чате нет.",
    "Deleting scheduled message": "Удаление отложенного сообщения",
    "No chats found.": "Чаты не найдены.",
    "Searching chats...": "Поиск чатов...",
    "Search Chats": "Поиск чатов",
    "Search a chat...": "Поиск чата...",
    "Enter your query to start searching (at least 5 characters needed)": "Введите запрос, чтобы начать поиск (нужно не менее 5 символов)",
    "Discussion group updated": "Группа обсуждения обновлена",
    "Discussion group removed": "Группа обсуждения удалена",
    "Error: %1": "Ошибка: %1",
    "Remove discussion group": "Удалить группу обсуждения",
    "Choose a group that will host discussion of channel posts.": "Выберите группу, в которой будут обсуждаться публикации канала.",
    "No suitable groups": "Нет подходящих групп",
    "Create a public supergroup or convert an existing one to use as discussion.": "Создайте публичную супергруппу или преобразуйте существующую для использования как обсуждение.",
    "Reload": "Перезагрузить",
    "Show stickers as emojis": "Показывать стикеры как эмодзи",
    "Only display emojis instead of the actual stickers": "Отображать только эмодзи вместо самих стикеров",
    "Show stickers as images": "Показывать стикеры как изображения",
    "Show background for stickers and align them centrally like images": "Показывать фон для стикеров и выравнивать их по центру, как изображения",
    "Animate stickers": "Анимировать стикеры",
    "Cyberpunk look (requires a dark and orange theme for the perfect experience)": "Вид киберпанк (для лучшего эффекта нужна тёмная и оранжевая тема)",
    "Silica base theme (lighter, also good on light themes)": "Базовая тема Silica (легче, хороша также при светлых темах)",
    "Choose RooTelegram's theme": "Выберите тему RooTelegram",
    "Silica (base theme)": "Silica (базовая тема)",
    "Neon (cyberpunk)": "Неон (киберпанк)",
    "Behavior": "Поведение",
    "Send message by enter": "Отправлять сообщение клавишей Enter",
    "Send your message by pressing the enter key": "Отправлять сообщение нажатием клавиши Enter",
    "Focus text input on chat open": "Активировать поле ввода при открытии чата",
    "Focus the text input area when entering a chat": "Активировать поле ввода при входе в чат",
    "Focus text input area after send": "Активировать поле ввода после отправки",
    "Focus the text input area after sending a message": "Активировать поле ввода после отправки сообщения",
    "Delay before marking messages as read": "Задержка перед отметкой сообщений как прочитанных",
    "RooTelegram will wait a bit before messages are marked as read": "RooTelegram немного подождёт, прежде чем сообщения будут отмечены как прочитанные",
    "Open-with menu integration": "Интеграция в меню «Открыть с помощью»",
    "Integrate RooTelegram into open-with menu of Sailfish OS": "Интегрировать RooTelegram в меню «Открыть с помощью» Sailfish OS",
    "Notification feedback": "Сигнализация уведомлений",
    "Use non-graphical feedback (sound, vibration) for notifications": "Использовать неграфическую сигнализацию (звук, вибрацию) для уведомлений",
    "All events": "Все события",
    "Only new events": "Только новые события",
    "Notification turns on the display": "Уведомление включает экран",
    "Enable notification sounds": "Включить звуки уведомлений",
    "When sounds are enabled, RooTelegram will use the current Sailfish OS notification sound for chats, which can be configured in the system settings.": "Когда звуки включены, RooTelegram будет использовать текущий звук уведомлений Sailfish OS для чатов, который можно настроить в системных настройках.",
    "Always append message preview to notifications": "Всегда добавлять превью сообщения в уведомления",
    "In addition to showing the number of unread messages, the latest message will also be appended to notifications.": "Помимо показа числа непрочитанных сообщений, в уведомления будет также добавляться последнее сообщение.",
    "Highlight unread messages": "Выделять непрочитанные сообщения",
    "Highlight Conversations with unread messages": "Выделять беседы с непрочитанными сообщениями",
    "Hide content in notifications": "Скрывать содержимое в уведомлениях",
    "Go to quoted message": "Переходить к цитируемому сообщению",
    "When tapping a quoted message, open it in chat instead of showing it in an overlay.": "При касании цитируемого сообщения открывать его в чате вместо показа во всплывающем окне.",
    "Cover: only private chats in unread count": "Обложка: только приватные чаты в счётчике непрочитанных",
    "Exclude groups and channels from the unread message and chat counts shown on the cover preview": "Исключить группы и каналы из счётчиков непрочитанных сообщений и чатов, показываемых на превью обложки",
    "Disable video preloading": "Отключить предзагрузку видео",
    "Disables automatic video preloading to reduce RAM/GPU and mobile data usage. Photos are still downloaded automatically.": "Отключает автоматическую предзагрузку видео для снижения нагрузки на ОЗУ/ГП и расхода мобильного трафика. Фото по-прежнему загружаются автоматически.",
    "Notifications": "Уведомления",
    "Show desktop notifications for new messages. The app always stays in background; this toggle controls only notification publishing.": "Показывать уведомления о новых сообщениях. Приложение всегда остаётся в фоне; этот переключатель управляет только публикацией уведомлений.",
    "Notify when a contact posts a new story.": "Уведомлять, когда контакт публикует новую историю.",
    "Notify when someone reacts to one of your messages.": "Уведомлять, когда кто-то реагирует на одно из ваших сообщений.",
    "Connection": "Подключение",
    "Proxies route your Telegram traffic through another server to bypass censorship. MTProto proxies (especially with Fake-TLS) are the most resistant to blocking. SOCKS5 proxies also cover voice and video calls.": "Прокси направляют ваш трафик Telegram через другой сервер для обхода цензуры. Прокси MTProto (особенно с Fake-TLS) наиболее устойчивы к блокировке. Прокси SOCKS5 также охватывают голосовые и видеозвонки.",
    "Add, enable and test connection proxies.": "Добавляйте, включайте и проверяйте прокси подключения.",
    "Privacy": "Конфиденциальность",
    "Allow adding me to groups and channels": "Разрешить добавлять меня в группы и каналы",
    "Privacy setting for managing who can add you to groups and channels.": "Настройка конфиденциальности: кто может добавлять вас в группы и каналы.",
    "Your contacts only": "Только ваши контакты",
    "Allow finding by phone number": "Разрешить поиск по номеру телефона",
    "Privacy setting for managing whether you can be found by your phone number.": "Настройка конфиденциальности: можно ли найти вас по номеру телефона.",
    "Show link in forwarded messages": "Показывать ссылку в пересланных сообщениях",
    "Privacy setting for managing whether a link to your account is included in forwarded messages.": "Настройка конфиденциальности: включается ли ссылка на ваш аккаунт в пересланные сообщения.",
    "Show phone number": "Показывать номер телефона",
    "Privacy setting for managing whether your phone number is visible.": "Настройка конфиденциальности: виден ли ваш номер телефона.",
    "Show profile photo": "Показывать фото профиля",
    "Privacy setting for managing whether your profile photo is visible.": "Настройка конфиденциальности: видно ли ваше фото профиля.",
    "Show status": "Показывать статус",
    "Privacy setting for managing whether your online status is visible.": "Настройка конфиденциальности: виден ли ваш статус в сети.",
    "Allow sending Location to inline bots": "Разрешить отправку местоположения встроенным ботам",
    "Some inline bots request location data when using them": "Некоторые встроенные боты запрашивают данные о местоположении при использовании",
    "Blocklist": "Список блокировки",
    "View": "Просмотреть",
    "Show the list of Telegram users you have blocked.": "Показать список заблокированных вами пользователей Telegram.",
    "Privacy setting for managing who can call you.": "Настройка конфиденциальности: кто может вам звонить.",
    "Everybody": "Все",
    "Nobody": "Никто",
    "Allow calls": "Разрешить звонки",
    "This is a Premium-only feature.": "Это функция только для Premium.",
    "Only selected": "Только выбранные",
    "Privacy updated": "Конфиденциальность обновлена",
    "Voice and video messages": "Голосовые и видеосообщения",
    "Who can send you voice messages and video notes (round videos). Premium feature.": "Кто может отправлять вам голосовые сообщения и видеозаметки (круглые видео). Функция Premium.",
    "Choose who can send you voice messages and video notes.": "Выберите, кто может отправлять вам голосовые сообщения и видеозаметки.",
    "Choose who cannot send you voice messages and video notes.": "Выберите, кто не может отправлять вам голосовые сообщения и видеозаметки.",
    "Everybody except": "Все, кроме",
    "Sessions": "Сеансы",
    "Session was terminated": "Сеанс завершён",
    "Terminating session": "Завершение сеанса",
    "Terminate Session": "Завершить сеанс",
    "This app": "Это приложение",
    "Active since: %1, last online: %2": "Активен с: %1, последний раз в сети: %2",
    "1 week": "1 неделя",
    "1 month": "1 месяц",
    "3 months": "3 месяца",
    "6 months": "6 месяцев",
    "1 year": "1 год",
    "Session Timeout": "Тайм-аут сеанса",
    "Inactive sessions will be terminated after this timeframe": "Неактивные сеансы будут завершены по истечении этого срока",
    "Storage": "Хранилище",
    "Enable online-only mode": "Включить режим «только онлайн»",
    "Disables offline caching. Certain features may be limited or missing in this mode. Changes require a restart of RooTelegram to take effect.": "Отключает офлайн-кэширование. В этом режиме некоторые функции могут быть ограничены или недоступны. Изменения требуют перезапуска RooTelegram.",
    "Enable storage optimizer": "Включить оптимизатор хранилища",
    "User Profile": "Профиль пользователя",
    "First Name": "Имя",
    "Enter 1-64 characters": "Введите от 1 до 64 символов",
    "Last Name": "Фамилия",
    "Enter 0-64 characters": "Введите от 0 до 64 символов",
    "Profile Pictures": "Изображения профиля",
    "Add Picture": "Добавить изображение",
    "Delete Picture": "Удалить изображение",
    "Deleting profile picture": "Удаление изображения профиля",
    "Log Out": "Выйти",
    "Logged out": "Выполнен выход",
    "Phone number: +%1": "Номер телефона: +%1",
    "Go to Channel": "Перейти к каналу",
    "Go to Message": "Перейти к сообщению",
    "Start Bot": "Запустить бота",
    "Sticker set successfully removed!": "Набор стикеров успешно удалён!",
    "Sticker set successfully installed!": "Набор стикеров успешно установлен!",
    "Main": "Главное",
    "No stories from your contacts": "Нет историй от ваших контактов",
    "Pull down to refresh": "Потяните вниз для обновления",
    "My Archive": "Мой архив",
    "You have no archived stories": "У вас нет архивированных историй",
    "(no caption)": "(без подписи)",
    "New story": "Новая история",
    "Delete story": "Удалить историю",
    "Blacklist is empty": "Чёрный список пуст",
    "Remove from blacklist": "Удалить из чёрного списка",
    "Add to blacklist": "Добавить в чёрный список",
    "Added to blacklist": "Добавлено в чёрный список",
    "Removed from blacklist": "Удалено из чёрного списка",
    "My Profile": "Мой профиль",
    "You have no stories on your profile": "У вас нет историй в профиле",
    "Archive": "Архив",
    "Profile": "Профиль",
    "Story": "История",
    "This story type is not supported yet": "Этот тип истории пока не поддерживается",
    "Deleting story": "Удаление истории",
    "Could not set reaction.": "Не удалось установить реакцию.",
    "Story not available": "История недоступна",
    "Audience": "Аудитория",
    "Done": "Готово",
    "No contacts or private chats.": "Нет контактов или приватных чатов.",
    "Custom audience": "Своя аудитория",
    "Publish": "Опубликовать",
    "Tap to change": "Коснитесь, чтобы изменить",
    "Caption": "Подпись",
    "Add a caption (optional)": "Добавить подпись (необязательно)",
    "Reading video…": "Чтение видео…",
    "Video too long: %1 (max %2)": "Видео слишком длинное: %1 (макс. %2)",
    "Duration: %1": "Длительность: %1",
    "Cannot determine your account.": "Не удалось определить ваш аккаунт.",
    "Posting story…": "Публикация истории…",
    "Video conversion failed.": "Не удалось преобразовать видео.",
    "Story posted": "История опубликована",
    "Could not post story.": "Не удалось опубликовать историю.",
    "Telegram stories are vertical (9:16). Your landscape video is being adapted before publishing.": "Истории Telegram вертикальные (9:16). Ваше горизонтальное видео адаптируется перед публикацией.",
    "Converting video": "Преобразование видео",
    "Uploading video": "Загрузка видео",
    "Everyone": "Все",
    "Selected contacts": "Выбранные контакты",
    "Choose contacts": "Выбрать контакты",
    "Allow screenshots": "Разрешить снимки экрана",
    "If off, the story is marked as protected: official clients block screenshots and forwarding.": "Если выключено, история помечается как защищённая: официальные клиенты блокируют снимки экрана и пересылку.",
    "Post to my profile": "Опубликовать в моём профиле",
    "Keep the story visible on your profile after the 24h expiration.": "Сохранять историю видимой в профиле после истечения 24 часов.",
    "Custom audience (%1)": "Своя аудитория (%1)",
    "Reply sent": "Ответ отправлен",
    "Send": "Отправить",
    "Reply to %1": "Ответить %1",
    "Reply to story": "Ответить на историю",
    "Reply": "Ответить",
    "Write a reply…": "Напишите ответ…",
    "Viewers": "Просмотревшие",
    "Telegram user": "Пользователь Telegram",
    "Forwarded": "Переслано",
    "Reposted": "Репостнуто",
    "No viewers yet": "Пока нет просмотров",
    "Banned until %1": "Заблокирован до %1",
    "Banned": "Заблокирован",
    "Unable to load members for this chat.": "Не удалось загрузить участников этого чата.",
    "There are no removed users.": "Нет удалённых пользователей.",
    "No administrators found.": "Администраторы не найдены.",
    "Joined %1": "Присоединился %1",
    "Unbanning…": "Разблокировка…",
    "Unban": "Разблокировать",
    "User has been unbanned.": "Пользователь разблокирован.",
    "Apply now": "Применить сейчас",
    "Neon theme": "Тема Неон",
    "Silica theme": "Тема Silica",
    "Cyberpunk look": "Вид киберпанк",
    "Base theme": "Базовая тема",
    "Circuit background, neon glow on menus, buttons and titles, rounded avatars and glass cards. Heavier: requires a dark and orange theme for the perfect experience.": "Фон со схемами, неоновое свечение на меню, кнопках и заголовках, скруглённые аватары и стеклянные карточки. Тяжелее: для лучшего эффекта нужна тёмная и оранжевая тема.",
    "Native flat menus, square avatars, no custom background, standard Silica colors. Lighter and clearly readable also on light system themes.": "Нативные плоские меню, квадратные аватары, без своего фона, стандартные цвета Silica. Легче и хорошо читается также при светлых системных темах.",
    "Apply this theme now?": "Применить эту тему сейчас?",
    "Copy video to gallery": "Копировать видео в галерею",
    "A video conversion is already in progress.": "Преобразование видео уже выполняется.",
    "Video converter not available.": "Конвертер видео недоступен.",
    "Source video not found.": "Исходное видео не найдено.",
    "Could not start the video converter.": "Не удалось запустить конвертер видео.",
    "Record a Voice Note": "Записать голосовую заметку",
    "Press the button to start recording": "Нажмите кнопку, чтобы начать запись",
    "Starting": "Запуск",
    "Recording": "Запись",
    "Stopping": "Остановка",
    "Use recording": "Использовать запись",
    "Voice Note (%1)": "Голосовая заметка (%1)",
    "Ready": "Готово",
    "Preview not supported for this link...": "Превью не поддерживается для этой ссылки...",
    "Continua": "Продолжить",
    "Novità": "Что нового",
    "Video: %1": "Видео: %1",
    "Picture: %1": "Изображение: %1",
    "Audio: %1": "Аудио: %1",
    "Voice Note: %1": "Голосовая заметка: %1",
    "Animation: %1": "Анимация: %1",
    "Document: %1": "Документ: %1",
    "%1M": "%1 млн",
    "%1K": "%1 тыс.",
    "was never online": "никогда не был в сети",
    "last online: last month": "последний раз в сети: в прошлом месяце",
    "last online: last week": "последний раз в сети: на прошлой неделе",
    "last online: %1": "последний раз в сети: %1",
    "online": "в сети",
    "was recently online": "недавно был в сети",
    "Admin": "Администратор",
    "Creator": "Создатель",
    "Restricted": "Ограничен",
    "changed the chat title to %1": "изменил название чата на %1",
    "sent an anonymous quiz": "отправил анонимную викторину",
    "sent an anonymous poll": "отправил анонимный опрос",
    "Anonymous Quiz": "Анонимная викторина",
    "Quiz": "Викторина",
    "Anonymous Poll": "Анонимный опрос",
    "Unable to find user %1": "Не удалось найти пользователя %1",
    "You are already a member of this chat.": "Вы уже участник этого чата.",
    "Closed!": "Закрыто!",
    "Pending acknowledgement": "Ожидает подтверждения",
    "created topic: %1": "создал тему: %1",
    "renamed topic to: %1": "переименовал тему в: %1",
    "edited topic icon": "изменил значок темы",
    "closed topic": "закрыл тему",
    "reopened topic": "снова открыл тему",
    "edited topic": "изменил тему",
    "hid topic": "скрыл тему",
    "unhid topic": "показал тему",
    "Send shared content": "Отправить общий контент",
    "Unknown caller": "Неизвестный абонент",
    "Calling…": "Вызов…",
    "Incoming voice call": "Входящий голосовой звонок",
    "Exchanging encryption keys…": "Обмен ключами шифрования…",
    "Ending call…": "Завершение звонка…",
    "Decline": "Отклонить",
    "Accept": "Принять",
    "Unmute": "Включить звук",
    "Mute": "Выключить звук",
    "End call": "Завершить звонок",
    "Call declined": "Звонок отклонён",
    "No answer": "Нет ответа",
    "Missed call": "Пропущенный звонок",
    "Call failed": "Звонок не удался",
    "Speaker off": "Динамик выкл.",
    "Speaker": "Динамик",
    "Incoming video call": "Входящий видеозвонок",
    "Video not\navailable": "Видео\nнедоступно",
}

RUN = {
    "%n scheduled message(s)": ("%n запланированное сообщение", "%n запланированных сообщения", "%n запланированных сообщений"),
    "%n chat(s)": ("%n чат", "%n чата", "%n чатов"),
    "%1 blocked": ("%1 заблокирован", "%1 заблокированных", "%1 заблокированных"),
    "%1 subscribers": ("%1 подписчик", "%1 подписчика", "%1 подписчиков"),
    "%1 members": ("%1 участник", "%1 участника", "%1 участников"),
    "%1 online": ("%1 в сети", "%1 в сети", "%1 в сети"),
    "%Ln Messages deleted": ("Удалено %Ln сообщение", "Удалено %Ln сообщения", "Удалено %Ln сообщений"),
    "%Ln messages have been copied": ("Скопировано %Ln сообщение", "Скопировано %Ln сообщения", "Скопировано %Ln сообщений"),
    "Forward %Ln messages": ("Переслать %Ln сообщение", "Переслать %Ln сообщения", "Переслать %Ln сообщений"),
    "%Ln messages selected": ("Выбрано %Ln сообщение", "Выбрано %Ln сообщения", "Выбрано %Ln сообщений"),
    "%Ln join requests": ("%Ln запрос на вступление", "%Ln запроса на вступление", "%Ln запросов на вступление"),
    "chats": ("чат", "чата", "чатов"),
    "unread messages": ("непрочитанное сообщение", "непрочитанных сообщения", "непрочитанных сообщений"),
    "Delete %Ln message(s)?": ("Удалить %Ln сообщение?", "Удалить %Ln сообщения?", "Удалить %Ln сообщений?"),
    "%Ln messages of album deleted": ("Удалено %Ln сообщение альбома", "Удалено %Ln сообщения альбома", "Удалено %Ln сообщений альбома"),
    "%n comment(s)": ("%n комментарий", "%n комментария", "%n комментариев"),
    "scored %Ln points in %2": ("набрал %Ln очко в %2", "набрал %Ln очка в %2", "набрал %Ln очков в %2"),
    "%Ln%": ("%Ln%", "%Ln%", "%Ln%"),
    "%Ln vote(s) total": ("%Ln голос всего", "%Ln голоса всего", "%Ln голосов всего"),
    "%Ln unread messages": ("%Ln непрочитанное сообщение", "%Ln непрочитанных сообщения", "%Ln непрочитанных сообщений"),
    "Question (%Ln characters left)": ("Вопрос (осталось %Ln символ)", "Вопрос (осталось %Ln символа)", "Вопрос (осталось %Ln символов)"),
    "Answer (%Ln characters left)": ("Ответ (осталось %Ln символ)", "Ответ (осталось %Ln символа)", "Ответ (осталось %Ln символов)"),
    "%Ln vote(s)": ("%Ln голос", "%Ln голоса", "%Ln голосов"),
    "%Ln vote(s) including yours": ("%Ln голос, включая ваш", "%Ln голоса, включая ваш", "%Ln голосов, включая ваш"),
    "scored %Ln points": ("набрал %Ln очко", "набрал %Ln очка", "набрал %Ln очков"),
    "On (%n configured)": ("Вкл. (%n настроен)", "Вкл. (%n настроено)", "Вкл. (%n настроено)"),
    "Off (%n configured)": ("Выкл. (%n настроен)", "Выкл. (%n настроено)", "Выкл. (%n настроено)"),
    "%1 day(s)": ("%1 день", "%1 дня", "%1 дней"),
    "%n new story(es)": ("%n новая история", "%n новые истории", "%n новых историй"),
    "%n story(es)": ("%n история", "%n истории", "%n историй"),
    "Choose who will see your next story (%n selected).": ("Выберите, кто увидит вашу следующую историю (выбран %n).", "Выберите, кто увидит вашу следующую историю (выбрано %n).", "Выберите, кто увидит вашу следующую историю (выбрано %n)."),
    "Members of your custom audience (%n selected). Saved across stories.": ("Участники вашей аудитории (выбран %n). Сохраняется между историями.", "Участники вашей аудитории (выбрано %n). Сохраняется между историями.", "Участники вашей аудитории (выбрано %n). Сохраняется между историями."),
    "(%n selected)": ("(выбран %n)", "(выбрано %n)", "(выбрано %n)"),
    "%n contact(s) selected": ("Выбран %n контакт", "Выбрано %n контакта", "Выбрано %n контактов"),
    "%n view(s)": ("%n просмотр", "%n просмотра", "%n просмотров"),
    "%n reaction(s)": ("%n реакция", "%n реакции", "%n реакций"),
}


def esc(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def repl_message(m: re.Match) -> str:
    block = m.group(0)
    raw_src = m.group("src")
    src = html.unescape(raw_src)
    if m.group("num") is not None:
        forms = RUN.get(src)
        if forms is None:
            return block
        nf = "".join(f"<numerusform>{esc(f)}</numerusform>" for f in forms)
        new_tr = f"<translation>{nf}</translation>"
    else:
        tr = RU.get(src)
        if tr is None:
            return block
        new_tr = f"<translation>{esc(tr)}</translation>"
    return re.sub(r'<translation[^>]*>.*?</translation>', new_tr, block, count=1, flags=re.S)


def main():
    data = EN.read_text(encoding="utf-8")
    data = data.replace('language="en"', 'language="ru"', 1)
    pattern = re.compile(
        r'<message(?P<num> numerus="yes")?>(?P<body>.*?<source>(?P<src>.*?)</source>.*?)</message>',
        re.S,
    )
    out = pattern.sub(repl_message, data)
    OUT.write_text(out, encoding="utf-8")
    print(f"Scritto {OUT} — unfinished residui: {out.count('type=\"unfinished\"')}")


if __name__ == "__main__":
    main()
